repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        types: [yaml, markdown]
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=8192]
