:PROPERTIES:
:ID:       05ac9c63-4b61-4192-b305-69e531064c22
:mtime:    20251119123519 20250613002047
:ctime:    20250613002047
:END:
#+TITLE: Android ADB
#+FILETAGS: :android:bash:shell:

You can get files from (and too) your phone if you have USB Debugging enabled and the Android SDK installed on your
computer.

* Setup

You have to [[https://developer.android.com/studio/debug/dev-options#enable][enable developer options]] on your phone, since I use [[id:86e356e8-931f-40f7-9393-13a89c22c00d][LineageOS]] I followed their [[https://wiki.lineageos.org/adb_fastboot_guide][instructions]]. I did find
after upgrading that whilst this option was enabled I didn't have the necessary access, the ~adb device~ didn't list the
device and the phone didn't show anything. Rebooting sorted this.

* Pull multiple files

Typically you can only pull one file, but with a bit of [[id:48c0d280-8330-4f65-a5da-098ea186c6b6][Bash xarg]] magic you can pull multiple files across. Based on
answers in [[https://stackoverflow.com/questions/11074671/adb-pull-multiple-files][this thread]] the following got me all pictures for a given day onto my local computer.

#+begin_example sh
adb shell 'find /storage/self/primary/DCIM/Camera/IMG_20250522_*.jpg -print0' | xargs -0 -n 1 adb pull
#+end_example

Another alternative is a ~for~ loop

#+being_example sh
for file in $(adb shell ls /storage/self/primary/OpenTracks\ GPX/2026-03-*); do
    adb pull "${file}"
done
#+end_example

That said neither of the above doesn't work when there is a space in the directory path :-/

* Push multiple files

Much easier to push multiple files

#+begin_example sh
adb push path\ to\ directory /storage/<dev>/target/path/.
#+end_example

* Trouble Shooting

** ~operation not permitted~
I encountered this on occasions when trying to use ~adb push~. One possible solution is to restart
adb as ~root~

#+begin_example
adb root
#+end_example

This didn't seem to work when trying to push a directory with lots of files. I opted to zip the directory up and push
the ~.zip~ which did work.

** ~unauthorized~

If the device is showing as ~unauthorized~ when listed with ~adb devices~ then toggle /Settings > Developer Options
> Revoke USB debugging authorisations/ ([[https://stackoverflow.com/a/25546300][via]])
