:PROPERTIES:
:ID:       a53fa3c5-f091-4715-a1a4-a94071407abf
:mtime:    20251224100757 20251207121740 20250829223721 20250515103508 20250514112953 20250406203704 20250406160925 20250226152510 20241124190532 20240523145115 20240523132208 20240502105958 20231022214824 20230908084133 20230907222812 20230813184404 20230812222550 20230623080100 20230215101306
:ctime:    20230215101306
:END:
#+TITLE: Arch Linux
#+FILETAGS: :gnu:linux:arch:

I've used [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] for many years but I found my an ageing 12 year old laptop that compiling was taking longer and longer
(compared to my main system at least!). I also had a number of [[id:69864d74-8ec2-42e4-a227-f824a521a5ce][Raspberry Pis]] that I didn't want to have to setup cross
compiling environments in order to run Gentoo on. I still wanted a rolling distribution though that always had the
latest version of packages installed. Enter [[https://archlinux.org][Arch Linux]] and [[https://archlinuxarm.org/][Arch Linux ARM]].

+ [[id:9bf2dfc3-ff49-49b2-8507-503f64649f7a][Pacman]] the default package manager.

Install notes for different systems

+ Raspberry Pi Zero W
+ [[id:742ab443-39f4-4cf6-a5ca-cb486578ad94][Raspberry Pi 4b]]
+ [[id:84523969-a4c2-4349-ac23-09894939ed54][T490s]]

* ~systemd~

By default Arch uses [[https://systemd.io][~systemd~]] for starting and running services.

** Services

To add a service

#+begin_src bash
systemctl enable --now <unit>.service
#+end_src

To start/stop/restart/status a service

#+begin_src bash
systemctl [start|stop|restart|status] <unit>.service
#+end_src

** ~netctl~

~netctl~ is a subunit specifically concerned with netwoking.

** ~journalctl~

~journalctl~ is a programme for reading the log files from ~systemd~. To follow logs for a specific service in real time
you can use ~journalctl -fu <unit>.service~.

** Java

There are many options for [[https://wiki.archlinux.org/title/Java][Java]] on Arch Linux, to list and switch between the different versions you should use
~archlinux-java~ which will list the available options and allow you to ~set~ the default.

* Derivatives

There are a few Arch Linux based distros around.  [[https://manjaro.org/][Manjaro]] is popular and [[https://cachyos.org/][CachyOS]] is a version optimised for
performance/speed.

* Links

+ [[https://wiki.archlinux.org/][Arch Linux Wiki]]
+ [[https://bbs.archlinux.org/][Arch Linux Forums]] (annoyingly like [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] they still use BBcode rather than Markdown).

** Arch based distros

+ [[https://manjaro.org/][Manjaro]]
+ [[https://cachyos.org/][CachyOS]]
