:PROPERTIES:
:ID:       742ab443-39f4-4cf6-a5ca-cb486578ad94
:mtime:    20251212223257 20251212195343 20251212103425 20251211094111 20251211003606 20251208213404 20251208202826 20251208175553 20251207212421 20251207194725 20251207121232
:ctime:    20251207121232
:END:
#+TITLE: Arch Raspberry Pi 4b
#+FILETAGS: :linux:arch:install:config:

I've used [[https://archlinuxarm.org/][ArchLinuxARM]] on my Raspberry Pi's for some time now as I like rolling distributions but at the time [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]]
didn't offer binary distributions for packages (that has now changed). They mostly work well although support for the Pi
Zero W of which I own five or six is no longer available. One day I may upgrade these to Gentoo as they are [[https://wiki.gentoo.org/wiki/Raspberry_Pi][supported]].

The instructions below are based on reinstalling as for some reason one day the external 5TB USB drive which serves as
the main storage for the device, backing up music, video, references etc. was no longer detected. I checked it wasn't a
hardware problem by booting from a new install and it was detected and rather than fighting trying to work out why USB
drivers weren't loaded on the current install I opted for a fresh as I had purchased two new 64GB microSD cards and
wanted to make a fresh install on one then make a backup (using ~dd~) to the other so I had a a spare which I would
periodically update should the in-use one ever die.

As such I already had a list of explicitly installed packages available via Pacman from the existing system (which
thankfully still booted at least!). I also had my configuration backed up using [[id:48249b0d-eeba-484a-8f00-808a14169692][~etckeeper~]].

* Existing System

** Installed Packages

Extract a list of explicitly installed packages using the following which removes the package version and leaves a plain
list of the packages to be installed which is piped to a file

#+begin_example sh
pacman -Qe | awk -F" " '{print $1}' > /home/user/tmp/pacman-Qe
#+end_example

This includes packages that have been installed from [[id:fb505adf-5df0-4d6e-a7b1-9853044653c5][AUR]] which will have to be handled separately. Typically I keep
these under ~~/aur/~ so it was possible for me to easily edit this. I found out [[https://unix.stackexchange.com/a/297876][afterwards]] you can use the ~-n~ flag to
get just native packages so really you should use...

#+begin_example sh
pacman -Qen | awk -F" " '{print $1}' > /home/user/tmp/pacman-Qen
#+end_example


** Backup ~/etc~

Make sure ~/etc~ is up-to-date and backed up.

#+begin_example sh
su
cd /etc
etckeeper commit
git push
#+end_example

Shutdown and switch microSD cards to the new system, boot the new microSD and use [[id:ae1e9b97-feb0-4f1a-b804-b89edaf5a790][SSH]] to connect to the device over
ethernet.


* Install

Follow the [[https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-4][installation instructions]] to download and install the pre-built image to a microSD card. I opted to use
~gparted~ to split the ~/~ (root) partition/file-system where the operating system lives and the ~/home~
partition/file-system as I find this to be good practice for separating the two should things be corrupt. Make sure to
format the ~/home~, I keep my life simple and use ~ext4~.

Default account and passwords are...

| Account | Password |
|---------+----------|
| ~alarm~ | ~alarm~  |
| ~root~  | ~root~   |

Boot the device using the new microSD, ideally with a wired ethernet connection which makes SSHing in easier. Once
booted you should be able to [[id:ae1e9b97-feb0-4f1a-b804-b89edaf5a790][SSH]] in and you should login using the ~alarm~ account details.


#+begin_example sh
ssh alarm@192.168.1.215
#+end_example

At a basic level you now have a functioning system, but its not (yet) configured to do everything you want/need. In my
case I'm restoring functionality from an old system.

* USB Troubles

Using the "latest" image built 2025-11-03 we see the following in ~dmesg~ for USB

#+begin_example
[root@alarmpi alarm]# dmesg | grep usb -i
[    1.602053] usbcore: registered new interface driver usbfs
[    1.602084] usbcore: registered new interface driver hub
[    1.602114] usbcore: registered new device driver usb
[    2.293631] usbcore: registered new interface driver lan78xx
[    2.293662] usbcore: registered new interface driver smsc95xx
[    2.403239] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[    2.405681] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 2
[    2.405696] xhci_hcd 0000:01:00.0: Host supports USB 3.0 SuperSpeed
[    2.405831] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.12
[    2.405846] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.405857] usb usb1: Product: xHCI Host Controller
[    2.405866] usb usb1: Manufacturer: Linux 6.12.56-1-rpi xhci-hcd
[    2.405874] usb usb1: SerialNumber: 0000:01:00.0
[    2.406153] hub 1-0:1.0: USB hub found
[    2.406439] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 6.12
[    2.406454] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.406465] usb usb2: Product: xHCI Host Controller
[    2.406474] usb usb2: Manufacturer: Linux 6.12.56-1-rpi xhci-hcd
[    2.406482] usb usb2: SerialNumber: 0000:01:00.0
[    2.406698] hub 2-0:1.0: USB hub found
[    2.407465] usbcore: registered new interface driver uas
[    2.407505] usbcore: registered new interface driver usb-storage
[    2.409442] usbcore: registered new interface driver usbhid
[    2.409451] usbhid: USB HID core driver
[    2.673172] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    2.828450] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
[    2.828477] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    2.828488] usb 1-1: Product: USB2.0 Hub
[    2.830051] hub 1-1:1.0: USB hub found
[    9.650413] usbcore: registered new interface driver brcmfmac
#+end_example

...and USB devices are detected and can be mounted.

The packages that were upgraded were...

#+begin_example
[root@alarmpi alarm]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (48) archlinux-keyring-20251116-1  bash-5.3.8-1  binutils-2.45.1-1  ca-certificates-mozilla-3.119-1  coreutils-9.9-1  curl-8.17.0-2  device-mapper-2.03.37-1  dhcpcd-10.3.0-1  e2fsprogs-1.47.3-2  gcc-libs-15.2.1+r301+gf24307422d1d-1  glib2-2.86.2-1  glibc-2.42+r33+gde1fe81f4714-1  gnutls-3.8.11-2
              hwdata-0.401-1  iana-etc-20251114-1  icu-78.1-1  iproute2-6.18.0-1  libarchive-3.8.4-1  libbpf-1.6.2-1  libelf-0.194-1.1  libnftnl-1.3.1-1  libnghttp3-1.13.1-1  libnl-3.12.0-1  libsysprof-capture-49.0-1.1  libxcrypt-4.5.2-1  libxml2-2.15.1-4  linux-api-headers-6.17-1  linux-firmware-20251125-2
              linux-firmware-amdgpu-20251125-2  linux-firmware-atheros-20251125-2  linux-firmware-broadcom-20251125-2
linux-firmware-cirrus-20251125-2  linux-firmware-intel-20251125-2  linux-firmware-mediatek-20251125-2  linux-firmware-nvidia-20251125-2  linux-firmware-other-20251125-2
              linux-firmware-radeon-20251125-2  linux-firmware-realtek-20251125-2  linux-firmware-whence-20251125-2  linux-rpi-6.12.60-1  mkinitcpio-40-2  nano-8.7-1  raspberrypi-bootloader-20251202-1  sqlite-3.51.1-1  systemd-258.2-2  systemd-libs-258.2-2  systemd-resolvconf-258.2-2  systemd-sysvcompat-258.2-2

Total Installed Size:  1353.60 MiB
Net Upgrade Size:        25.27 MiB
#+end_example

After rebooting USB devices are not detected and there are less modules loaded by the kernel

#+begin_example
[root@alarmpi alarm]# dmesg | grep usb -i
[    1.602076] usbcore: registered new interface driver usbfs
[    1.602104] usbcore: registered new interface driver hub
[    1.602130] usbcore: registered new device driver usb
[    2.363677] usbcore: registered new interface driver lan78xx
[    2.363709] usbcore: registered new interface driver smsc95xx
[    2.472639] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[   19.497567] xhci_hcd 0000:01:00.0: USB bus 1 deregistered
[   19.498067] usbcore: registered new interface driver uas
[   19.498098] usbcore: registered new interface driver usb-storage
[   19.500023] usbcore: registered new interface driver usbhid
[   19.500033] usbhid: USB HID core driver
[   30.477898] usbcore: registered new interface driver brcmfmac
#+end_example


* Configuration

The first few steps were undertaken on the existing system to make it easy to install/upgrade/configure the new system


** Upgrade

I found the ArchLinux image from 2025-12-07 was broken as well and have posted on the forums about this issue (see
[[https://archlinuxarm.org/forum/viewtopic.php?f=60&t=17365&p=73853#p73853][thread]]) but fortunately had an image I'd downloaded a few days previously 2025-11-03 which did work. I therefore set
about restoring my system from this but explicitly disabled all Linux kernel related packages from being upgraded by
adding them to ~IgnorePkg~ in ~/etc/pacman.conf~


#+begin_example conf
IgnorePkg = linux-rpi linux-api-headers linux-firmware linux-firmware-amdgpu linux-firmware-atheros linux-firmware-broadcom linux-firmware-cirrus linux-firmware-intel linux-firmware-mediatek linux-firmware-nvidia linux-firmware-cirrus linux-firmware-other linux-firmware-radeon linux-firmware-realtek linux-firmware-whence raspberrypi-bootloader
#+end_example

#+begin_example sh
pacman-key --init
pacman-key --populate archlinuxarm
pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
  warning: linux-api-headers: ignoring package upgrade (6.16-2 => 6.17-1)
warning: linux-firmware: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-amdgpu: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-atheros: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-broadcom: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-cirrus: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-intel: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-mediatek: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-nvidia: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-other: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-radeon: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-realtek: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-firmware-whence: ignoring package upgrade (20251021-1 => 20251125-2)
warning: linux-rpi: ignoring package upgrade (6.12.56-1 => 6.12.61-1)
warning: raspberrypi-bootloader: ignoring package upgrade (20251031-1 => 20251208-2)
resolving dependencies...
looking for conflicting packages...
Packages (34) archlinux-keyring-20251116-1  bash-5.3.8-1  binutils-2.45.1-1  ca-certificates-mozilla-3.119-1
              coreutils-9.9-1  curl-8.17.0-2  device-mapper-2.03.37-1  dhcpcd-10.3.0-1  e2fsprogs-1.47.3-2
              gcc-libs-15.2.1+r301+gf24307422d1d-1  glib2-2.86.3-1  glibc-2.42+r33+gde1fe81f4714-1  gnutls-3.8.11-2
              hwdata-0.402-1  iana-etc-20251114-1  icu-78.1-1  iproute2-6.18.0-1  libarchive-3.8.4-1  libbpf-1.6.2-1
              libelf-0.194-1.1  libidn2-2.3.8-1  libnftnl-1.3.1-1  libnghttp3-1.13.1-1  libnl-3.12.0-1
              libsysprof-capture-49.0-1.1  libxcrypt-4.5.2-1  libxml2-2.15.1-4  mkinitcpio-40-2  nano-8.7-1
              sqlite-3.51.1-1  systemd-258.2-2  systemd-libs-258.2-2  systemd-resolvconf-258.2-2
              systemd-sysvcompat-258.2-2
Total Download Size:    85.69 MiB
Total Installed Size:  423.37 MiB
Net Upgrade Size:       18.30 MiB
:: Proceed with installation? [Y/n] y
#+end_example

At this point I rebooted the system to ensure I could still detect the USB hub that allows peripherals to be plugged in
and detected such as my external USB drive and the microSD adapter from which I was going to restore packages from.

Success, upgraded essential packages and USB devices were still detected and could be mounted.

** Change ~root~ password

Change the ~root~ password to something only you know.

#+begin_example sh
su
passwd
#+end_example

*NB* From this point forward it is assumed commands are carried out as ~root~ unless otherwise explicitly stated.



** Install essential tools

Whilst I intended to restore all packages installed from the old system a couple of essentials were installed first. As I
didn't sit down and do this all in one go I installed ~tmux~ and ~kitty~ so I could have a persistent session and
~rsync~ for copying files between the old and new system and ~arch-install-scripts~ which include ~arch-chroot~ so I
could ~chroot~ to the old install and poke around if needed

#+being_example sh
pacman -Syu tmux kitty rsync arch-chroot
#+end_example

** Mount old filesystems

As I've a bunch of configuration files I want to use to setup the new system and an existing ~/home~ partition I wish to
migrate I needed to mount the old file system. I used a simple SD-card to USB adapter to plug the old card in it was
automatically detected and I could mount and ~chroot~ to it.

#+begin_example sh
su
mkdir /mnt/old
mount /dev/sdb2 /mnt/old
mount /dev/sdb1 /mnt/old/boot
mount /dev/sdb3 /mnt/old/home
arch-chroot /mnt/old
#+end_example

This allows me to perform actions under my old system if needed, but the files are also accessible to be copied to the
new system.

*** Copy ~root~ home directory from old system

I have some custom [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]] aliases, custom ~$PS1~ and some other configuration files and scripts on my old system under the
~root~ accounts home directory so I wanted to copy these over. Pretty straight-forward once the drives are mounted.

#+begin_example sh
cd /root/
rsync -av /mnt/old/root/.* .
rsync -av /mnt/old/root/* .
source ~/.bashrc
#+end_example


** Mount the new ~/home~ partition

I split the ~/~ (root) and ~home~ partitions on the new drive but it did not know about the new system so I needed to
sort that out by mounting it, copying the old ~/home~ over and the current ~/home~ (which contains the basic ~alarm~
account details).

#+begin_example sh
mkdir -p /mnt/new/home
mount /dev/mmcblk0p3 /mnt/new/home
#+end_example

As with ~root~ home directory we can now ~rsync~ the old to the new. I had a few user accounts setup for friends so this
copies their home directories over too (see below on restoring their accounts).

#+begin_example sh
cd /mnt/new/home
rsync -av /mnt/old/home/* /mnt/new/home/. --exclude=".cache"
#+end_example


** Install packages from old system

We saved the old packages that were explicitly installed to what is now ~/mnt/old/home/user/tmp/pacman-Qen~ and can use
this to install all these packages on the new system. Because I have masked ~linux*~ and ~raspberrypi-bootloader~
packages I explicitly removed these from the file before using it to install packages on the new system.

#+begin_example sh
  pacman -Syu - < /mnt/old/home/user/tmp/pacman-Qen
#+end_example

This upgraded 601 packages which I left to run. ~calibre~ was skipped due to unresolved dependencies, but for now I
wasn't too bothered as they've introduced "[[id:e23a0f6e-6276-4443-bd01-bc7cfd7ec8c5][Artificial Intelligence]]" and I'd
rather not be spied on or contribute to these pernicious systems.

*** Extra Installs

Needed/decided to install a few extra packages base don recommendations.

#+begin_example
pacman -Syu zsh-lovers mugshot cups sane hddtemp python-pylint flake8 python-pyflakes python-pydocstyle ipython
postgresql-old-upgrade just rustfmt shfmt prettier fzf
# pacman -Syu yt-dlp-ejs
#+end_example

*** AUR packages

If you only use ~pacman -Qe~ to get a list of explicitly installed packages and didn't restrict to native packages then
you may want to first edit this file and move all entries to packages that were installed from AUR to a separate file so
you have a record. If you don't ~pacman~ will complain that there is no such package available at which point you can
move it over (I found my ~~/aur~ directory wasn't a complete  representation of everything I had installed from AUR so
had a few packages to move over).

You could get a diff of what packages are installed via AUR using something like

#+being_example sh
diff $(pacman -Qe) $(pacman -Qen)
#+end_example


** Setup user accounts

I wanted to restore my old user accounts so had to pay careful attention to the ~gid~ already assigned. Useful reference
(as I don't do this often) is the [[https://wiki.archlinux.org/title/Users_and_groups][Users and groups]] wiki page.

We can see what groups each account was a member of by looking at ~/mnt/old/etc/group~

#+begin_example sh
grep -E "user|user2|user3|user4" /mnt/old/etc/group
wheel:x:998:user
users:x:985:user,user2,user3,user4
user:x:1001:
user2:x:1002:
user3:x:1003:
user4:x:1006:
#+end_example

Deliberately exclude the ~-m~ flag as we are restoring the ~/home/user~ directory.

#+begin_example sh
  useradd -G users,wheel user
  passwd user
#+end_example

*** Other accounts

I don't know what passwords I set for others, or if they change them. I could create new accounts for them and set new
passwords however, account passwords are hashed in the ~/etc/shadow~ file so I wondered if I could use that to restore
the old accounts passwords without having knowledge of them (maybe!). I checked the hashes of ~user~ under ~/etc/shadow~
and ~/mnt/old/etc/shadow~ to see if they matched (and yes I reused the same password) but they didn't to which end I
opted to manually recreate the user accounts using the flag/parameter ~-u ####~ to ensure the user ID matched that under
the olda ccount. I deferred setting the passwords until a later point for these users.

#+begin_example sh
useradd -u 1002 -G users user2
useradd -u 1003 -G users user3
useradd -u 1006 -G users user4
#+end_example

*** sudo

Edit ~/etc/sudoers~ to allow all members of the ~wheel~ group (in this guide only one account has been added to the
group) so that [[https://aur.archlinux.org/][AUR]] packages can be installed

#+begin_example conf
##
## User privilege specification
##
root ALL=(ALL:ALL) ALL
## Uncomment to allow members of group wheel to execute any command
%wheel ALL=(ALL:ALL) ALL
#+end_example

** ~/etc/fstab~

I needed to...

+ make sure the new ~/home~ partition is correctly mounted on booting (note we copied ~/home/alarm~ over to
  ~/mnt/old/home/~ already but will eventually delete this account).
+ Mount the external USB drive.

#+begin_example sh
  cd /home
  rm -rf alarm
#+end_example

Edit ~/etc/fstab~ to reflect the desired mounts. The external drive has a ~LABEL~ (set using ~e2label~).

#+begin_example
#+end_example

** ALSA

Made two sets of changes to set the default soundcard to the IQAduioDAC I have based on suggestions [[https://superuser.com/questions/626606/how-to-make-alsa-pick-a-preferred-sound-device-automatically][here]]

#+begin_example
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: IQaudIODAC [IQaudIODAC], device 0: IQaudIO DAC HiFi pcm512x-hifi-0 [IQaudIO DAC HiFi pcm512x-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
#+end_example

*** /etc/modprobe.d/alsa-base.conf

#+begin_example
options vc4 enable=1 index=0
options vc4 enable=0 index=1
options snd_soc_iqaudio_dac=-2
#+end_example

*** /etc/asound.conf

#+begin_example
pcm.!default {
    type hw
    card 2 # IQaudIODAC
}
ctl.!default {
    type hw
    card 2 # IQaudIODAC
}
pcm.dsp {
    type plug
    slave.pcm "dmix"
}
#+end_example


** [[id:83df78ca-e349-418f-ab71-b7735c16d027][MPD]]

I found I had to create the log file and change permissions

#+begin_example
touch /var/log/mpd.log
chown mpd:mpd /var/log/mpd.log
#+end_example

I copied my old configuration over and ~mpd~ started without any problems

#+begin_example
systemctl enable --now mpd.service
systemctl status mpd.service
* mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/system/mpd.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/mpd.service.d
             `-00-arch.conf
     Active: active (running) since Fri 2025-12-12 19:28:28 UTC; 3h 1min ago
 Invocation: 40e76482e91f48e38a1607f6b6832d13
TriggeredBy: * mpd.socket
       Docs: man:mpd(1)
             man:mpd.conf(5)
   Main PID: 435 (mpd)
      Tasks: 7 (limit: 4915)
        CPU: 15min 30.370s
     CGroup: /system.slice/mpd.service
             `-435 /usr/bin/mpd --systemd

Dec 12 19:27:07 alarmpi systemd[1]: Starting Music Player Daemon...
Dec 12 19:27:10 alarmpi mpd[435]: Ignoring the 'pid_file' setting in systemd mode
Dec 12 19:28:28 alarmpi systemd[1]: Started Music Player Daemon.
#+end_example


** [[id:7c341a0b-a59b-403e-a574-061d326c4c50][snapcast]]

I use [[https://github.com/snapcast/snapcast][Snapcast]] to provide multi-room synchronised audio around my home. Input comes from ~mpd~ and the Pi4 acts as both
a server and client (I have an iQaudio DAC connected which is plugged into an Onkyo amplifier).

There is a ~PKGBUILD~ on [[https://aur.archlinux.org/packages/snapcast][AUR]] but compiling on the Pi4 required some tweaks (which I had made in the [[https://aur.archlinux.org/packages/snapcast#comment-1015464][past]]).

Edit ~/etc/makepkg.conf~ and add to ~CFLAGS~ the option ~-mno-omit-leaf-frame-pointer~, this left me with the following
options...

#+begin_example conf
CFLAGS="-march=armv7-a -mfloat-abi=hard -mfpu=neon -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection \
        -fno-omit-frame-pointer"
#+end_example

You can then clone the repository if you haven't already and install. If you have already cloned and tried building you
will have to remove the ~src~ directory.

#+begin_example
git clone ssh://aur@aur.archlinux.org/snapcast.git
cd snapcast
rm -rf src
makepkg -sri
#+end_example

You should make sure your user account is in the ~wheel~ group and you have enabled ~sudo~ for all members.

*** ~snapserver~

Enable the Snapcast server

#+begin_example
systemctl enable --now snapserver.service
#+end_example

*** ~snapclient~

Initially this was failing

#+begin_example
systemctl start snapclient.service
journalctl -xeu snapclient.service
...
-- The job identifier is 4372.
Dec 12 18:27:00 alarmpi snapclient[26820]: (Snapclient) No server URL given, defaulting to 'tcp://_snapcast._tcp'
Dec 12 18:27:00 alarmpi snapclient[26820]: (Snapclient) Version 0.34.0
Dec 12 18:27:00 alarmpi snapclient[26820]: (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
Dec 12 18:27:00 alarmpi snapclient[26820]: (Avahi) (Browser) NEW: service 'Snapcast' of type '_snapcast._tcp' in domain 'local'
Dec 12 18:27:00 alarmpi snapclient[26820]: (Avahi) (Browser) CACHE_EXHAUSTED
Dec 12 18:27:00 alarmpi snapclient[26820]: (Avahi) Service 'Snapcast' of type '_snapcast._tcp' in domain 'local':
Dec 12 18:27:00 alarmpi snapclient[26820]: (Avahi)         alarmpi.local:1704 (192.168.1.28)
Dec 12 18:27:00 alarmpi snapclient[26820]: (Controller) Found server 192.168.1.28:1704
Dec 12 18:27:00 alarmpi snapclient[26820]: (Connection) Resolving host IP for: 192.168.1.28
Dec 12 18:27:00 alarmpi snapclient[26820]: (Connection) Connecting to host: 192.168.1.28:1704, port: 1704, protocol: tcp
Dec 12 18:27:00 alarmpi snapclient[26820]: (Connection) Connected to 192.168.1.28
Dec 12 18:27:00 alarmpi snapclient[26820]: (Connection) My MAC: "dc:a6:32:c4:71:b9", socket: 9
Dec 12 18:27:00 alarmpi snapclient[26820]: (Controller) ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
Dec 12 18:27:00 alarmpi snapclient[26820]: (Controller) Codec: flac, sampleformat: 48000:16:2
Dec 12 18:27:00 alarmpi snapclient[26820]: (Player) Player name: alsa, device: default, description: Default Audio Device, idx: 1, sharing mode: unspecified, parameters: <none>
Dec 12 18:27:00 alarmpi snapclient[26820]: (Player) Mixer mode: software, parameters: <none>
Dec 12 18:27:00 alarmpi snapclient[26820]: (Player) Sampleformat: 48000:16:2, stream: 48000:16:2
Dec 12 18:27:00 alarmpi snapclient[26820]: (Alsa) Using default buffer_time: 80 ms, default fragments: 4
Dec 12 18:27:00 alarmpi snapclient[26820]: (Alsa) Exception: Can't open default, error: Unknown error 524, code: -524
Dec 12 18:27:00 alarmpi snapclient[26820]: (Snapclient) Exception: Can't open default, error: Unknown error 524
Dec 12 18:27:00 alarmpi snapclient[26820]: (Snapclient) Snapclient terminated.
Dec 12 18:27:00 alarmpi systemd[1]: snapclient.service: Main process exited, code=exited, status=1/FAILURE
#+end_example

This is because by default ~/etc/default/snapclient~ has no values for the environment variables ~$SNAPCLIENT_OPTS~
which are used by the ~systemd~ unit defined in ~/etc/systemd/system/multi-user.target.wants/snapclient.service~

#+begin_example
─────┬────────────────────────────────────────────────────────────────────────────────
     │ File: systemd/system/multi-user.target.wants/snapclient.service
─────┼────────────────────────────────────────────────────────────────────────────────
   1 │ [Unit]
   2 │ Description=Snapcast client
   3 │ Documentation=man:snapclient(1)
   4 │ Wants=avahi-daemon.service
   5 │ After=network-online.target time-sync.target sound.target avahi-daemon.service
   6 │
   7 │ [Service]
   8 │ EnvironmentFile=-/etc/default/snapclient
   9 │ ExecStart=/usr/bin/snapclient --logsink=system $SNAPCLIENT_OPTS
  10 │ User=snapclient
  11 │ Group=snapclient
  12 │ Restart=on-failure
  13 │
  14 │ [Install]
  15 │ WantedBy=multi-user.target
─────┴────────────────────────────────────────────────────────────────────────────────
#+end_example

Referring to my old install and ~snapclient --help~ you cand find out what devices are available using ~snapclient -l~

#+begin_example
snapclient -l
0: null
Discard all samples (playback) or generate zero samples (capture)

1: sysdefault
Default Audio Device

2: pipewire
PipeWire Sound Server

3: sysdefault:CARD=vc4hdmi0
vc4-hdmi-0, MAI PCM i2s-hifi-0
Default Audio Device

4: hdmi:CARD=vc4hdmi0,DEV=0
vc4-hdmi-0, MAI PCM i2s-hifi-0
HDMI Audio Output

5: sysdefault:CARD=vc4hdmi1
vc4-hdmi-1, MAI PCM i2s-hifi-0
Default Audio Device

6: hdmi:CARD=vc4hdmi1,DEV=0
vc4-hdmi-1, MAI PCM i2s-hifi-0
HDMI Audio Output

7: sysdefault:CARD=IQaudIODAC
IQaudIODAC, IQaudIO DAC HiFi pcm512x-hifi-0
Default Audio Device
#+end_example

It was then a case of setting the default soundcard in the ~SNAPCLIENT_OPTS~ that are defined in
~/etc/default/snapclient~ (since these will be read when the ~systemd~ unit starts given the above configuration) and to
then enable the server and client permanently.

#+begin_example
# Start the client, used only by the init.d script
START_SNAPCLIENT=true
# Additional command line options that will be passed to snapclient
# note that user/group should be configured in the init.d script or the systemd unit file
# For a list of available options, invoke "snapclient --help"
SNAPCLIENT_OPTS="--user snapclient:audio -h 192.168.1.28 -p 1704 -s 7"
#+end_example

*** Enable services

Enable both the ~snapserver~ and ~snapclient~ service

#+begin_example
systemctl enable --now snapserver.service
systemctl status snapserver.service
 * snapserver.service - Snapcast server
     Loaded: loaded (/usr/lib/systemd/system/snapserver.service; enabled; preset: disabled)
     Active: active (running) since Fri 2025-12-12 22:32:11 UTC; 1s ago
  Invocation: 380fcec66dd74e8b93fd9f05f8d93cb5
       Docs: man:snapserver(1)
   Main PID: 1352 (snapserver)
      Tasks: 5 (limit: 4915)
        CPU: 177ms
     CGroup: /system.slice/snapserver.service
             `-1352 /usr/bin/snapserver --logging.sink=system --server.datadir=/var/lib/snapserver

Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.45
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from 38:d5:47:e0:16:1f, host: kimura, v0.31.0, ClientName: Snapclient, OS: Gentoo Linux, Arch: x86_64, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from dc:a6:32:c4:71:b9, host: alarmpi, v0.34.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv7l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.27
Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.26
Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.23
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from b8:27:eb:5b:5a:eb, host: alarmpi7, v0.20.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv6l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from b8:27:eb:51:0a:32, host: alarmpi6, v0.20.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv6l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from b8:27:eb:37:92:37, host: alarmpi3, v0.20.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv6l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Avahi) Service 'Snapcast' successfully established.
systemctl enable --now snapclient.service
 * snapserver.service - Snapcast server
     Loaded: loaded (/usr/lib/systemd/system/snapserver.service; enabled; preset: disabled)
     Active: active (running) since Fri 2025-12-12 22:32:11 UTC; 1s ago
  Invocation: 380fcec66dd74e8b93fd9f05f8d93cb5
       Docs: man:snapserver(1)
   Main PID: 1352 (snapserver)
      Tasks: 5 (limit: 4915)
        CPU: 177ms
     CGroup: /system.slice/snapserver.service
             `-1352 /usr/bin/snapserver --logging.sink=system --server.datadir=/var/lib/snapserver

Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.45
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from 38:d5:47:e0:16:1f, host: kimura, v0.31.0, ClientName: Snapclient, OS: Gentoo Linux, Arch: x86_64, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from dc:a6:32:c4:71:b9, host: alarmpi, v0.34.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv7l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.27
Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.26
Dec 12 22:32:12 alarmpi snapserver[1352]: (StreamServer) StreamServer::NewConnection: ::ffff:192.168.1.23
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from b8:27:eb:5b:5a:eb, host: alarmpi7, v0.20.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv6l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from b8:27:eb:51:0a:32, host: alarmpi6, v0.20.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv6l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Server) Hello from b8:27:eb:37:92:37, host: alarmpi3, v0.20.0, ClientName: Snapclient, OS: Arch Linux ARM, Arch: armv6l, Protocol version: 2, Auth: {"param":"","scheme":""}
Dec 12 22:32:12 alarmpi snapserver[1352]: (Avahi) Service 'Snapcast' successfully established.
#+end_example

The service now starts and I get audio from the attached amp and on all other devices around my house 🔊🎶

** [[id:48249b0d-eeba-484a-8f00-808a14169692][etckeeper]]

I have my old ~/etc/~ configuration from which I've been copying settings but I wasn't ready to

** [[id:be393585-6c62-4ce9-9fba-15e4d1c472cb][SyncThing]]

** [[id:3774439d-af75-453e-b3e9-9d578b6bec46][Nginx]]

* New things

** incron

I find [[id:48249b0d-eeba-484a-8f00-808a14169692][Git etckeeper]] very useful for keeping the ~/etc~ directory backed up, but when I manually edited files I had to
remember to add them to the commit history. Whilst reading around for this restore I found there is the [[https://wiki.archlinux.org/title/Etckeeper#Incron][~incron~]]
programme which will use ~inotify~ to monitor files and make commits when there are changes.

* Links

** Arch Linux ARM

+ [[https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-4][Raspberry Pi 4]]
+ [[https://github.com/archlinuxarm/][GitHub | Arch Linux ARM]]

** USB xhci_hcd issues

+ [[https://archlinuxarm.org/forum/viewtopic.php?t=14734][Arch Linux ARM • View topic - No USB detected on Raspberry Pi 4 with aarch64]]
