:PROPERTIES:
:ID:       9c6257dc-cbef-4291-8369-b3dc6c173cf2
:mtime:    20230528213012 20230519194008 20230330135624 20230326125853 20230310194006 20230224092946 20230105145245 20230103103313 20221231194258 20230103103312
:ctime:    20221231194258
:END:
#+TITLE: Bash
#+DATE: [2022-04-21 Thu 10:00]
#+FILETAGS: :bash:programming:linux:

Bash is the default shell on most GNU/Linux systems and its well worth learning how to use it as it is a powerful
scripting language. Day-to-day I actually use [[id:a1b78518-31e8-4fd3-a36f-d8f152832138][zsh]] to drive my command prompt as it contains a bunch of additional
functionality such as customised command prompts and a ton of built-in aliases that I find useful. But I still use Bash
scripts to accomplish small tasks.

* Bash Scripts

** Setting Flags

Scripts can store options using the following pattern.

#+begin_src sh
set -e
set -o pipefail

usage()
{
    echo "usage : flac2mp3 [ -d DIR ] [ -j JOBS ] [ -b BITRATE ]"
}

while getopts "d:j:b:?h" option
do
    case $option in
	d)
	    INPUT_DIR=${OPTARG};;
	j)
	    JOBS=${OPTARG};;
	b)
	    BITRATE=${OPTARG};;
	h|?)
            usage
            exit 0;;
    esac
done
#+end_src

** Coloured Messages

Get coloured ~echo~ from a script using the following function.


#+begin_src sh
  function print_stage() {
    echo -e " \e[33m*\e[39m \e[94m$1\e[39m"
}
#+end_src

** Asking for Input

A script can ask for input from users using the following ([[https://wiki.gentoo.org/wiki/LiveUSB#Automatic_drive-wide_installation_script][source]])

#+begin_src sh
  #!/bin/bash
  set -e
  FAVOURITE_COLOUR=${1:?Tell me your favouirite colour?}
  FAVOURITE_FOOD=%{2:?What is your favourite food?}
#+end_src

** Lint your Scripts

Lint your scripts with [[https://www.shellcheck.net/][shellcheck]] and of course you can use [[id:a29a1e50-3cf2-4d88-a71d-7c600fdf8f65][Emacs LSP]] to do so on the fly.

* Configuration

Configuration of Bash on a per-user basis is via ~\~/.bashrc~ / ~\~/.bash_profile~ / ~\~/.bash_aliases~
** Aliases
:PROPERTIES:
:ID:       c7d811f9-5e9f-43b9-9b0b-d647a399756c
:END:

*** Ignoring Aliases

Sometimes you /don't/ want an alias to be used, even if you have set it. You can access the unaliased form of a command
by encapsulating it in single quotes e.g. ~'ls'~

* Tips and Tricks

** Make a directory for every file

You can use [[http://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion][variable substitution]] to quickly make a directory for every file in a given location (from [[https://unix.stackexchange.com/a/220026/39149][here]]).

#+BEGIN_SRC bash eval:no
  cd path/to/directory
  FILE_EXT="txt"
  for x in *.txt; do
    mkdir "${x%\.txt}" && mv "$x" "${x%\.}"
  done
#+END_SRC

** Parameter Expansion

You can use [[https://stackoverflow.com/questions/19482123/extract-part-of-a-string-using-bash-cut-split/19482947#19482947][parameter expansion]] to extract components of strings.

#+begin_src bash
  TEST="user/repository"
  USER=${TEST%/*} # Retains everything BEFORE /
  REPO=${TEST#*/} # Retains everyting AFTER /
#+end_src

** Getting dates dynamically

You can get dates dynamically in output files courtesy of the ~date~ command...

#+begin_src bash
  touch new-file-$(date +%F)
  # Different formats
  $(date +%Y-%m-%d)
  $(date +%F) # equivalent to above
  $(date +$s) # seconds since epoch
  $(date +%Y-%m-%d-%H:%M:%S)
  $(date +%F-%X) # equivalent to above
#+end_src
* Command Line Tools

The power of the command line comes from pipping the output of one command to another. To which end there are a bunch of
useful command line tools for working with files.

** awk

[[id:4d64ea2c-b91a-4162-8d79-889b05b5ba80][awk]]

** find

[[id:af0aba11-91a9-4e79-89fb-1ae6ca55f3c8][find]]
** sed

[[id:16c65320-e19d-4bdc-ab55-c410860cddfa][sed]] is a ~s~tring ~ed~itor for processing text files at the command line.

** gh

[[id:9a9076c8-7698-47b9-9cd3-c8b9e06d6694][gh_cli]]

** grep

[[id:1ffb126f-a7aa-4d26-a4d1-a7bfa8085abe][grep]]

** jq

[[id:a23966d2-0e34-4ebd-8a66-5d40c2ce6a43][jq]] is the awk/sed/grep tool for working with JSON files.

** most

An alternative Pager, install it on your system and you can test it with ~PAGER=most man ls~. If you want to make this
permanent you can add the following to ~/.bashrc~ / ~/.zshrc~

#+begin_src bash
  if command -v most > /dev/null 2>&1; then
    export PAGER="most"
  fi
#+end_src

** parallel

Bash has its own tool for parallel processing courtesy of [[https://www.gnu.org/software/parallel/][parallel]]. As with many parallelisation processes you need to
define a function that performs the single task you wish to undertake and the pass it a list of parameters to process.

An example script I've written is the following which converts FLAC files to MP3 in parallel

#+INCLUDE: "~/dotfiles/bin/flac2mp3" example sh

The key points are...

1. All FLAC files within the specified directory are located using ~find~.

#+begin_src sh
FILES=$(find "${INPUT_DIR}" -type f -name "*.flac")
#+end_src

2. A function ~_convert~ is defined and exported that takes a single argument (in this case a FLAC file path) and
   converts it to MP£ using ~ffmpeg~

#+begin_src sh
_convert()
{
    echo "Converting file ${1}"
    ffmpeg -hide_banner -loglevel panic -i "${1}" -ab "${2}" -map_metadata 0 -id3v2_version 3 "${1}".mp3
}
export -f _convert
#+end_src

3. The list of files is then pipped into the ~parallel~ command that is called with the ~_convert~ function.

#+begin_src sh
echo "${FILES}" | parallel -q -j ${JOBS} _convert {} $BITRATE
#+end_src

** xarg

[[id:48c0d280-8330-4f65-a5da-098ea186c6b6][xarg]] is a wonderful and simple tool for repeating actions on lists of objects.

* Links

** ~PS1~ Customisation
+ [[https://bashrcgenerator.com/][.bashrc generator: create your .bashrc PS1 with a drag and drop interface]]
+ [[https://stackoverflow.com/questions/4133904/ps1-line-with-git-current-branch-and-colors][command prompt - PS1 line with Git current branch and colors - Stack Overflow]]

** Shell Commands
+ [[https://explainshell.com/][Explain Shell]]
