:PROPERTIES:
:ID:       13de4e0e-4c14-48c8-897e-42862be8cfc1
:mtime:    20230309065755 20230307195327 20230215121954
:ctime:    20230215121954
:END:
#+TITLE: Discourse
#+FILETAGS: :gnu:linus:foss:web:

Easiest to use Docker images. If you've followed the [[id:fab2461a-c95a-47e3-9e5d-64af083c92e0][Linux KVM]] instructions you need to install a few tools to get
going.

#+begin_src bash
  sudo su
  apt-get upgrade # Upgrade all packages
  apt autoremove # Remove old packages
  apt-get install git curl emacs
#+end_src

Now update Docker following the instructions [[https://docs.docker.com/engine/install/ubuntu/][here]].

#+begin_src bash
  sudo su
  apt-get install ca-certificates curl gnupg lsb-release
  mkdir -m 0755 -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt-get update
  # If GPG error umask may be wrong, try
  # chmod a+r /etc/apt/keyrings/docker.gpg
  # apt-get update
  apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  docker run hello-world
#+end_sr
c
Now clone the Discourse Docker repository and run the install script. This will probably inform you that Docker isn't
installed but that is ok, the script will add the Docker repository for you, then download and install Docker for you
(as described in [[https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04][this article]] but without you having to do anything).

#+begin_src
  git clone https://github.com/discourse/discourse_docker.git /var/discourse
  cd /var/discourse
  chmod 700 containers
  ./discourse-setup

# Setup is saved to a file, need to set the following correctly
#DISCOURSE_SMTP_ADDRESS: mailhost.shef.ac.uk
#DISCOURSE_SMTP_PORT: 587
#DISCOURSE_SMTP_USER_NAME: n.shephard@sheffield.ac.uk
#DISCOURSE_SMTP_PASSWORD: "pa$$word"
##DISCOURSE_SMTP_ENABLE_START_TLS: true           # (optional, default true)
#DISCOURSE_SMTP_DOMAIN: sheffield.ac.uk
#DISCOURSE_NOTIFICATION_EMAIL: n.shephard@sheffield.ac.uk
#+end_src

You are now prompted for information about where the service will be running. You need a valid ~Hostname~ and email
address for administrator, an SMTP server and ideally a [[https://letsencrypt.org/][Let's Encrypt account]] so you can run the server on
~https~. **NB** If things go wrong remove the ~/var/discourse/containers/app.yaml~ file and start again.disc

* Questions/Problems

+ Need a valid domain (~discourse.curbar.shef.ac.uk~?).
+ Need to have ports ~80~/~443~ open (ideally the later), need to configure firewall to do so.
+ Need an SMTP server on the host (or elsewhere?) to handle sending emails, possibly [[https://marlam.de/msmtp/][msmtp]]?



* Links

+ [[https://www.discourse.org/][Discourse]]
+ [[https://github.com/discourse/discourse/blob/main/docs/INSTALL.md][discourse/INSTALL.md · GitHub]]
+ [[https://meta.discourse.org/t/setup-discourseconnect-official-single-sign-on-for-discourse-sso/13045][DiscourseConnect]] - offers single sign-on.
