:PROPERTIES:
:ID:       31304184-2fad-4cc5-824b-3ab4b9d2e126
:mtime:    20240224205650 20230418113544 20230214231111 20230103103309 20221212181558
:ctime:    20221212181558
:END:
#+TITLE: Dotfiles
#+DATE: [2022-04-18 Mon 21:13]
#+FILETAGS: :dotfiles:unix:config

When you spend time working on UNIX like operating systems like GNU/Linux (and including OSX) you end up with a lot of
configuration files that are customised to your preferences and settings. Keeping these in order and backed up is a
sensible approach to avoid a lot of pain should they be lost. It also has the advantage that when you get a new computer
or access to a new system it is easy to deploy your customised settings in the new environment.

This is where the concept of "dotfiles" comes in.

* Setting up a repository

The first step is to create a directory where all your "dotfiles" will be kept and version controlled. Its a pain to
place your ~${HOME}~ directory under version control because you will likely have innumerable other directories that are
git repositories and whilst this can be handled via [[https://git-scm.com/book/en/v2/Git-Tools-Submodules][Submodules]] its a bit of a faff. Instead its advisable to keep things
simple and have a ~\\~/dotfiles~ repository that you keep under [[id:3c905838-8de4-4bb6-9171-98c1332456be][Git]] version control.

#+BEGIN_SRC bash eval: no
  mkdir ~/dotfiles
  cd ~/dotfiles
  git init
#+END_SRC

Make a repository for yo
* Automating deployment
#+TODO: Complete this section.

* Links

+ [[https://dotfiles.github.io/][GitHub does dotfiles - dotfiles.github.io]]
+ [[https://www.atlassian.com/git/tutorials/dotfiles][How to Store Dotfiles - A Bare Git Repository | Atlassian Git Tutorial]]
+ [[https://wiki.archlinux.org/title/Dotfiles][Dotfiles - ArchWiki]]

** Tools

+ [[https://github.com/TheRealLorenz/dotlink][TheRealLorenz/dotlink: No non-sense dotfiles linker]]

** Frameworks

+ [[https://dotfiles.io/][Dotfiles - Simply designed to fit your shell life (UK)]]
+ [[https://www.chezmoi.io/][chezmoi - chezmoi]]
+ [[https://www.atlassian.com/git/tutorials/dotfiles][How to Store Dotfiles - A Bare Git Repository | Atlassian Git Tutorial]]
  + [[https://www.ackama.com/what-we-think/the-best-way-to-store-your-dotfiles-a-bare-git-repository-explained/][The best way to store your dotfiles: A bare Git repository **EXPLAINED** - Ackama]]
