:PROPERTIES:
:ID:       b9961a9e-e833-4160-aa8f-1c69b9cbb397
:mtime:    20250623181634 20231222084356 20230228201359 20230225220747 20230114083258 20230103103312 20221228105320
:ctime:    20221228105320
:END:
#+TITLE: Emacs TRAMP
#+DATE: [2022-12-21 Wed 09:10]
#+FILETAGS: emacs:tramps:editing

[[https://www.gnu.org/software/tramp/][TRAMP]] is a protocol for editing files either as another user on your own files system or on a remote file system over
[[id:b39ebc4e-3351-45e3-80b8-9780c76dbbb6][SSH]] (providing you have permission to access the system!).

* Configuration

#+INCLUDE: "~/.config/emacs/settings/tramp-settings.el" example emacs-lisp

* General Syntax

The general syntax for opening a file is.

#+begin_src emacs_lisp
  C-x C-f /[method/user]::[@remotehost]]::/filename
#+end_src

* Editing as root

You can open a file on the same system as ~root~ using.

#+begin_src emacs_lisp
C-x C-f /su::/etc/resolv.conf
C-x C-f /sudo::/etc/resolv.conf
#+end_src

You may find you'll be asked for your GPG key if you have that configured and then the ~root~ password or user password
depending on whether you are using using ~su~ or ~sudo~. You will be prompted whether to save to
~local-temporary-directory~ which by default is the value stored in ~temporary-file-directory~ and defaults to ~/tmp~
unless configured otherwise.

* SSH

To open files over SSH you should have access (obviously!) and ideally have setup SSH keys with keychain to ease the
process.

#+begin_src emacs_lisp
  C-x C-f /ssh:user@remote:~/path/to/file
#+end_src

** Shell Prompts

One of the issues encountered was that the [[id:a1b78518-31e8-4fd3-a36f-d8f152832138][ZSH]] prompt that I use messes up with the ~ssh~ connection. To [[https://emacs.stackexchange.com/a/48089][disable this]]
you should add the following to your ~\~/.zshrc~` to ensure many of the ZSH features are disabled when logging in.

#+begin_src sh
if [[ $TERM == "dumb" ]]; then
│   unsetopt zle
│   unsetopt prompt_cr
│   unsetopt promppt_subst
│   unfunction precmd
│   unfunction preexec
│   export PS1="$ "
│   return
fi
#+end_sh

This should be on the remote host so that the [[id:a1b78518-31e8-4fd3-a36f-d8f152832138][ZSH]] shell does not get initialised with all the bells and whistles that
are otherwise enabled which prevents Emacs TRAMP from opening the file. If you have ~\~/.zshrc~ setup as a symbolic link
to your ~dotfiles~ repository that is under version control then you only need to do this once and synchronise each
repository so the changes propagate and you can then use TRAMP to open files across machines regardless of which you
are actually sat at.

The [[https://www.emacswiki.org/emacs/TrampMode#h5o-9=0][Emacs Wiki : TrampMode]] page also suggests you can set the
variable ~tramp-terminal-type~ to ~tramp~ and use that in the above snippet too.

* Links

+ [[https://www.gnu.org/software/tramp/][GNU TRAMP]]
+ [[https://www.emacswiki.org/emacs/TrampMode][EmacsWiki : Tramp Mode]]

** Blogs

+ [[https://coredumped.dev/2025/06/18/making-tramp-go-brrrr./][Making TRAMP go Brrrr…. • Core Dumped]]
