:PROPERTIES:
:ID:       a29a1e50-3cf2-4d88-a71d-7c600fdf8f65
:mtime:    20250120145912 20241216144645 20240304065906 20230114084624
:ctime:    20230114084624
:END:
#+TITLE: Emacs LSP
#+FILETAGS: :emacs:lsp:programming:

I use Emacs as my Integrated Development Environment (IDE) and in addition to [[id:3070e6ed-1788-44ff-8498-8af6c84f588f][Tree-Sitter]] have configured it to use [[https://emacs-lsp.github.io/lsp-mode/][LSP
Mode - Language Server Protocol support for Emacs]]  as I started using it prior to [[https://joaotavora.github.io/eglot/][Eglot]] (another LSP mode for Emacs)
being incorporated into Emacs (>=29).

* Installation

Installation is straight-forward but for optimal benefit requires the use of a number of other packages. Since I use
~use-package~ the [[https://emacs-lsp.github.io/lsp-mode/page/installation/#use-package][installation instructions]] provided a good starting point, note that they include integration with
~which-key~. The additional packages I use are...

+ [[https://github.com/emacs-lsp/lsp-ui][lsp-ui]] - provides high level User Interface modules such as flycheck and code neses.
+ [[https://github.com/emacs-lsp/lsp-treemacs][lsp-treemacs]]
+ company
+ [[https://github.com/emacs-lsp/dap-mode][dap-mode]]


** Python

There are multiple options for a Python Language Server.

*** Jedi
I've used Jedi prior to LSP becoming widely available in Emacs so wanted to stick with this. There are two components to
this [[https://github.com/fredcamps/lsp-jedi][~lsp-jedi~]] which acts as a go-between from Emacs ~lsp-mode~ and the language server itself
[[https://github.com/pappasam/jedi-language-server][~jedi-language-server~]]. This seems to work perfectly on my work laptop but not on my desktop and I can not for the life
of me figure out why. I've kept the old configuration just in case I one day sort it out.

*** pylsp



*** pyright

[[https://emacs-lsp.github.io/lsp-pyright/][~lsp-pyright~]] is another good  option.
** R

** Bash

** Emacs LISP

Strangely there is no language server dedicated to Emacs LISP which is mildly frustrating but internal support for Emacs
LISP is, unsurprisingly, very good in Emacs.

** Markdown

Install [[https://github.com/remarkjs/remark-language-server][remark-language-server]] ...

#+begin_src bash
  npm install -g remark-language-server
  npm list -g
  which remark-language-server
#+end_src

Make sure the install path is in the ~exec-path~ in Emacs,

#+begin_src elisp
  (setq exec-path (append '("~/bin"
                          "~/.local/bin"
                          "~/.cargo/bin/"
                          "~/.node/bin/"
                          )
                        exec-path))
#+end_src

The [[https://github.com/jrblevin/markdown-mode][markdown-mode]] package can be used, you can set a hook here or in the

#+begin_src elisp
  (use-package markdown-mode
  :ensure t
  :mode ("\\.md\\'" . gfm-mode)
  :hook (markdown-mode . auto-fill-mode)
  :init (setq markdown-command "pandoc")
  :config
  :bind (:map markdown-mode-map
          ("C-c C-m" . markdown-do)))

#+end_src

** Ltex

[[https://valentjn.github.io/ltex/][LTeX]] is a bit of a magic bullet, it provides "_grammar/spell checking using language tool  with support for LaTeX,
Markdown and Others_". This includes [[id:169b9c5f-df34-46ab-b64f-8ee98946ee69][Orgmode]] which was a real short coming for sometime since I write these notes in
[[id:169b9c5f-df34-46ab-b64f-8ee98946ee69][Orgmode]]!

*** Installing

Under Emacs you can use the [[https://github.com/emacs-languagetool/lsp-ltex][emacs-languagetool/lsp-ltex]] package but yo have to have the language server [[https://valentjn.github.io/ltex/ltex-ls/installation.html][ltex-ls]]
installed. Under Gentoo this is available from the [[https://github.com/msva/mva-overlay/][mva overlay]].

**** Gentoo

#+begin_src bash
eselect repository mva
emerge -av ltex-ls
#+end_src

**** Arch

For Arch install from [[https://aur.archlinux.org/packages/ltex-ls-bin][AUR (en) - ltex-ls-bin]]


#+begin_src bash
git clone https://aur.archlinux.org/ltex-ls-bin.git
cd ltex-ls-bin
makepkg -sri
#+end_src


* Links

+ [[https://andreyor.st/posts/2023-09-09-migrating-from-lsp-mode-to-eglot/][Migrating from LSP-Mode to Eglot · Andrey Listopadov]]
+ [[https://www.mattduck.com/lsp-python-getting-started.html][Getting started with lsp-mode for Python]]
+ [[https://blog.serghei.pl/posts/emacs-python-ide/][Advanced Python Development Workflow in Emacs | Serghei's Blog]]
