:PROPERTIES:
:ID:       4451966f-b810-4a9d-905b-e2b682578c62
:mtime:    20231130102352 20230910184222 20230906125824 20230103103310 20221224191223
:ctime:    20221224191223
:END:
#+TITLE: Emacs Buffers
#+DATE: <2022-12-22 Thu 09:06>
#+FILETAGS: emacs:buffers:productivity

Buffers are the windows through which you view files and processes in Emacs.

* Switching Buffers

~C-x b~ will switch buffers, a default is offered but if this isn't right you can either start typing the name of the
buffer you want to switch to or hit ~<Tab>~ to get a list of those available. You can then use the Up and Down arrow
keys to navigate through the available buffers. Hit ~<Return>~ when done to switch.

* Killing Buffers

A simple way to kill a single buffer is ~C-x k~ you will be asked which buffer you want to kill, by default it will be
the current buffer that you are visiting, but if you hit ~<Tab>~ you'll get a list.

** Multiple Buffers

You can kill multiple buffers using Helm (from [[https://www.emacswiki.org/emacs/KillingBuffers#h5o-13][here]]). Start ~M-x helm-mini~ and start typing a pattern against which to
match buffers, e.g. ~magit~ a buffer(!) then appears with the buffers that exist which match, select each you want to
kill with ~C-SPACE~ and kill the selected ones with ~M-D~.

*** Kill all Dired buffers

[[id:e2a2ead1-4348-4cc6-9ef1-dd96777aaec8][Dired]] by default opens each directory in a new buffer, as a consequence you can quickly rack up a lot of Dired buffers
you can kill them all quickly with ~IbufferMode~ using ~C-x C-b * / D yes Ret~ (from [[https://www.emacswiki.org/emacs/KillingBuffers#h5o-6][here]]).

* Managing Buffers

** What modes are enabled?

You can find out what modes are enabled using ~M-x describe-mode~ to see a list of the Major and minor modes enabled for
the given buffer.

** Equalise all buffer windows

You can make all buffers equal in size using ~balance-windows~ which is bound to ~C-x +~

** Winner mode

~winner-mode~ is a simple way of managing buffers/windows and switching between having many buffers to a single and back
again (through a history of buffer layouts).

* Writing in Buffers

You'll spend a lot of time writing in buffers, its worth knowing a few tricks.

** Line wrapping

You can wrap lines of text to the desired/configured line length using ~fill-paragraph~ or ~fill-region~ its bound to
~M-q~ so just highlight the region and it will be reformatted to the configured line-length. If you need to change this
on the fly you can do so with ~C-x f~.

* Code Folding

The useful ~hs-minor-mode~ can be used to enable cold-folding where the code underneath function definitions is hidden
from view. To enable this globally for all programming modes (and others) you can add the following to your
configuration.

#+begin_src elisp
  (use-package emacs
    ...
    :hook
    ((prog-mode
       latex-mode) .hs-minor-mode)
    ...
    )
#+end_src

Once enabled you can use ~C-c @~ and with ~which-key~ enabled you get a buffer showing what options you have to show and
hide code in different amounts. Very neat.

| Key Chord   | Action        |
|-------------+---------------|
| ~C-c @ C-t~ | Hide All      |
| ~C-c @ C-a~ | Show All      |
| ~C-c @ C-c~ | Toggle hiding |
| ~C-c @ C-h~ | Hide block    |
| ~C-c @ C-h~ | Show block    |
