:PROPERTIES:
:ID:       e2a2ead1-4348-4cc6-9ef1-dd96777aaec8
:mtime:    20250101104005 20240830092356 20231005070522 20231003113848 20230623175141 20230130170006 20230103103313 20221224191223
:ctime:    20221224191223
:END:
#+TITLE: Emacs Dired
#+DATE: <2022-12-22 Thu 09:14>
#+FILETAGS: emacs:dired:files:browsing

* Working with Files

** Filename Editing

You can edit filenames using ~C-x C-q~ and edit the filename in place (e.g. ~M-$~ to spellcheck), when done you confirm
the filename change with ~C-c C-c~ ([[https://mbork.pl/2023-01-30_The_benefits_of_everything_being_a_buffer][source]]).

This is particularly useful if you've a bunch of files with a common prefix that you want to remove (e.g. downloads from
[[https://bandcamp.com][Bandcamp]] that all have the artist and album prefix). Fire up the buffer use ~C-x SPACE~ to start rectangle select and
select the prefixes you want to remove.

** Compression

You can (un)compress files or directory in Dired by hitting `Z`.

* Casual Dired

The [[https://github.com/kickingvegas/casual-dired][Casual Dired]] package is "/An opinionated Transient user interface for Emacs file manager Dired/" and is a brilliant
idea. Its part of the Casual package system.

* [[https://github.com/Fuco1/dired-hacks][Dired Hacks]]

A collection of useful dired additions split into multiple packages.
