:PROPERTIES:
:ID:       938af6af-7a0e-46d1-ae76-6157e948151b
:mtime:    20251110225146 20251012200712 20250902155530 20250622203020 20250304224048 20241215223039 20241023184234 20240706220449 20240115230041 20231222084358 20230114083319 20230103103311 20221229094021
:ctime:    20221229094021
:END:
#+TITLE: Emacs Configuration
#+DATE: <2022-12-28 Wed 08:44>
#+FILETAGS: emacs:configuration:elisp

Emacs configuration starts with an "init" file, this can be located in one of several locations (~\~/emacs.d/init.el~)
but I use ~~/.config/emacs/init.el~ as my main configuration file and then load additional, package specific
configurations from ~~/.config/emacs/settings/<pkgnmae>-settings.el~ as I find large files unwieldly to navigate.

* Main Configuration

#+INCLUDE: "~/.config/emacs/init.el" example emacs-lisp

** Byte Compilation

Byte compilations will increase the speed of Emacs as text files are converted to binaries which load and are
interpreted quicker. Source files are text and ~.el~ whilst byte-compiled files are ~.elc~ and are machine read-able.

There are two potions to help with this Jona Bernoulli's (aka [[https://github.com/tarsius][@tarsius]]) [[https://github.com/emacscollective/auto-compile][auto-compile]] which for every ~.elc~ which only
updates ~.elc~ when they are outdated, it /won't/ compile new ~.el~ files for which there is no corresponding ~.elc~
(see [[https://github.com/jamescherti/compile-angel.el?tab=readme-ov-file#what-is-the-difference-between-auto-compile-and-compile-angel][note]]). The other option is to use the [[https://github.com/jamescherti/compile-angel.el][compile-angel.el]] which always compiles ~.el~ to ~.elc~ and makes sure they
are kept up-to-date.

** System Configuration

Configuration options specific to the OS or machine can be made for ideas and guidance see...

+ [[https://olddeuteronomy.github.io/post/multiplatform-emacs-config/][Making a Multiplatform Emacs Configuration]]
+ [[https://irreal.org/blog/?p=13072][Running Emacs On Multiple Platforms | Irreal]]

** use-package

I typically use [[https://github.com/jwiegley/use-package][use-package]] to install and load packages. Its now part of core Emacs so there is no need to explicitly
install it. Configuration is simplified but there are still better ways of doing things as covered in [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using use-package
the right way - (think)]], its not without problems though and it is possible to migrate from ~use-package~ to the default
Emacs method as described in [[https://eugene-andrienko.com/it/2025/10/10/emacs-ditch-use-package.html][Why and how I ditched use-package?]].

* Gentoo

Under [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] it is possible to install packages at the system level using [[https://github.com/jauhien/gs-elpa][gs-elpa]] which compiles and installs Lisp
packages from ELPA repositories. It works with Layman.

#+begin_src bash
  emerge -av gs-elpa
  layman -L
  layman -a melpa
  layman -a gnu-elpa
  emerge -va
#+end_src

* Literate Configuration

I opted to make a [[file:~/.config/emacs/config/config.org::\[\[https://github.com/LionyxML/magit-stats\]\]\[magit-stats\]\]][Literate Configuration]] ([[https://wiki.nshephard.dev/~arch/emacs/config.html][website]]) for my configuration using [[id:6e75f9df-df3d-4402-b5ad-ed98d0834e08][Org Babel]]. I've a few things to sort out
but am pretty happy with it as a starting point and am going to use it as a basis for starting to learn and improve my
[[id:708f5d99-6040-4306-a323-306d39ce45c3][Emacs Lisp]] skills/knowledge.

* Package Specifics

Details of each package specific configuration are found on their own pages.

+ [[id:0f5d8919-1769-492d-b0e0-e9e8c738190e][Centaurtabs]]
+ [[id:efe4e098-d7e6-42cd-90bd-234a25806c3a][Eglot]]
+ [[id:35c72a31-2beb-4dcf-98c9-0254b05bcb86][EIN]]
+ [[id:c5b2b8ae-46fc-4d91-8227-7116c7885de4][Elfeed]]
+ [[id:a2ff20a8-46cd-4123-9931-722925e0af19][ESS]]
+ [[id:d0cd450a-2c1e-44da-b185-a9b27d0f0012][Flycheck]]
+ [[id:220d7ba9-d30e-4149-a25b-03796e098b0d][Magit]]
+ [[id:100c80ce-2299-4d0f-a6a2-03fed94a4cc7][Markdown]]
+ [[id:42dd7a3e-d6bf-4e22-b564-f159fcbeb460][Org GTD]]
+ [[id:301c717a-c9f6-4490-9620-491762db4343][OSM]]
+ [[id:b9961a9e-e833-4160-aa8f-1c69b9cbb397][Tramp]]
+ [[id:d6626ec2-1e95-4d42-b06e-ae45268f2b58][Transient]]
+ [[id:3070e6ed-1788-44ff-8498-8af6c84f588f][Tree-Sitter]]
+ [[id:4668a662-27ab-4015-aaa0-6e356b6bc165][Vterm]]

* Links

+ [[https://codeberg.org/jcastp/emacs.d/][Codeberg | jcastp/emacs.d]] - a nice literate configuration
+ [[https://leanpub.com/lit-config/read][Read Literate Configuration | Leanpub]] (via [[https://mastodon.social/@masukomi@connectified.com/112741432091944271][this thread]])
+ [[https://github.com/LionyxML/emacs-kick][LionyxML/emacs-kick: A feature rich Emacs (kickstarter) config for (neo)vi(m)mers]]
+ [[https://sophiebos.io/posts/first-emacs-config/][Building Your First Emacs Config | Sophie Bosio]]
+ [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Using use-package the right way - (think)]]
+ [[https://eugene-andrienko.com/it/2025/10/10/emacs-ditch-use-package.html][Why and how I ditched use-package?]]
