:PROPERTIES:
:ID:       ac85ca6b-4b6e-4e8d-82f8-2f85c5062de6
:mtime:    20230912205339
:ctime:    20230912205339
:END:
#+TITLE: Emacs Password
#+FILETAGS: :emacs:pass:password:security:

[[https://www.passwordstore.org/][pass]] is the standard password manager for UNIX-like systems (i.e. [[id:0e6300c6-7025-4f45-820d-4d9da82b41a6][Linux]]). It has a number of Emacs packages for working
with passwords.

* ~password-store~

[[https://git.zx2c4.com/password-store/tree/contrib/emacs][password-store]] is a package for working with ~pass~. For convenience I bind ~F1~ to ~password-store-copy~ and in doing
so I'm prompted for the password I want to unlock.

#+begin_src lisp
(use-package pass
	     :ensure t
	     :defer t)
(global-set-key (kbd "<f1>") 'password-store-copy)
#+end_src


* ~pass~

[[https://github.com/NicolasPetton/pass][pass: A major mode for password-store]] depends on ~password-store~ and ~password-store-otp~ but this is the package that
allows interaction with your password store.  Its simple, and if I want to do more I can use ~M-x pass~ to start the pass
major mode which uses [[id:d6626ec2-1e95-4d42-b06e-ae45268f2b58][Emacs Transient]] to perform actions on the existing library.

#+begin_src lisp
(use-package pass
	     :ensure t
	     :defer t)
(global-set-key (kbd "<f1>") 'password-store-copy)
#+end_src

* ~password-store-otp~

Allows interaction with the [[https://github.com/tadfisher/pass-otp/][pass-otp extension]] for managing one-time-password (OTP) token.

* Links

** HowTos

+ [[https://yejun.dev/posts/simplify-totp-management-in-emacs/][Simplify TOTP management in Emacs - Yejun Su]]
