:PROPERTIES:
:ID:       0b7373ce-724c-40f0-8432-f8dbbbad95fc
:mtime:    20260922143426 20260918201423 20260918164616 20260904205529
:ctime:    20260904205529
:END:
#+TITLE: Ergonomic Keyboard
#+DATE: [2026-09-04 Fri]
#+FILETAGS: :keyboard:ergonomic:

I've used a M$ Ergonomic 4000 for almost 20 years and had my second version die on me recently. I was saddened to find
that they are no longer made so resorted to searching eBay for versions. Second hand ones were going for north of £45
which I wasn't willing to pay. However, a few places listed brand new "QWERTY/Arabic" versions for a very reasonable
~£14 so I bit the bullet and bought one.

* Keymap

The keyboard worked on plugging it in...sorta. Not all the keys from my muscle memory matched those I was
expecting. Turns out these aren't UK-QWERTY, rather they are US-QWERTY. Simple enough to modify the keyboard layout in
[[id:63fa9747-24ef-40e2-a2ed-d6bd4133374f][Xfce4]] to use the US layout and output matched what was printed on the keys (rather than my expectation). This was all
good until I wanted to type ~£~ (UK pound symbol) which doesn't have a natural mapping on the standard US keyboard.

I found a useful [[https://superuser.com/questions/293119/how-to-type-pound-sign%C2%A3-using-us-keyboard-in-windows-linux-and-mac][thread]] on superuser.com and found that setting the layout to ~English (US)~ and variant to ~English
(US, intl., with dead keys)~ meant I could use ~AltGr + Shift + 4~ to get a ~£~ but as mentioned in the comments to this
particular [[https://superuser.com/a/293123/250590][solution]] it is at the expense of messing up typing ~~~/~´~/~¨~ which now required double typing and the
symbols look off to me too, e.g. ~´~ instead of ~'~ and ~¨~ instead of ~"~. The later are obtained by typing the
quotation keys and then hitting space which is a /big/ hindrance to my typing.

I would /like/ to use a UK-QWERTY layout as that is what my muscle memory is currently strong enough but the US-QWERTY
layout is not only missing common keys but the double quote and @ symbol are transposed. I don't need to type ~£~ that
frequently but often enough for it to be a nuisance not having it readily available and using the dead keys approach is
also annoying.

Might have found the solution to this, the *Layout* is ~English (US)~ but setting the *Variant* to ~English (intl. with
AltGr dead keys)~ seems to give me a nice balance, no need to use ~Alt-Gr + '~/~Alt-Gr + '~ or hit space after taping
each.

** Alt+Gr

The ~Alt-Gr~ (right of the space bar) is pretty handy here you can use ~Alt-Gr + '~ to avoid having to tap the space
bar afterwards. This is somewhat of an improvement but it will still going to take some time to get used to it.

* Links

+ [[https://superuser.com/questions/293119/how-to-type-pound-sign%C2%A3-using-us-keyboard-in-windows-linux-and-mac][How to type pound sign using us-keyboard]]
+ [[https://apple.stackexchange.com/questions/426379/qwerty-us-qwerty-international-os-layout][QWERTY US International layout]]
+ [[https://en.wikipedia.org/wiki/Dead_key][Dead key - Wikipedia]]
+ [[https://technicskeyboard.com/how-to-do-quotation-marks-on-international-keyboard/][How To Do Quotation Marks On International Keyboard - Technicskeyboard.com]]
