:PROPERTIES:
:ID:       d9c960c2-71b6-45e6-b388-dcd07b9da3e1
:mtime:    20251225190243 20251225170807 20250308205721 20250308073752 20250228080846 20250226203815 20250226192133 20250225224811 20250225210838 20250224202433 20250224081624 20250223214102 20250223190038 20240812084832 20240602222241 20240601082743 20230730204045 20230730112159
:ctime:    20230730112159
:END:
#+TITLE: FitTrackee
#+FILETAGS: :python:postgresql:gpx:tracking:

I use [[https://github.com/OpenTracksApp/OpenTracks][OpenTracks]] to track my running, cycling and hiking and have for a long time meant to write a WebUI for summarising
things. Fortunately I stumbled across [[https://samr1.github.io/FitTrackee/en/][FitTrackee]] which is a [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] package written in Flask that uses a database to
store all the data and summarise it in a nice dashboard.


* Installation

Notes from installation under [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]]. I opted to install from [[https://pypi.org][PyPI]] you should follow the installation instructions
at [[https://samr1.github.io/FitTrackee/en/installation.html#from-pypi][here]] if you are intending on doing the same (there are also instructions for installing from [[https://samr1.github.io/FitTrackee/en/installation.html#from-sources][GitHub sources]]).

** Install Dependencies

Requires PostgreSQL and since its written in [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] we install the ~mkvirtualenv~ package to easily manage virtual
environments. As ~root~

#+begin_src bash
pacman -Syu python-mkvirtualenv postgresql
#+end_src

** Create user

Create a dedicated user account (~fittrackee~) adding to the ~postgres~ group to run the service. As ~root~ create the
user and set the password.

#+begin_src bash
useradd -m -G users,postgres -s /bin/bash fittrackee
passwd fittrackee
#+end_src

** Create Database User

As ~root~ you need to create a database to go with the service. As the ~postgres~ user create an account in PostgreSQL
    for ~fittrackee~

#+begin_src bash
sudo su postgres
[postgres@host ~/]$ createuser --interactive
Enter name of role to add: fittrackee
Shall the new role be a superuser? (y/n) n
Shall the new role be allowed to create databases? (y/n) y
Shall the new role be allowed to create more new roles? (y/n) n
#+end_src

You're not prompted to set the password, we also need to create a schema and authorise the ~fittrackee~ user.

#+begin_src sql
psql
postgres=# ALTER USER fittrackee WITH PASSWORD '<password>';
postgres=# CREATE SCHEMA fittrackee AUTHORIZATION fittrackee;
postgres=# CREATE DATABASE fittrackee OWNER fittrackee;
    #+end_src


** Switch to ~fitttrackee~ install FitTrackee

You need to add the following to the ~/home/fittrackee/.bashrc~ in order to use ~virtualenvwrapper~ commands


#+begin_src bash
sudo su fittrackee
cd
echo "export WORKON_HOME=~/.virtualenvs\nsource /usr/bin/virtualenvwrapper.sh" >> ~.bashrc
mkvirtualenv fittrackee
pip install fittrackee
#+end_src


** Set up your ~\~/.env~

There are a number of [[https://samr1.github.io/FitTrackee/en/installation.html#environment-variables][environment variables]] that ~fittrackee~ requires, set this up by copying the [[https://github.com/SamR1/FitTrackee/blob/master/.env.example#L4][.env.example]] file
into the ~/home/fittrackee/.env~ file. You **must** source the ~\~/.env~ file otherwise the database will not be
created. You will **have** to source this file each time you make changes for them to take effect.

#+begin_src bash
sudo su fittrackee
nano ~/.env
# Paste the contents in the save and exit ^+O then ^+X
source ~/.env
#+end_src

You may wish to tweak some settings

** Create Database

You should have created a database user ~fittrackee~ above and allowed it to create databases, now as the ~fittrackee~
system user you need to create the database.

#+begin_src bash
sudo su fittrackee
ftcli db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 9741fc7834da, create User table
INFO  [alembic.runtime.migration] Running upgrade 9741fc7834da -> b7cfe0c17708, create Activity & Sport tables
INFO  [alembic.runtime.migration] Running upgrade b7cfe0c17708 -> caf0e0dc621a, create Record table
INFO  [alembic.runtime.migration] Running upgrade caf0e0dc621a -> dd73d23a7a3d, create Activities Segments table
INFO  [alembic.runtime.migration] Running upgrade dd73d23a7a3d -> 92adde6ac0d0, add 'bounds' column to 'Activity' table
INFO  [alembic.runtime.migration] Running upgrade 92adde6ac0d0 -> 5a42db64e872, add static map url to 'Activity' table
INFO  [alembic.runtime.migration] Running upgrade 5a42db64e872 -> 9f8c9c37da44, add static map id to 'Activity' table
INFO  [alembic.runtime.migration] Running upgrade 9f8c9c37da44 -> e82e5e9447de, add 'timezone' to 'User' table
INFO  [alembic.runtime.migration] Running upgrade e82e5e9447de -> 71093ac9ca44, add weather infos in 'Activity' table
INFO  [alembic.runtime.migration] Running upgrade 71093ac9ca44 -> 096dd0b43beb, Add 'notes' column to 'Activity' table
INFO  [alembic.runtime.migration] Running upgrade 096dd0b43beb -> 27425324c9e3, add 'weekm' in 'User' table
INFO  [alembic.runtime.migration] Running upgrade 27425324c9e3 -> f69f1e413bde, add 'language' to 'User' table
INFO  [alembic.runtime.migration] Running upgrade f69f1e413bde -> 1345afe3b11d, replace 'is_default' with 'is_active' in 'Sports' table
INFO  [alembic.runtime.migration] Running upgrade 1345afe3b11d -> 8a0aad4c838c, add application config in database
INFO  [alembic.runtime.migration] Running upgrade 8a0aad4c838c -> 3243cd25eca7, add uuid to activities
INFO  [alembic.runtime.migration] Running upgrade 3243cd25eca7 -> 4e8597c50064, rename 'activity' with 'workout'
INFO  [alembic.runtime.migration] Running upgrade 4e8597c50064 -> cee0830497f8, Add new sports
INFO  [alembic.runtime.migration] Running upgrade cee0830497f8 -> 9842464bb885, add stopped speed threshold to sports
INFO  [alembic.runtime.migration] Running upgrade 9842464bb885 -> 080acc8ee956, add sport preferences
INFO  [alembic.runtime.migration] Running upgrade 080acc8ee956 -> 07188ca7620a, add imperial units preferences
INFO  [alembic.runtime.migration] Running upgrade 07188ca7620a -> ed409fd9db9d, add snowshoes sport
INFO  [alembic.runtime.migration] Running upgrade ed409fd9db9d -> e30007d681cb, add missing indexes on Workout table
INFO  [alembic.runtime.migration] Running upgrade e30007d681cb -> 5e3a3a31c432, update User and AppConfig tables
INFO  [alembic.runtime.migration] Running upgrade 5e3a3a31c432 -> cd0e6cf83207, add ascent record
INFO  [alembic.runtime.migration] Running upgrade cd0e6cf83207 -> 84d840ce853b, add OAuth 2.0 and blacklisted tokens
INFO  [alembic.runtime.migration] Running upgrade 84d840ce853b -> 5b936821326d, add virtual cycling as sport type
INFO  [alembic.runtime.migration] Running upgrade 5b936821326d -> bf13b8f5589d, Add date_format for date display to user preferences in DB
INFO  [alembic.runtime.migration] Running upgrade bf13b8f5589d -> a8cc0adfe1d3, add Mountaineering
INFO  [alembic.runtime.migration] Running upgrade a8cc0adfe1d3 -> 0f375c44e659, update elevation precision
INFO  [alembic.runtime.migration] Running upgrade 0f375c44e659 -> 374a670efe23, add privacy policy
INFO  [alembic.runtime.migration] Running upgrade 374a670efe23 -> db58d195c5bf, add user preference to start elevation plots at zero
INFO  [alembic.runtime.migration] Running upgrade db58d195c5bf -> eff1c16c43eb, Add user preference for gpx speed calculation
INFO  [alembic.runtime.migration] Running upgrade eff1c16c43eb -> d22670a89a54, add paragliding sport
INFO  [alembic.runtime.migration] Running upgrade d22670a89a54 -> 24eb097614e4, add open water swimming

#+end_src

** systemd

Systemd service files are also provided in the [[https://samr1.github.io/FitTrackee/en/installation.html#deployment][Deployment]] section.

Add these to ~/etc/systemd/system/fittrackee.service~ and  ~/etc/systemd/system/fittrackee_workers.service~.

There are a few things to change across these files

+ ~User=<USER>~ - needs replacing in a few places the global configuration and also on the ~ExecStart~ line to reflect
  the account things are running under.
+ ~<FITTRACKEE DIRECTORY>~ - a directory under the ~User~ account where data is stored. Create this directory if
  required.
+ You may need to tweak the ~ExecStart~ path to reflect the location of ~gunicorn~ under the virtual environment you
  created.
+ Path to your virtual environment should reflect where you have installed things (use ~which gunicorn~ to find out the
  path, but note it also needs updating for ~which flask~).
+ ~<NUMBER OF PROCESSES>~ needs setting, to start with I went with ~1~

If you use [[id:48249b0d-eeba-484a-8f00-808a14169692][etckeeper]] make sure to add them to the [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] repository. You will need to enable the units.

#+begin_src bash
cd /etc
git add systemd/system/fittrackee*
git commit -m "Adding fitrtrackee systemd service units"
git push
systemd enable --now fittrackee.service
systemd enable --now fittrackee_workers.service
#+end_src

** Nginx Configuration

A useful configuration is provided in the [[https://samr1.github.io/FitTrackee/en/installation.html#deployment][Deployment]] section. You'll need a URL and a free one can be obtained from
[[https://noip.com/][noip.com]] (although you have to update it every 30-days). If you've modified the ~$PORT~ then make sure to tweak this
under the ~location~ section of the server configuration.  Again add the file to your ~etckeeper~ repository and restart
the server.


#+begin_src
git add nginx/nginx.conf
git commit -m "Adding nginx config for fittrackee"
systemd restart nginx.service
#+end_src




 * Importing Legacy Tracks

I have a lot (>5000) tracks that I've recorded over the years and manually uploading these one by one was never going to
happen. Fortunately a recent update (insert version) allowed customising how many ~.gpx~ files could be placed in a
~.zip~ and uploaded in one go. This appealed as a way of getting all of my legacy tracks in place but required some
planning.

** Split tracks into Activities

Each of the tracks is a ~.gpx~ file, these are a form of XML and so they are text files that can be searched. As they
record the activity type it is straight-forward to use a little [[id:48c0d280-8330-4f65-a5da-098ea186c6b6][Bash xarg]]
to split them into their own directories since uploading a Zip file you specify the "Activity" in FitTrackee

#+begin_src
cd ~/path/to/gpx/tracks~
mkdir -p ../by_activity/{running,cycling,hiking}
grep -l -Z -r "hiking" . | xargs -0 -I{} cp {} ../by_activity/hiking/.
grep -l -Z -r "biking" . | xargs -0 -I{} cp {} ../by_activity/cycling/.
grep -l -Z -r "cycling" . | xargs -0 -I{} cp {} ../by_activity/cycling/.
grep -l -Z -r "running" . | xargs -0 -I{} cp {} ../by_activity/running/.
#+end_src

Each directory can now be zipped up and uploaded individually.

** Database

The database that sits behind FitTrackee already has events in it and I didn't want duplicates to deal with. There are a
couple of strategies available here from starting anew and uploading everything or adding everything and then removing
duplicates. First though, start by making a backup of your existing system/database so you don't lose anything

#+begin_src
cd
cp -r postgresql postgresql-$(date +%Y%m%d)
#+end_src

As this is an existing installation then you need to remove the database and create it again as well as remove the
existing ~uploads~ to avoid conflicts. The number in the ~uploads/workouts/~ directory relates to the user.

#+begin_src
dropdb 'fittrackee'
rm -rf uploads/workouts/1/*
#+end_src

#+begin_src
psql -U postgres
postgres=# CREATE DATABASE fittrackee OWNER fittrackee;
postgres=# CREATE SCHEMA fittrackee AUTHORIZATION fittrackee;
postgres=# CREATE DATABASE fittrackee OWNER fittrackee;
postgres=# \q
ftcli db upgrade
#+end_src

You can now restart the ~fittrackee~ application, but you will have to register anew since this is a new database. I hit
problems with this as I did the [[https://github.com/SamR1/FitTrackee/issues/568][first time]] I installed and ran
Fittrackee. To get round this I manually connected to the database, checked the ~confirmation_token~ then manually
visited ~https://fittrackee.nshephard.dev/account-confirmation?token=<confirmation_token~> and I was logged in. I then
changed the role of the user I had created to be admin with...

#+begin_src
ftcli users update <username> --set-role owner
#+end_src

...and I was good to go. I tweaked the maximum size of individual ~.gpx~ files (to 10Mb), the size of ~.zip~ files (to
100Mb) and the maximum number of workouts in an individual ~.zip~ (to 10,000).

Hit some errors about ~user_raw_gpx_speed~ which was ~FALSE~ by default

*** Miscellaneous

#+begin_src
psql -U fittrackee
-- List tables
\dt+
-- List details of a given table
\d+ usesr
-- Switch to Dark Mode
UPDATE users SET use_dark_mode = TRUE WHERE username = 'neil';
-- Give username admin role
UPDATE users SET role = 100 WHERE username = 'neil';
-- Set limits on application
UPDATE app_config SET max_users = 1 WHERE id = 1;
UPDATE app_config SET max_zip_file_size = 104857600 WHERE id = 1;    -- 100Mb zip file limits
UPDATE app_config SET max_single_file_size = 20971520 WHERE id = 1;  -- 20Mb single GPX file
UPDATE app_config SET gpx_limit_import = 10000 WHERE id = 1;         -- 10000 files per zip
UPDATE app_config SET stats_workouts_limit = 0 WHERE id = 1;         -- No limit on stats for workouts
-- Disable various sports
UPDATE sports SET is_active = FALSE WHERE id = 9;                    -- Alpine Skiing
UPDATE sports SET is_active = FALSE WHERE id = 10;                    -- Cross Country Skiing
UPDATE sports SET is_active = FALSE WHERE id = 11;                    -- Rowing
UPDATE sports SET is_active = FALSE WHERE id = 12;                    -- Snowshoes
UPDATE sports SET is_active = FALSE WHERE id = 13;                    -- Cycling (Virtual)
UPDATE sports SET is_active = FALSE WHERE id = 15;                    -- Paragliding
UPDATE sports SET is_active = FALSE WHERE id = 16;                    -- Open Water Swimming
UPDATE sports SET is_active = FALSE WHERE id = 17;                    -- Cycling (Trekking)
UPDATE sports SET is_active = FALSE WHERE id = 18;                    -- Swimrun
#+end_src

#+:CAPTION

| id | label                      | is_active | stopped_speed_threshold |
|----+----------------------------+-----------+-------------------------|
|  1 | Cycling (Sport)            | t         |                       1 |
|  2 | Cycling (Transport)        | t         |                       1 |
|  3 | Hiking                     | t         |                     0.1 |
|  4 | Mountain Biking            | t         |                       1 |
|  5 | Running                    | t         |                       1 |
|  6 | Walking                    | t         |                     0.1 |
|  7 | Mountain Biking (Electric) | t         |                       1 |
|  8 | Trail                      | t         |                     0.1 |
|  9 | Skiing (Alpine)            | t         |                       1 |
| 10 | Skiing (Cross Country)     | t         |                     0.1 |
| 11 | Rowing                     | t         |                       1 |
| 12 | Snowshoes                  | t         |                     0.1 |
| 13 | Cycling (Virtual)          | t         |                       1 |
| 14 | Mountaineering             | t         |                     0.1 |
| 15 | Paragliding                | t         |                     0.1 |
| 16 | Open Water Swimming        | t         |                     0.1 |
| 17 | Cycling (Trekking)         | t         |                       1 |
| 18 | Swimrun                    | t         |                     0.1 |


* Upgrading

** Backup database

Use [[https://www.postgresql.org/docs/current/app-pgdump.html][pg_dump]] to back up the database (most useful information on this is from the [[https://wiki.archlinux.org/title/PostgreSQL#Manual_dump_and_reload][Arch Linux Wiki | PostgreSQL - Manual
dump and reload]]). This needs to be run as user ~postgres~ and if you are creating the backup under the
~/home/fittrackee~ directory then appropriate directory permissions need modifying to allow ~postgres~ to read/write
under the account (add them to the ~fittrackee~ group in ~/etc/group~ and change permissions with ~chmod 775
/home/fittrackee~).


#+begin_example
su postgres
cd /home/fittrackee
mkdir db-$(date +%Y%m%d)
pg_dumpall -f db-20251225/backup-$(date +%Y%m%d).sql
#+end_example

This creates a backup in the ~/home/fittrackee/db-20251225/backup-20251225.sql~

** Backup Uploads

The root directory in my installation is ~/home/fittrackee~ and ~uploads~ is within this
(i.e. ~/home/fittrackee/uploads~). I compressed this into a single tarball to save a little space.

#+begin_example
su fittrackee
cd
tar cjvf /home/fittrackee/db-20251225/uploads_backup-$(date +%Y%m%d).tar.bz2 uploads
#+end_example


** ~0.9.4~ > ~1.0.4~

As I'm upgrading to a major new version I had to install [[https://postgis.net/][PostGIS]], a geo-spatial extension for [[id:498abde2-0f65-4a10-bf84-8bf6a3410d67][PostgreSQL]]. After reading
the [[https://docs.fittrackee.org/en/upgrading-to-1.0.x.html][instructions]] carefully the main thing that differs from a [[https://docs.fittrackee.org/en/installation.html#upgrade][standard upgrade]] appears to be the need to install
~postgis~ itself and add the extension to the database.

#+begin_example
pacman -Syu postgis
#+end_example

Instructions suggested adding PostGIS extension as ~root~ but I've found under Arch Linux there is a separate ~postgres~
account for doing administrative tasks with PostgreSQL so I used that. I didn't know the database, you can find this
with...

#+begin_example
su postgres
psql -U postgres

psql (18.1)
Type "help" for help.

postgres=# \l
                                                   List of databases
    Name    |   Owner    | Encoding | Locale Provider | Collate |  Ctype  | Locale | ICU Rules |   Access privileges
------------+------------+----------+-----------------+---------+---------+--------+-----------+-----------------------
 fittrackee | fittrackee | UTF8     | libc            | C.UTF-8 | C.UTF-8 |        |           |
 postgres   | postgres   | UTF8     | libc            | C.UTF-8 | C.UTF-8 |        |           |
 template0  | postgres   | UTF8     | libc            | C.UTF-8 | C.UTF-8 |        |           | =c/postgres          +
            |            |          |                 |         |         |        |           | postgres=CTc/postgres
 template1  | postgres   | UTF8     | libc            | C.UTF-8 | C.UTF-8 |        |           | =c/postgres          +
            |            |          |                 |         |         |        |           | postgres=CTc/postgres
(4 rows)

postgres=# quit
#+end_example

Add the extension to the ~fittrackee~ database as user ~postgres~

#+begin_example
  psql -U postgres -d fittrackee -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
  CREATE EXTENSION
#+end_example

I wasn't sure if this had worked so I found a way to [[https://stackoverflow.com/a/53463490][check if PostGIS is installed]].

#+begin_example
psql -U postgres -d fittrackee
psql (18.1)
Type "help" for help.

fittrackee=# SELECT PostGIS_version();
            postgis_version
---------------------------------------
 3.6 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
#+end_example
Looks like its installed, we're good to go.

*IMPORTANT* - The whole point of this is to enable geo-spatial features, but you can /not/ enable this in ~.env~ via the
 ~ENABLE_GEOSPATIAL_FEATURES=True~ until you have first updated the ~fittrackee~ version and restarted the database so
 hold back.

** Stop the server

#+begin_example
killall fittrackee
ps aux | grep fit
root     1815642  0.0  0.3  10616  6408 pts/7    S    17:00   0:00 su fittrackee
fittrac+ 1815644  0.0  0.3   8840  6972 pts/7    S    17:00   0:00 bash
postgres 1829809  0.0  0.4  17928  8324 pts/0    S+   18:11   0:00 psql -U postgres -d fittrackee
postgres 1829810  0.0  2.0 251368 40148 ?        Ss   18:11   0:00 postgres: postgres fittrackee [local] idle
fittrac+ 1830410  100  0.3  10152  6148 pts/7    R+   18:14   0:00 ps aux
fittrac+ 1830411  0.0  0.2   6956  4264 pts/7    S+   18:14   0:00 grep --color=auto fit
#+end_example

** Create a new virtual environment

I use [[id:4bf1c297-d00a-4857-9339-8017c27138c6][Python Virtual Environments]], in particular ~virtualenvwrapper~

#+begin_example
su fittrackee
cd
mkvirtualenv fittrackee-1.0.4
pip install fittrackee
#+end_example


** Upgrade the database

Here I took a risk, my current install was off of a development version after I had assistance from the developer to fix
an [[https://github.com/SamR1/FitTrackee/issues/716][issue]] with uploading tracks. I wanted to switch to stable releases but the [[https://docs.fittrackee.org/en/installation.html#upgrade][upgrade instructions]] differentiate between
PyPI installs and those from [[https://github.com/SamR1/FitTrackee/][source]] and explicitly warn that the upgrades only work if the previous approach was used.

I took a risk and upgraded my database and it seemed to work ok.

#+begin_example
(fittrackee-1.0.4) $ ftcli db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 78a90b587a9b -> 61ecbc76f410, add Halfbike
INFO  [alembic.runtime.migration] Running upgrade 61ecbc76f410 -> 514c727b7feb, add windsurfing sport and board equipment
INFO  [alembic.runtime.migration] Running upgrade 514c727b7feb -> b0ef6ca5ec92, replace 'users_data_export' table with 'user_tasks' table and update following
tables:
  - 'app_config'
  - 'users'
  - 'workouts'
  - 'workout_segments'
INFO  [alembic.runtime.migration] Running upgrade b0ef6ca5ec92 -> 1648fe51cbd1, add preferences for segments creation (for .fit files)
INFO  [alembic.runtime.migration] Running upgrade 1648fe51cbd1 -> 684e59432ca4, add standup paddleboarding
INFO  [alembic.runtime.migration] Running upgrade 684e59432ca4 -> 4eeeecd3936d, add tennis (outdoor)
INFO  [alembic.runtime.migration] Running upgrade 4eeeecd3936d -> 98688d3d293b, add preference for workout chart display
INFO  [alembic.runtime.migration] Running upgrade 98688d3d293b -> 45fd75e5f16f, add ave and max power
INFO  [alembic.runtime.migration] Running upgrade 45fd75e5f16f -> 8221053f0e81, add index on original file and update value
INFO  [alembic.runtime.migration] Running upgrade 8221053f0e81 -> fed271354410, add geometry and points to workout segments
INFO  [alembic.runtime.migration] Running upgrade fed271354410 -> 0a2e2369b972, add workouts limit for global map and first point geometry to workouts
INFO  [alembic.runtime.migration] Running upgrade 0a2e2369b972 -> 67ae8866b18f, add padel (outdoor)
INFO  [alembic.runtime.migration] Running upgrade 67ae8866b18f -> b30c7818c902, update oauth2_code table
INFO  [alembic.runtime.migration] Running upgrade b30c7818c902 -> 141d3978536a, add messages preferences
#+end_example

** Restart the Application

#+begin_example
$ fittrackee
(fittrackee-1.0.4) $ fittrackee  &
[1] 1837627
[2025-12-25 18:48:34 +0100] [1837627] [INFO] Starting gunicorn 23.0.0
[2025-12-25 18:48:34 +0100] [1837627] [INFO] Listening at: http://127.0.0.1:5000 (1837627)
[2025-12-25 18:48:34 +0100] [1837627] [INFO] Using worker: sync
[2025-12-25 18:48:34 +0100] [1837642] [INFO] Booting worker with pid: 1837642
#+end_example

All looks good, no errors and I can connect to the WebUI.

** Update Workouts

I only upload workouts with GPS data so I'm not sure whether this was required but the [[https://docs.fittrackee.org/en/upgrading-to-1.0.x.html][upgrade 1.0.x instructions]]
indicate that its required to enable geospatial features so I went ahead and did it anyway. I needed to find out how
many workouts I had and how many times I'd have to run the command.

#+begin_example
ls -l uploads/workouts/1/20*.gpx | wc -l
3133
ftcli workouts refresh --add-missing-geometry --per-page 1000 -v
...
Refreshing workout 997/997...
2025/12/25 18:57:20 - fittrackee_workouts_cli - INFO - Refreshing workout 997/997...

Refresh done:
- updated workouts: 994
- errored workouts: 3
2025/12/25 18:57:20 - fittrackee_workouts_cli - INFO -
Refresh done:
- updated workouts: 994
- errored workouts: 3

Done.
2025/12/25 18:57:20 - fittrackee_workouts_cli - INFO -
Done.
#+end_example

Turns out most of mine needed refreshing! Takes a few minutes for 1000 to run and I needed to do this just over three
times. Seems I've a few ~.gpx~ without any segments which is a bit weird but I ignored those and continued with the
refresh. In the end it took more than four attempts to run as it didn't seem to pick up 1000 each time, but that gave me
time to do some [[id:de39fb08-fd16-4da2-889e-e13e952c96ef][Pilates]].

Once completed I edited ~.env~ and set ~ENABLE_GEOSPATIAL_FEATURES=True~. Stopped the running service, ~source .env~ so
that ~$ENABLE_GEOSPATIAL_FEATURES~ is available and restarted it.

#+begin_example
killall fittrackee
fittrackee &
#+end_example

Hey presto! I have maps enabled.

* Links
+ [[https://samr1.github.io/FitTrackee/en/][FitTrackee]]
+ [[https://github.com/SamR1/FitTrackee/][GitHub | FitTrackee]]
