:PROPERTIES:
:ID:       d25bfba9-1460-4c15-bf86-dbabffadc24e
:END:
#+TITLE: ForgeJo Runners
#+FILETAGS: :git:forgejo:runners:selfhost:

Runners make Continuous Integration possible. Under [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] these are available from the AUR [[https://aur.archlinux.org/packages/forgejo-runner][~forgejo-runner~]]
package. It requires the Go language to be installed to build but this should be removed afterwards automatically.

#+begin_src bash
mkdir ~/aur
cd ~/aur
git clone https://aur.archlinux.org/forgejo-runner.git
cd forgejo-runner
makepkg -sri
#+end_src

Once installed refer to the [[https://forgejo.org/docs/next/admin/actions/][Forgejo Actions administrator guide]]. You will need to make sure there are both Docker and
Podman container services available to run the actions whose configurations are hosted elsewhere
(e.g. ~https://code.forgejo.org~).

** Configuration

You have to add the following to the default configuration (default values are not included by default as is the case
for many other aspects of the configuration).

#+begin_src
[actions]
ENABLED = true
DEFAULT_ACTIONS_URL = https://code.forgejo.org
ARTIFACT_RETENTION_DAYS = 30

[storage]
ACTIONS_LOG =
ARTIFACTS =
#+end_src

You then need to register runners.

* Links

+ [[https://jan.wildeboer.net/2024/08/Running-a-runner-codeberg/][Running a runner for Codeberg/Forgejo on RHEL9 as user]]
+ [[https://codeberg.org/whitequark/nixos-forgejo-actions-runner][whitequark/nixos-forgejo-actions-runner: NixOS configuration for turnkey deployment of Forgejo Actions runners - Codeberg.org]]
