:PROPERTIES:
:ID:       0998b01c-7d0a-4aec-99ec-908374de338c
:mtime:    20240705080642
:ctime:    20240705080642
:END:
#+TITLE: Gentoo Portage
#+FILETAGS: :gentoo:portage:packages:


Package management under Gentoo is courtesy of [[https://wiki.gentoo.org/wiki/Portage][Portage]] and the ~emerge~ command which resolves all dependencies. It is
configured via ~/etc/portage/make.conf~ where various flags are defined to determine the architecture of your system

* Installing Packages

To install packages you most have ~root~ access and its sensible to ensure your Portage repository is up-to-date.

#+begin_src bash
  emerge --sync emerge -uDNa <package>
#+end_src


* Binary Packages

Gentoo also supports [[https://wiki.gentoo.org/wiki/Binary_package_guide][Binary packages]] which can be very useful for large packages on older systems with low
resources. The [[https://wiki.gentoo.org/wiki/Binary_package_quickstart][Binary package quickstart]] is a useful starting point.

* Helpers

There are a number of [[https://wiki.gentoo.org/wiki/Useful_Portage_tools][helper packages]] that make working with Gentoo a bit smoother.

+ ~eix~ which is a C based programme that handles syncing repositories and provides a fast interface to packages that
  are available on a system.
+ ~emacs-eix~ emacs interface to eix.
+ ~genlop~ is a useful package for parsing ~emerge.log~ to find out what packages have been installed.
+ ~gentoolkit~ has a number of useful tools such as ~elcean~, ~equery~.
+ ~eselect~ for administering packages and choosing which versions of slotted packages to use
+ ~eclean-kernel~ for tidying up and removing old kernels.
+ ~layman~ for managing Gentoo overlays.

#+begin_src bash
  emerge -av eix genlop gentoolkit eselect eclean-kernel eix-sync
#+end_src
