:PROPERTIES:
:ID:       c76767c4-2a49-42f8-a323-a6d6105e0bce
:mtime:    20251120133916 20251107143616 20250513083634 20240919222900 20231008074712 20230910194920 20230910183127
:ctime:    20230910183127
:END:
#+TITLE: Pre-commit
#+FILETAGS: :git:hooks:pre-commit:

[[https://pre-commit.com/][Pre-commit]] is a powerful [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] tool for executing a range of hooks prior to making commits to your Git history. This is
useful because it means you can automatically run a range of linting tools on your code across an array of languages to
ensure your code is up-to-scratch /before/ you make the commit.

There are a number of other pages on Pre-commit...

+ [[id:8c412a9d-c7ff-4afc-bc05-7bec3f06aa41][Pre-commit CI]]
+ [[id:f00b1609-ba04-4ec2-bbd2-6dec08148776][Pre-commit R]]
+ [[id:8dbde866-810a-48e4-981f-2fcbc19ec5cf][Pre-commit Markdownlint-cli2]]
+ [[id:254f1c27-9822-4211-a118-7ae1d21fe485][Pre-commit rumdl]]

* Background
:PROPERTIES:
:CUSTOM_ID: background
:END:
Pre-commit is written in [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] but that isn't a limitation as it will lint [[id:fac7a695-9bdf-4a79-9ec3-9945e9a0cba4][YAML]], [[id:950174e1-c936-463a-b4a2-702ca516d95e][JSON]], C, JavaScript, [[id:de9a18a7-b4ef-4a9f-ac99-68f3c76488e5][R]], Go, [[id:3469c33e-7c61-46c7-b01e-655695f3b93c][Rust]],
TOML, Terraform, Jupyter Notebooks, and so on. The list of [[https://pre-commit.com/hooks.html][supported hooks]] is vast.

For those unfamiliar with version control and [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] in particular this will likely all sound alien. If you are new to the
world of version control and [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] I can highly recommend the [[https://srse-git-github-zero2hero.netlify.app/][Git & Github through GitKraken Client - From Zero to Hero!]]
course offered by the [[https://rse.shef.ac.uk][Research Software Engineering]] at the University of Sheffield and developed by Alumni
[[https://www.r-rse.eu/][Anna Krystalli]].

** What is a "hook"?
:PROPERTIES:
:CUSTOM_ID: what-is-a-hook
:END:
In computing a "hook" refers to something that is run prior to or in response to a requested action. In the context of
the current discussion we are talking about hooks that relate to actions undertaken in Git version control and
specifically actions that are run before a "commit" is made.

When you have initialised a directory to be under [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] version control the settings and configuration are stored in the
~.git/~ sub-directory. There is the ~.git/config~ file for the repositories configuration but also the ~.git/hooks/~
directory that is populated with a host of ~*.sample~ files with various different names that give you an in-road into
what different hooks you might want to run. Its worth spending a little time reading through these if you haven't done
so yet as they provide useful examples of how various hooks work.

** Why pre-commit hooks?
:PROPERTIES:
:CUSTOM_ID: why-pre-commit-hooks
:END:
Typically when writing code you should [[https://ns-rse.github.io/posts/linting/][lint]] your code to ensure it conforms to agreed style guides and remove any "[[https://en.wikipedia.org/wiki/Code_smell][code
smells]]" that may be lingering (code that violates design principles). It won't guarantee that your code is perfect but
its a good starting point to improving it. People who write a lot of code have good habits of doing these checks
manually prior to making commits. Experienced coders will have configured their Integrated Development Environment (IDE)
to apply many such "hooks" on saving a file they have been working on.

At regular points in your workflow you save your work and check it into Git by making a commit and that is where
~pre-commit~ comes in to play because it will run all the hooks it has been configured to run against the files you are
including in your commit. If any of the hooks fail then your commit is /not/ made. In some cases ~pre-commit~ will
automatically correct the errors (e.g. removing trailing white-space; applying [[https://github.com/psf/black][black]] formatting if configured) but in
others you have to correct them yourself before a commit can be successfully made.

Initially this can be jarring, but it saves you, and more importantly those who you are asking to review your code, time
and effort. Your code meets the required style and is a little bit cleaner before being sent out for review. Long term
linting your code is beneficial (see [[file:2022-04-19-linting][Linting - What is all the fluff about?]]).

* Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:
Pre-commit is written in [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] and so you will need Python installed on your system in order to use it. Aside from that
there is little else extra that is required to be manually installed as pre-commit installs virtual environments
specific for each enabled hook.

Most systems provide ~pre-commit~ in their package management system but typically you should install ~pre-commit~
within your virtual environment or under your user account.

#+begin_src sh
  pip install pre-commit conda install -c conda-forge pre-commit
#+end_src

If you are working on a Python project then you should include ~pre-commit~ as a requirement (either in
~requirements-dev.txt~) or under the ~dev~ section of ~[project.optional-dependencies]~ in your ~pyproject.toml~ as
shown below.
#+begin_example
[project.optional-dependencies]
dev ~
  pre-commit
  pytest
  pytest-cov
#+end_example

* Configuration
:PROPERTIES:
:CUSTOM_ID: configuration
:END:
Configuration of pre-commit is via a file in the root of your [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] version controlled directory called
~.pre-commit-config.yaml~. This file should be included in your [[id:0859ef9e-834d-4e84-8e67-fa7593a61e0b][Git]] repository, you can create a blank file or
~pre-commit~ can generate a sample configuration for you.

#+begin_example
# Empty configuration
touch .pre-commit-config.yaml
# Auto-generate basic configuration
pre-commit sample-config > .pre-commit-config.yaml
# Add to Git repository regardless of above method used
git add .pre-commit-config.yaml
#+end_example

** Hooks
:PROPERTIES:
:CUSTOM_ID: hooks
:END:
Each hook is associated with a repository (~repo~) and a version (~rev~) within it. Many are available from the
~https://github.com/pre-commit/pre-commit-hooks~. The default set of ~pre-commit~ hooks might look like the following.

#+begin_example
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0 # Use the ref you want to point at
      hooks:
          - id: trailing-whitespace
            types: [file, text]
          - id: check-docstring-first
          - id: check-case-conflict
          - id: end-of-file-fixer
            types: [python]
          - id: requirements-txt-fixer
          - id: check-yaml
#+end_example

** Hooks from External Repositories
:PROPERTIES:
:CUSTOM_ID: hooks-from-external-repositories
:END:
Some hooks are available from dedicated repositories, for example the following runs [[https://github.com/psf/black][Black]], [[https://flake8.pycqa.org/en/latest/][Flake8]] and [[https://pylint.pycqa.org/en/latest/][Pylint]] on your
code and should follow under the above (with the same level of indenting to be valid YAML).

#+begin_example
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
        - id: black
          types: [python]

  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
        - id: flake8
          additional_dependencies: [flake8-print]
          types: [python]
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
        - id: pylint
#+end_example

An extensive list of [[https://pre-commit.com/hooks.html][supported hooks]] is available. It lists the repository from
which the hook is derived along with its name.

** Local Hooks
:PROPERTIES:
:CUSTOM_ID: local-hooks
:END:
You can also define [[https://pre-commit.com/#new-hooks][new hook]] and configure them under the ~- repo: local~.

#+begin_example
  - repo: local
    hooks:
      - id: <id>
        name: <descriptive name>
        language: python
        entry:
        types: [python]
#+end_example

For some examples of locally defined hooks see the
[[https://github.com/pandas-dev/pandas/blob/main/.pre-commit-config.yaml][Pandas .pre-commit-config.yaml]].

* Usage
:PROPERTIES:
:CUSTOM_ID: usage
:END:
Before ~pre-commit~ will run you need to install it within your repository. This puts the file ~.git/hooks/pre-commit~
in place that contains the hooks you have configured to run. To install this you should have your
~.pre-commit-config.yaml~ in place and then run the following.

#+begin_src sh
  pre-commit install
#+end_src

Once installed and configured there really isn't much to be said for using ~pre-commit~, just make commits and before
you can make a successful commit ~pre-commit~ must run with all the hooks you have configured passing. By default
~pre-commit~ only runs on files that are staged and ready to be committed, if you have unstaged files these will be
stashed prior to running the ~pre-commit~ hook and restored afterwards. Should you wish to run these manually without
making a commit then, after activating a virtual environment if you are using one, simply make a ~git commit~ or you can
run.

#+begin_src sh
  pre-commit run
#+end_src

If any of the configured hooks fail then the commit will not be made.  Some hooks such as [[https://github.com/psf/black][black]] may reformat files in
place and you can then make another commit recording those changes and the hook should pass. Its important to pay close
attention to the output.  If you want to run a specific hook you simply add the ~<id>~ after ~run~.

#+begin_src sh
  pre-commit run <id>
#+end_src

Or if you want to force running against all files (except unstaged ones) you can do so.

#+begin_src sh
  pre-commit run --all-files # Across all files/hooks
#+end_src

And these two options can be combined to run a specific hook against all files.

#+begin_src sh
  pre-commit run <id> --all-files
#+end_src

You may find that you wish to switch branches to work on another feature or fix a bug but that your current work doesn't
pass the ~pre-commit~ and you don't wish to sort that out immediately. The solution to this is to use ~git stash~ to
temporarily save your current uncommitted work and restore the working directory and index to its previous state. You
are then free to switch branches and work on another feature or fix a bug, commit and push those changes and then switch
back.

Imagine you are working on branch ~a~ but are asked to fix a bug on branch ~b~. You go to commit your work but find that
~a~ does not pass ~pre-commit~ but you wish to work on ~b~ anyway. Starting on branch ~a~ you stash your changes, switch
branches, make and commit your changes to branch ~b~ then switch back to ~a~ and unstash your work there.

#+begin_src sh
  git stash git checkout b ... # Work on branch b git add <changed_files_on_branch_b> git commit -m "Fixing bug on branch
  b" git push git checkout a git stash apply
#+end_src

* Updating
:PROPERTIES:
:CUSTOM_ID: updating
:END:
You can update hooks locally by running ~pre-commit autoupdate~. This will update your ~.pre-commit-config.yaml~ with
the latest version of repositories you have configured and these will run both locally and if you use CI/CD as described
below. However this will /not/ update any packages that are part of the ~- repo: local~ that you may have implemented
and it is your responsibility to handle these.

* Pre-commit CI/CD
:PROPERTIES:
:CUSTOM_ID: pre-commit-cicd
:END:
Ideally contributors will have setup their system to work with pre-commit and be running such checks prior to making
pushes. It is however useful to enable running pre-commit as part of your Continuous Integration/Development pipeline
(CI/CD). This can be done with both [[https://gitlab.com][GitLab]] and [[https://github.com][GitHub]] although similar methods are available for many
[[https://pre-commit.com/#usage-in-continuous-integration][continuous integration systems]].

There is much more to CI with ~pre-commit~ which you can read[[id:8c412a9d-c7ff-4afc-bc05-7bec3f06aa41][git_precommit_ci]]

** GitHub
:PROPERTIES:
:CUSTOM_ID: github
:END:
GitHub actions reside in the ~.github/workflows/~ directory of your project. A simple pre-commit action is available on
the Marketplace at [[https://github.com/marketplace/actions/pre-commit][pre-commit/action]].  Copy this template to ~.github/workflows/pre-commit.yml~ and include it in your
Git repository.

#+begin_src sh
  git add .github/workflows/pre-commit.yml git commit -m "Adding pre-commit GitHub Action" && git push
#+end_src

** GitLab
:PROPERTIES:
:CUSTOM_ID: gitlab
:END:
If you use GitLab the following article describes how to configure a CI job to run as part of your repository.

- [[https://stackoverflow.com/collectives/gitlab/articles/71270196/how-to-use-pre-commit-to-automatically-correct-commits-and-merge-requests-with-g][How to use pre-commit to automatically correct commits and merge requests with GitLab CI]]

* Other Languages

~pre-commit~ doesn't work just with [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]], it works with /any/ language. I've written an article on using [[id:f00b1609-ba04-4ec2-bbd2-6dec08148776][Pre-commit
with R]].


* Hooks I use

A non-exhaustive list of hooks that I use by language.

** General

+ ~check-added-large-files~
+ ~check-case-conflict~
+ ~check-toml~
+ ~check-yaml~
+ ~debug-statements~
+ ~end-of-file-fixer~
+ ~mixed-line-ending~
+ ~trailing-whitespaces~

** Markdown

+ [[id:8dbde866-810a-48e4-981f-2fcbc19ec5cf][~markdown-cli2~]]

** Python

+ ~black~
+ ~isort~
+ ~nbQA~
+ ~nbstripout~
+ ~pydoctstyle~
+ ~pylint~
+ ~pyupgrade~
+ ~ruff~

** Security

+ [[https://github.com/gitleaks/gitleaks][gitleaks/gitleaks: Find secrets with Gitleaks 🔑]]

* Links
:PROPERTIES:
:CUSTOM_ID: links
:END:
+ [[https://pre-commit.com/][Pre-commit]]
+ [[https://pre-commit.com/hooks.html][Supported hooks]]
+ [[https://github.com/marketplace/actions/pre-commit][GitHub Action]]
+ [[https://stackoverflow.com/collectives/gitlab/articles/71270196/how-to-use-pre-commit-to-automatically-correct-commits-and-merge-requests-with-g][GitLab CI]]

** Misc

+ [[https://github.com/tox-dev/pre-commit-uv][tox-dev/pre-commit-uv]]

** Hooks

+ [[https://www.pydocstyle.org/en/stable/usage.html#usage-with-the-pre-commit-git-hooks-framework][pydocstyle]]

** Alternatives

+ [[https://prek.j178.dev/][prek]]
+ [[https://megalinter.io/latest/][MegaLinter]]
