:PROPERTIES:
:ID:       f4f7b185-7263-418d-bb53-e5280e2b9068
:mtime:    20250423135552 20250304204632 20241025200654
:ctime:    20241025200654
:END:
#+TITLE: Git Commit
#+FILETAGS: :git:

* Secrets
:PROPERTIES:
:ID:       537032aa-3f89-4267-b79b-95380b9404b2
:mtime:    20250423135552
:ctime:    20250423135552
:END:

Sometimes you have secrets such as API keys that may reside in files within your repository. Committing and pushing
these to a [[id:28ffcc43-9dff-4de8-a211-277c5346a642][Forge]] is a bad idea, they then become public and whilst it is possible to remove them using tools such as [[https://rtyley.github.io/bfg-repo-cleaner/][BFG
Repo Cleaner]] this is a bit of a pain and still leaves you having exposed your secrets for a period of time. Better to
avoid in the first place.

** [[https://github.com/gitleaks/gitleaks][GitHub - gitleaks/gitleaks: Find secrets with Gitleaks 🔑]]

A useful tool with both a [[https://github.com/gitleaks/gitleaks#github-action][GitHub Action]] and [[https://github.com/gitleaks/gitleaks#pre-commit][Pre-Commit]] hook that allows you to check that secrets have not been added to
your repository.

You'd be best of using the [[https://github.com/gitleaks/gitleaks#pre-commit][Pre-Commit]] hook to ensure you don't commit and push changes.

* Links

+ [[https://www.conventionalcommits.org/en/v1.0.0/][Conventional Commits]]
+ [[https://dev.to/craicoverflow/enforcing-conventional-commits-using-git-hooks-1o5p][Enforcing Conventional Commits using Git Hooks]]
+ [[https://github.com/RomuloOliveira/commit-messages-guide/tree/master][commit-messages-guide: A guide to understand the importance of commit messages and how to write them well]]

** Tools

+ [[https://github.com/gitleaks/gitleaks][Git Leaks]]
+ [[https://rtyley.github.io/bfg-repo-cleaner/][BFG Repo Cleaner]]
