:PROPERTIES:
:ID:       98fb864e-8e55-47cb-bfe8-c002d9e3d435
:mtime:    20240829233948 20240829153651 20240130204153
:ctime:    20240130204153
:END:
#+TITLE: Git Hooks
#+FILETAGS: :git:versioncontrol:precommit:hooks:ci:


Hooks are incredibly useful (not just in Git, but in general and form the basis of many [[id:3b6a27c8-6ef9-4133-95b9-302d2e4dbea3][CI/CD]] pipelines), but they also
run locally on various Git actions such as ~pre-commit~, ~post-commit~, ~pre-push~ or ~pre-pull~. Hooks are simple [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]]
scripts that reside in ~.git/hooks~ with specific filenames that indicate at which stage they are to be run. Typically
this directory will be populated with various examples for the different hooks that are available if you have created
your repository locally.

* Configuration

** ~core.hooksPath~

Configure the ~core.hooksPath~ and place all files in a ~./.hooks~ directory so they can be version controlled as
suggested in [[https://alecthegeek.gitlab.io/blog/2024/08/manage-git-and-hook-scripts-the-easy-way/][Manage Git and Hook Scripts the easy way]].


* Pre-commit

[[https://pre-commit.com][Pre-commit]] and the associated service [[https://pre-commit.ci][pre-commit.ci]] are wonderful tools. I've written about them in a few blog posts and
even given a talk to the Research Computing group at the University of Leeds.

+ [[https://ns-rse.github.io/posts/pre-commit/][Pre-Commit : Protecting your future self]]
+ [[https://ns-rse.github.io/posts/pre-commit-updates/][Pre-Commit : Customising and Updating]]
+ [[https://ns-rse.github.io/posts/pre-commit-ci/][Pre-Commit.ci : Integrating Pre-Commit into CI/CD]]
+ [[https://ns-rse.github.io/pre-commit/#/title-slide][Slides]] ([[https://github.com/ns-rse/pre-commit][source]])

That doesn't cover everything though so more notes are in the [[id:c76767c4-2a49-42f8-a323-a6d6105e0bce][Pre-commit]] section and linked from there.
