:PROPERTIES:
:ID:       3ef233c9-2d33-44d8-89ec-463e2631240c
:END:
#+TITLE: Go
#+FILETAGS: :programming:language:go:

Go is a compiled programming language, it's pretty stable seeing very few major releases and seems to deliberately be
parsimonious which helps maintain backwards compatibility (the traditional UNIX philosophy and a good thing). This is
likely in part is Go was do-developed by [[https://en.wikipedia.org/wiki/Ken_Thompson][Ken Thompson]], one of the original authors of Unix and the C language amongst
other things.

* Installation

Go is available in most decent operating systems package managers.

* ~go~

~go~ is the command for managing Go source code, it has a number of sub-commands used for managing a package.

#+begin_example
❱ go --help
Go is a tool for managing Go source code.

Usage:

	go <command> [arguments]

The commands are:

	bug         start a bug report
	build       compile packages and dependencies
	clean       remove object files and cached files
	doc         show documentation for package or symbol
	env         print Go environment information
	fix         apply fixes suggested by static checkers
	fmt         gofmt (reformat) package sources
	generate    generate Go files by processing source
	get         add dependencies to current module and install them
	install     compile and install packages and dependencies
	list        list packages or modules
	mod         module maintenance
	work        workspace maintenance
	run         compile and run Go program
	telemetry   manage telemetry data and settings
	test        test packages
	tool        run specified go tool
	version     print Go version
	vet         report likely mistakes in packages

Use "go help <command>" for more information about a command.

Additional help topics:

	buildconstraint build constraints
	buildjson       build -json encoding
	buildmode       build modes
	c               calling between Go and C
	cache           build and test caching
	environment     environment variables
	filetype        file types
	goauth          GOAUTH environment variable
	go.mod          the go.mod file
	gopath          GOPATH environment variable
	goproxy         module proxy protocol
	importpath      import path syntax
	modules         modules, module versions, and more
	module-auth     module authentication using go.sum
	packages        package lists and patterns
	private         configuration for downloading non-public code
	testflag        testing flags
	testfunc        testing functions
	vcs             controlling version control with GOVCS

Use "go help <topic>" for more information about that topic.
#+end_example

* Module dependency

Imports are managed through your own code's module which is defined in ~go.mod~ . This is created using...

#+begin_example shell
go mod init <module_name>
#+end_example

* Grouping functions - ~package~

The header of each Go source file starts with the line ~package <name>~ which groups functions into a package.
* Links

+ [[https://go.dev/][Go]]
+ [[https://go.dev/learn/][Get Started - The Go Programming Language]]
