:PROPERTIES:
:ID:       066a4ad3-d938-4ee5-a5b9-1bec44012734
:mtime:    20251022140344 20250902201951
:ctime:    20250902201951
:END:
#+TITLE: Home Assistant
#+FILETAGS: :linux:automation:home:

* Home Assistant

** Arch Linux ARM Install

Official support for Home Assistant on Arch Linux has been dropped, they recommend using Docker, but there is no Docker
image for the ~arm7h~ architecture that my [[id:69864d74-8ec2-42e4-a227-f824a521a5ce][Raspberry Pi]] 4b runs. Instead I looked to [[https://aur.archlinux.org/packages?O=0&K=home-assistant][AUR]] and found a number of packages,
some core some peripheral.

Create a virtual environment under ~~/aur~, I use [[id:99d3e5a1-bf9b-44f3-afc9-fed5ffead7bd][uv]] for this but you could easily use any [[id:4bf1c297-d00a-4857-9339-8017c27138c6][Python Virtual Environments]]. Don't forget
to setup [[id:a4af96d2-f895-4a68-9419-d482d2850f4d][Direnv]] to load the environment.

#+begin_example shell
#!/bin/bash
set -euo pipefail

function print_stage() {
    echo -e " \e[33m*\e[39m \e[94m$1\e[39m"
}

# TODO - Setup a temproary virtualenv with virtualenvwrapper to build and install package

# Install the core packages
for x in "home-assistant" "python-home-assistant-hacs" "python-home-assistant-frontend";
do
    print_stage "Installing : ${x}"
    git clone https://aur.archlinux.org/"${x}".git
    cd "${x}"
    makepkg -sri
done

#+end_example

I found I had to modify the ~PKGBUILD~ for ~python-home-assistant-frontend~ to work with ~uv~ and change ~pip install ...~
to ~uv pip install ...~.

Packages that are installed and then removed as part of the build process (might be worth installing globally)
+ ~python-attrs~
+ ~python-pip~
+ ~python-build~
+ ~python-pyproject-hooks~

Once installed you need to start the ~home-assitant.service~ and can optionally enable it to run on startup. The initial
startup appears to take a little while to set everything up as a large number of packages are installed using a virtual
environment.

#+begin_example
systemctl enable --now home-assistant.service
#+end_example


This will take a while to run as it downloads and installs a bunch of additional Python packages. I found it ground my
Pi to a halt and made it a little unstable for a while and had to manually reboot. But on rebooting I was able to
restart the service and I could visit ~https://192.168.1.##:8123~ and was able to see the welcome dashboard which I then
setup an account for.

** Deprecation

Oh dear...

#+begin_quote
This system is using the Core installation type, and 32-bit hardware (armv7l), both of which have been deprecated and
will no longer be supported after the release of Home Assistant 2025.12.
#+end_quote

* Extensions

** Home Assistant Community Store (HACS)

First I needed to install [[https://www.hacs.xyz/docs/use/][HACS]] but unfortunately I found that I get a warning about

* Links

** Hardware

+ [[https://www.home-assistant.io/green/][Home Assistant Green - Home Assistant]]
+ [[https://www.ikea.com/us/en/cat/wireless-led-bulbs-36813/][IKEA Smart Bulbs]]

** Software

+ [[https://www.home-assistant.io/][Home Assistant]]

*** Modules

+ [[https://www.home-assistant.io/integrations/forecast_solar/][Forecast.Solar - Home Assistant]]

** Sensors

+ [[https://www.frient.com/products][Frient]] (purchase from [[https://www.carefreesmarthomes.co.uk/frient][Carefree Smart Homes]])

** Threads

+ [[https://fosstodon.org/@justin@ramble.space/115417870904052209][Mastodon Recommendation for privacy devices]]
