:PROPERTIES:
:ID:       7dd30b1c-c484-4b49-88e2-4f3fec755a79
:mtime:    20250806065755 20250801153333 20250730232002 20250729221516 20250729073038
:ctime:    20250729073038
:END:
#+TITLE: Hyprland
#+FILETAGS: :linux:x11:desktop:

[[https://wiki.hypr.land/][Hyprland]] is a compositor for [[id:5de2c921-cecf-4c1b-9d43-4552e34b1688][Wayland]].

* Installation

Here are all the individual programmes I installed under both [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] and [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]]

** Arch Linux

#+begin_src
pacman -Syu \
 hypridle \
 hyprland \
 hyprlock \
 hyprpaper \
 hyprpolkitagent
 hyprshot \
 hyprwayland-scanner \
 otf-font-awesome \
 swayidle \
 swaylock \
 waybar \
#+end_src

*** AUR

#+begin_src
hyprpanel
#+end_src
** Gentoo

#+begin_src
emerge -av \
 fontawesome \
 fontawesome-extension \
 hyprland \
 hyprland-contrib \
 hyprlock \
 hyprpaper \
 hyprpolkitagent \
 hyprshot \
 hyprwayland-scanner \
 nwg-look \
 swayidle \
 swaylock \
 waybar
#+end_src

* General

You can set general/default settings under ~general {...}~ and ~decoration {...}~ but these can be over-ridden on a per
monitor/programme basis.

* [[https://wiki.hypr.land/0.46.0/Configuring/Monitors/][Monitors]]

Find out what monitors you have with ~hyprctl monitors~.

#+begin_src
# = name, resolution, offset, scale
monitor = eDP-1, highres, 0x0, 1
#+end_src

Here ~highres~ sets the maximum resolution for the monitor. ~0x0~ is the offset from the top-left. For the first monitor
this is irrelevant its always anchored to the top-left, but for subsequent monitors it defines whether they are placed
to the left/right/above/below the first monitor.

* [[https://wiki.hypr.land/0.46.0/Configuring/Workspace-Rules/][Workspace]]

By default in Hyprland treats each monitor/screen as its own workspace. The [[https://github.com/levnikmyskin/hyprland-virtual-desktops][levnikmyskin/hyprland-virtual-desktops]]
plugin implements virtual-desktop functionality which groups screens into workspaces.

You can then configure a workspace to be on a specific monitor.

#+begin_src
workspace = name:terminal, monitor:DP-1
#+end_src

* Wallpaper

Wallpapers come courtesy of [[https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/][hyprpaper]]

* Panel

Panel comes courtesy of [[https://github.com/pdf/hyprpanel][hyprpanel]]

* Authentication

** Elevated Priveliges

Install and use [[https://wiki.hypr.land/Hypr-Ecosystem/hyprpolkitagent/][~hyprpolkitagent~]] to get a GUI that requests elevated privileges.

* Taskbar

Install ~waybar~ and if you want the default icons you should also install ~otf-font-awesome~ (under Arch, for Gentoo
its ~media-fonts/fontawesome~ and perhaps ~media-fonts/fontawesome-extension~)

* ScreenSaver



* Screen Lock / Hibernate


* Links

+ [[https://wiki.hypr.land/][Hyprland]]
+ [[https://github.com/Alexays/Waybar/wiki/Configuration][Waybar]] (wiki)
+ [[https://github.com/horriblename/hyprgrass][hyprgrass]] gestures for touch screens
+ [[https://github.com/hyprwm/hyprlock][hyprlock]]
+ [[https://github.com/pdf/hyprpanel][hyprpanel]]
