:PROPERTIES:
:ID:       0e6300c6-7025-4f45-820d-4d9da82b41a6
:mtime:    20251227132633 20251225115645 20251216091907 20251213075059 20251211234747 20251211094106 20251124080425 20250831233329 20250528080159 20250526201922 20250524095641 20250322220520 20250314221237 20250129091643 20250126124211 20250118215315 20241014185041 20241009203940 20240910211009 20240418114040 20240304160438 20240302204630 20240121200503 20240121115714 20240107103825 20231219213305 20231126221347 20231121204845 20231120130321 20231015172332 20231005133759 20230926220759 20230917083604 20230905212306 20230724174038
:ctime:    20230724174038
:END:
#+TITLE: Linux
#+FILETAGS: :linux:computing:foss:opensource:

Linux is often considered the poster-child for the [[id:f277da12-5d6d-46e3-a49c-7bda9254d469][FOSS]] movement, but things actually started a lot earlier when [[id:0e3e2e06-d587-404e-ab7b-21837a60118a][Richard
Stallman]] setup the [[id:8b1e2298-ee48-43d3-a00b-94bb68413927][Free Software Foundation]] and started the [[https://www.gnu.org/][The GNU Operating System and the Free Software
Movement]] (of which [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]] is just one component, albeit a very important one!). There is the related  [[https://www.eff.org/][Electronic Frontier
Foundation]]  which also champions civil liberties in the digital world.

Linux is the code that gets your hardware to talk to each other and interact with the GNU Operating System and so is
itself, a pretty important component (the GNU attempt to get a replacement UNIX kernel, [[https://www.gnu.org/software/hurd/][hurd]] is /still/ a work in
progress).

I've used GNU/Linux variants for almost 20 years they are brilliant and an amazing example of what can be achieved using
the [[id:f277da12-5d6d-46e3-a49c-7bda9254d469][Free Open Source Software (FOSS)]] and collaborative working. I've used many variants starting with RedHat 7.3, then
trying out [[https://slackware.com][Slackware]] for a few years before jumping to [[https://www.gentoo.org][Gentoo]] and more recently using [[https://archlinux.org][Arch]] for lower powered devices and
work machines as I don't have time to tinker/maintain them in addition to my long standing Gentoo server.


* Distributions

I started with RedHat 7.3 at work setting up a server for others to run their [[id:9aa32f65-144f-4c52-aab6-afebd17c1e5b][Genetic]] analysis on. Quickly decided to
try out [[http://www.slackware.com/][Slackware]] at home, liked compiling from source and the lack of circular dependency hell that frustrated me with
RedHats RPM system.  After a while wanted a package management system as I found it awkward uninstalling a packages
dependencies and so tried out [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] and loved it and still use it to this day. For laptops and lower-powered devices
I've settled on [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] as I've never bothered to set up distributed cross-compilation under Gentoo. I'm very
interested to give NixOS a whirl though.

+ [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]]
+ [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch]]
+ [[id:69291a6b-c253-44bc-ad9d-8d899bb90529][NixOS]]
+ [[https://repology.org/][Repology]] a useful site that gives an overview of packages across distributions.

* Admin

+ [[id:e1ef1f56-6f9b-4512-ba34-79bd6448839c][Linux Administration]]
+ [[id:191117d7-b413-4409-84b5-0183599d9f4e][Ansible]]

* Disk Management

+ [[id:75f53f5a-6be0-4264-99ad-fd7f3cbabcec][Partitioning]]
+ [[id:d362171c-91ef-4894-ad6a-92d3f8b7c9af][Flie System]]
+ [[id:eaa3b7c6-7c4c-4eb1-9c18-e4fc65c9b1e7][Labelling]]
+ [[id:3e2c8539-9df7-434b-a53a-d9627bc1a5f7][Resize Logical Volumes under RAID]]

* Shells

I was a happy [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]] user for many years but then I started a job at a tech company and people were using the fancy [[id:a1b78518-31e8-4fd3-a36f-d8f152832138][ZSH]]
along with the [[https://ohmyz.sh/][Oh-myZsh]] framework. I liked the extra information and tools it provided so switched and haven't looked
back. I still use Bash for my ~root~ account though just to make me a little more cautious.

* Web Hosting

I use Linux on my VPS and various places to host websites. I've written more on this at [[id:e1dcf5fc-2125-455d-b800-d3f1b318c8c9][Web-hosting.]] Useful topics on
specific services are also written up at.

+ [[id:3774439d-af75-453e-b3e9-9d578b6bec46][nginx]]
+ [[id:13de4e0e-4c14-48c8-897e-42862be8cfc1][discourse]]


* Live USB
:PROPERTIES:
:mtime:    20251216091907 20251213075059 20250526201922 20250322220520 20240107103841
:ctime:    20240107103841
:END:

It can be handy to have a live distribution to carry around and boot as and when, there are a few options read more
[[id:eaf15ed2-dd31-4b30-a6ce-4b47b6baed0f][here]].


* Miscellaneous Topics
:PROPERTIES:
:ID:       f67cfdbc-32de-4a45-8e04-72d94c11ddd8
:mtime:    20251211234747 20251211094106 20250528080159 20250314221237 20250129091643 20250118215315 20240304160438 20240302204630 20240107103825
:ctime:    20240107103825
:END:

+ [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]]
+ [[id:6bc1142d-44aa-450c-b1a1-fa1ff32e0f83][Booklore]]
+ [[id:62ce92c8-2493-4e7f-b32a-196535c42886][Calibre]]
+ [[id:20a2e57f-b3bf-441a-87f5-e4a5c162eb71][coolify]]
+ [[id:c2e33394-c992-4ef4-82a6-e434f98a2a5a][curl]]
+ [[id:9384a236-065e-4384-9b90-2a083736eb17][dd]]
+ [[id:a4af96d2-f895-4a68-9419-d482d2850f4d][direnv]]
+ [[id:13de4e0e-4c14-48c8-897e-42862be8cfc1][discourse]]
+ [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]]
+ [[id:5d906b68-22c8-4169-8b0d-d3f3a02d2faa][Etherpad]]
+ [[id:170e7f2e-5bbf-4247-bacf-5459835ec26b][Garage]]
+ [[id:08b71419-a3fc-4c7e-8fb6-75f613e41315][Just]]
+ [[id:d0998286-1c36-47d7-943d-6b5f641a9e4d][Kitty]] - an excellent Terminal Emulator.
+ [[id:83df78ca-e349-418f-ab71-b7735c16d027][MPD]]
+ [[id:3774439d-af75-453e-b3e9-9d578b6bec46][Nginx]]
+ [[id:0539fa9c-fc0e-4cb8-a3f4-eee46899240a][Node Package Manager]]
+ [[id:8af3e4ee-799b-4016-9fa9-995f3a9c7c5b][pandoc]]
+ [[id:76578fdf-d00f-4eb6-ad74-13bb08fc5d65][qemu]]
+ [[id:fab2461a-c95a-47e3-9e5d-64af083c92e0][QEMU]]
+ [[id:8b2ddcec-2b0a-4cb2-9bd5-f558d0b7ad93][rkhunter]]
+ [[id:d1ce8192-41ce-4073-9fe8-654fd17fdadb][Security]] - includes [[id:ce08bd82-0146-49cb-8a64-048ffe7210f2][GnuPG]] and [[id:1f44c0fe-5b1c-4a02-a623-18c4eebbc851][Yubikey]].
+ [[id:7c341a0b-a59b-403e-a574-061d326c4c50][Snapcast]]
+ [[id:be393585-6c62-4ce9-9fba-15e4d1c472cb][SyncThing]]
+ [[id:b9f12c22-08db-46c1-a4fa-5ab9ee1a734c][Tmux]]
+ [[id:63fa9747-24ef-40e2-a2ed-d6bd4133374f][Xfce4]]
+ [[id:58938b15-84c8-48dc-8b7e-64e54f1d5c42][Unix Alternatives]]

* Android

[[id:2c46e54a-d704-4e7e-bca3-d8c3e042ab43][Android]] is an operating system for mobile phones that runs the Linux kernel (and a lot of [[id:88fc1e91-d928-485e-83b4-1991663fa267][GNU/Linux]] utilities).

* Privacy

A lot of FOSS respects and protects your [[id:b5000932-0fec-4353-acc4-0cb02127c9ac][privacy]] as it is more transparent than closed source software.

* Links

** [[https://fosscomics.com/][F/OSS Comics]]

+ [[https://fosscomics.com/8.%20The%20Origins%20of%20Unix%20and%20the%20C%20Language/][8. The Origins of Unix and the C Language]]

** Misc

+ [[https://it-notes.dragas.net/2024/09/10/make-your-own-readonly-device-with-netbsd/][Make Your Own Read-Only Device With NetBSD - IT Notes]]
+ [[https://www.theregister.com/2024/10/08/switching_from_linux_to_bsd/][Switching customers from Linux to BSD because boring is good • The Register]]

** Videos

+ [[https://www.youtube.com/watch?v=WEb_YL1K1Qg][UNIX: A History and a Memoir by Brian Kernighan - YouTube]]
+ [[https://www.youtube.com/watch?v=EY6q5dv_B-o][Ken Thompson interviewed by Brian Kernighan at VCF East 2019 - YouTube]]
