:PROPERTIES:
:ID:       0e6300c6-7025-4f45-820d-4d9da82b41a6
:mtime:    20240121200503 20240121115714 20240107103825 20231219213305 20231126221347 20231121204845 20231120130321 20231015172332 20231005133759 20230926220759 20230917083604 20230905212306 20230724174038
:ctime:    20230724174038
:END:
#+TITLE: Linux
#+FILETAGS: :linux:computing:foss:opensource:

Linux is often considered the poster-child for the [[id:f277da12-5d6d-46e3-a49c-7bda9254d469][FOSS]] movement, but things actually started a lot earlier when Richard
Stallman setup the [[https://www.eff.org/][Electronic Frontier Foundation]] and started the [[https://www.gnu.org/][The GNU Operating System and the Free Software
Movement]] (of which [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]] is just one component, albeit a very important one!).

Linux is the code that gets your hardware to talk to each other and interact with the GNU Operating System and so is
itself, a pretty important component (the GNU attempt to get a replacement UNIX kernel, [[https://www.gnu.org/software/hurd/][hurd]] is /still/ a work in
progress).

* Distributions

I started with RedHat 7.3 at work setting up a server for others to run their [[id:9aa32f65-144f-4c52-aab6-afebd17c1e5b][Genetic]] analysis on. Quickly decided to
try out [[http://www.slackware.com/][Slackware]] at home, liked compiling from source and the lack of circular dependency hell that frustrated me with
RedHats RPM system.  After a while wanted a package management system as I found it awkward uninstalling a packages
dependencies and so tried out [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] and loved it and still use it to this day. For laptops and lower-powered devices
I've settled on [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] as I've never bothered to set up distributed cross-compilation under Gentoo.

* Shells

I was a happy [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]] user for many years but then I started a job at a tech company and people were using the fancy [[id:a1b78518-31e8-4fd3-a36f-d8f152832138][ZSH]]
along with the [[https://ohmyz.sh/][Oh-myZsh]] framework. I liked the extra information and tools it provided so switched and haven't looked
back. I still use Bash for my ~root~ account though just to make me a little more cautious.

** Terminals

I like using the [[https://sw.kovidgoyal.net/kitty/][kitty]] terminal emulator. Its highly configurable, fast and easy to use (plus it supports transparency
and doesn't use large boarders which take up real-estate on the screen).

It doesn't always play ball when you've SSH'd in to other machines though. I couldn't find a solution to this so [[https://unix.stackexchange.com/questions/470676/tmux-under-kitty-terminal][asked]]
and got some very useful responses. The simplest is to install ~kitty~ on the remote server, but that isn't always
possible, in which case you should copy the ~terminfo~ from your local machine to your remote host.

#+begin_src bash
$ ssh myserver mkdir -p  ~/.terminfo/${TERM:0:1}
$ scp /usr/share/terminfo/${TERM:0:1}/$TERM myserver:~/.terminfo/${TERM:0:1}/
#+end_src


* Web Hosting

I use Linux on my VPS and various places to host websites. I've written more on this at [[id:e1dcf5fc-2125-455d-b800-d3f1b318c8c9][Web-hosting.]]

* Live USB
:PROPERTIES:
:mtime:    20240107103841
:ctime:    20240107103841
:END:

It can be handy to have a live distribution to carry around and boot as and when, there are a few options read more at
[[id:eaf15ed2-dd31-4b30-a6ce-4b47b6baed0f][here]].

* Topics
:PROPERTIES:
:ID:       f67cfdbc-32de-4a45-8e04-72d94c11ddd8
:mtime:    20240107103825
:ctime:    20240107103825
:END:

Miscellaneous topics

+ [[id:d0998286-1c36-47d7-943d-6b5f641a9e4d][Kitty]] - an excellent Terminal Emulator.
+ [[id:d1ce8192-41ce-4073-9fe8-654fd17fdadb][Security]] - includes [[id:ce08bd82-0146-49cb-8a64-048ffe7210f2][GnuPG]] and [[id:1f44c0fe-5b1c-4a02-a623-18c4eebbc851][Yubikey]].
+ [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]]
+ [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]]
+ [[id:76578fdf-d00f-4eb6-ad74-13bb08fc5d65][qemu]]
+ [[id:0539fa9c-fc0e-4cb8-a3f4-eee46899240a][Node Package Manager]]
+ [[id:63fa9747-24ef-40e2-a2ed-d6bd4133374f][Xfce4]]

* Android

[[id:2c46e54a-d704-4e7e-bca3-d8c3e042ab43][Android]] is an operating system for mobile phones that runs the Linux kernel (and a lot of [[id:88fc1e91-d928-485e-83b4-1991663fa267][GNU/Linux]] utilities).

* Privacy

A lot of FOSS respects and protects your [[id:b5000932-0fec-4353-acc4-0cb02127c9ac][privacy]] as it is more transparent than closed source software.

* Links
