:PROPERTIES:
:ID:       a4af96d2-f895-4a68-9419-d482d2850f4d
:mtime:    20250904090628 20250321105030 20250131200030 20250129091630
:ctime:    20250129091630
:END:
#+TITLE: Direnv
#+FILETAGS: :linux:shell:virtualenv:

[[https://direnv.net/][Direnv]] is a tool for managing virtual environments based on the directory you are currently in.

* Installation

Depends on your distribution.

#+begin_src
# Gentoo (via guru overlay)
emerge -av direnv
# Arch
pacman -Syu direnv
#+end_src

If you use [[id:69291a6b-c253-44bc-ad9d-8d899bb90529][NixOS]] include it in your packages somewhere!

** Shell Integration

After installing you need to ensure that ~direnv~ is [[https://direnv.net/docs/hook.html][hooked]] into your shell. This will depend on the shell you use. I
typically use [[id:a1b78518-31e8-4fd3-a36f-d8f152832138][ZSH]] and also use oh-my-zsh so there were two options.

#+begin_src
# plain ZSH integration
eval "$(direnv hook zsh)"
# oh-my-zsh plugin
plugins=(... direnv)
#+end_src

I opted for the second.

* Configuration

After installing you can setup a ~.envrc~ file for each directory which defines which environment to use. I typically
use Python for my development and [[id:4bf1c297-d00a-4857-9339-8017c27138c6][Python Virtual Environments]] are managed using ~virtualenvwrapper~. As such my
environments live under ~${HOME}/.virtualenv/<env_name>~. We can activate the respective environment automatically in a
given directory by adding the following to ~.envrc~.

#+begin_src
export VIRTUAL_ENV=${HOME}/.virtualenvs/<env_name>
export PATH=${VIRTUAL_ENV}/bin:${PATH}
#+end_src

You now need to tell direnv to use this file on entering the directory, in essence activate direnv on this directory

#+begin_src
direnv allow .
#+end_src


** Extending

You can add functions globally to ~/.direnvrc~ which will be sourced and use the relevant environment variables you use
in each projects ~.envrc~.

* Emacs Integration

It is possible to integrate with [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]] using the [[https://github.com/wbolster/emacs-direnv][emacs-direnv]] package

#+begin_src elisp
(use-package direnv
  :config
  (direnv-mode))
#+end_src

...and that is it! Emacs will detect the presence of ~.envrc~ when you open a file within a directory and enable that
environment.

* Links

+ [[https://direnv.net/][direnv]]
+ [[https://github.com/wbolster/emacs-direnv][emacs-direnv]]


** Blog

+ [[https://erick.navarro.io/blog/activate-python-virtualenv-automatically-with-direnv/][Activate python virtualenv automatically with direnv]]
+ [[https://treyhunner.com/2024/10/switching-from-virtualenvwrapper-to-direnv-starship-and-uv/][Switching from virtualenvwrapper to direnv, Starship, and uv]]
+ [[https://joshthomas.dev/til/direnv/using-direnv-to-add-a-personal-gitignore-file-to-repos/][Using direnv to add a personal `.gitignore` file to repos]]
