:PROPERTIES:
:ID:       04868965-8413-4d9d-8ecc-573570fec5b1
:mtime:    20230103103308 20220908194217
:ctime:    20220908194217
:END:
#+TITLE: LSP Mode
#+DATE: [2022-02-15 Tue 13:21]
#+FILETAGS: :emacs:programming:ide:

Emacs supports [[https://emacs-lsp.github.io/lsp-mode/][Language Server Protocol]] for a range of languages. This is a modularised way in which editors can be
turned into [[https://en.wikipedia.org/wiki/Integrated_development_environment][Integrated Development Environments (IDEs)]] where by code is automatically linted, functions options are
displayed whilst typing, variables can be renamed throughout who classes/packages and debugging is supported.

A multitude of [[https://emacs-lsp.github.io/lsp-mode/page/languages/][languages]] are supported under Emacs but the official documentation isn't always clear on how to setup and
configure these. Typically there are two components to setting up and configuring support for a given language.

1. The backend language server.
2. The Emacs lsp module to communicate with the backend.

* Bash

Support for Bash comes via the [[https://github.com/bash-lsp/bash-language-server][bash-language-server]], whilst support in Emacs is built-in to LSP-mode.

#+BEGIN_SRC bash
  npm install -g bash-language-server
#+END_SRC

To enable support ensure that you have a hook defined, at a bare minimum.

#+BEGIN_SRC elisp
  (use-package lsp-mode
    :commands lsp
    :hook
    (sh-mode . lsp))
#+END_SRC

* LaTeX

There are several options for [[id:e1c2cfef-1b43-47a8-a425-94e6ae58d917][LaTeX]] support, perhaps the most generic is provided by [[https://valentjn.github.io/ltex/index.html][LTeX]] which not only supports LaTeX
but also other languages such as [[id:0c371287-128d-4e46-8128-b2d4f5fc604c][Markdown]], [[id:169b9c5f-df34-46ab-b64f-8ee98946ee69][Org]], [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] reStructured Text, [[id:de9a18a7-b4ef-4a9f-ac99-68f3c76488e5][R]] Sweave and XHTML documents.

[[https://github.com/emacs-languagetool/lsp-ltex][lsp-ltex]] is the package to install to provide LTeX support via the Language Server Protocol, but you have to download
and install LTeX for instructions see [[https://valentjn.github.io/ltex/ltex-ls/installation.html][here]], but the package itself provides the command ~lsp-ltex-upgrade-ls~ and if the
LTeX server is not installed it will install it for you. You can configure ~lsp-ltex~ via ~use-package~ as shown below.

#+BEGIN_SRC elisp
  (use-package lsp-ltex
  :ensure t
  :hook (text-mode . (lambda ()
                       (require 'lsp-ltex)
                       (lsp))))
#+END_SRC
* Markdown

Support for Markdown was tricky to setup, the LSP Mode page points to a depricated ~unified-language-server~ instead
advising to use [[https://github.com/remarkjs/remark-language-server][remark-language-server]]. Installation is simple.

#+BEGIN_SRC bash
  npm install remark-language-server
#+END_SRC

Configuring Emacs LSP Mode to use this, less so and for the time being I've fallen back on just using the excellent
[[https://jblevins.org/projects/markdown-mode/][Markdown Mode for Emacs]].

* Python

There are multiple options available for [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] but because I'd used [[https://jedi.readthedocs.io/en/latest/][Jedi]], an autcompletion, static analysis and
refactoring library for Python, previously I opted for the [[https://github.com/pappasam/jedi-language-server][jedi-language-server]]. Under your default Virtual Environment
you need to install the language server.

#+BEGIN_SRC bash
  pip install -U jedi-language-server
#+END_SRC

In Emacs you need to install and configure [[https://github.com/fredcamps/lsp-jedi][lsp-jedi]].

#+BEGIN_SRC elisp
  (use-package lsp-jedi
  :ensure t
  :config
  (with-eval-after-load "lsp-mode"
    (add-to-list 'lsp-disabled-clients 'pyls)
    (add-to-list 'lsp-enabled-clients 'jedi)))
#+END_SRC

* Treemacs

* LSP UI

[[https://github.com/emacs-lsp/lsp-ui][LSP UI]] provides User Interface integration to LSP mode which means you can get fancy pop-ups showing you options for
different things. My configuration is below.

#+BEGIN_SRC elisp
  (use-package lsp-ui
  :ensure t
  :defer t
  :config
  (setq lsp-ui-doc-delay 1
	    lsp-ui-doc-enable t
	    lsp-ui-doc-header nil
        lsp-ui-doc-use-childframe t
        lsp-ui-doc-position 'top
        lsp-ui-doc-include-signature t
        lsp-ui-doc-use-childframe t
        lsp-ui-sideline-enable nil
        lsp-ui-flycheck-enable t
        lsp-ui-flycheck-list-position 'right
        lsp-ui-flycheck-live-reporting t
        lsp-ui-peek-enable t
        lsp-ui-peek-list-width 60
        lsp-ui-peek-peek-height 25
        lsp-ui-sideline-enable t
        lsp-ui-sideline-show-hover t
        lsp-ui-sideline-delay 3)
  :hook (lsp-mode . lsp-ui-mode)
  :bind (:map lsp-ui-mode-map
	          ("C-c i" . lsp-ui-imenu)))
#+END_SRC


* Full configuration

My current configuration for LSP mode can be found at [[https://gitlab.com/nshephard/emacs/-/blob/master/settings/lsp-settings.el][lsp-settings.el]]. The Python side of things is heavily based on that of [[ https://gitlab.com/nathanfurnal/dotemacs/-/snippets/2060535][Nathan
Furnal's Emacs Python Config]]. A copy of that is provided here for convenience but its a snap shot and things change so
check the source linked above for the most up-to-date.



* Links
+ [[https://emacs-lsp.github.io/lsp-mode/][LSP Mode - Language Server Protocol support for Emacs]]

** Language Servers
+ [[https://github.com/bash-lsp/bash-language-server][bash-language-server]]
+ [[https://valentjn.github.io/ltex/index.html][LTeX]]
+ [[https://github.com/pappasam/jedi-language-server][jedi-language-server]]
+ [[https://github.com/remarkjs/remark-language-server][remark-language-server]]

** LSP Mode Modules
+ [[https://github.com/fredcamps/lsp-jedi][lsp-jedi]]
+ [[https://github.com/non-Jedi/lsp-julia][lsp-julia]]
