:PROPERTIES:
:ID:       0a7fbe90-1f6e-4a38-a0c8-b378b1893f33
:mtime:    20240118164111 20240116122241 20240107125102 20231218231936 20231217220611 20231217163005 20231208200545 20231106165640 20231029193938 20231010204450 20230922120216 20230916065434 20230915202700 20230910203044
:ctime:    20230910203044
:END:
#+TITLE: Mastodon
#+FILETAGS: :mastodon:rss:

Mastodon is federated software and part of the [[id:8178219c-ef79-4b59-ad51-e4204a8f369c][Fediverse]] a decentralised network of servers for different services.

* Tips

** RSS feed

Its pretty simple to get and RSS feed of an account, just add ~.rss~ to the end of the URL.

An example of embedding Mastodon feeds on your site you can use [[https://github.com/sampsyo/emfed][emfed]].

An excellent service is available via [[https://rss-parrot.net/][RSS Parrot]] which allows you to toot ~@birb@rss-parrot.net~ with a URL for a site
with RSS feeds. It will then look up the RSS or Atom feed of the site automatically and set up an account that
automatically toots new RSS posts. It replies to you with the account details and you can follow them to stay abreast of
the RSS feed directly in Mastodon.

Since this is a Mastodon instance you can also view the account itself, e.g. I have setup...

+ [[https://rss-parrot.net/web/feeds/www.flickr.com.photos.slackline][@www.flickr.com.photos.slackline@rss-parrot.net]] for my Flickr feed.
+ [[https://rss-parrot.net/web/feeds/rse.shef.ac.uk][@rse.shef.ac.uk@rss-parrot.net]] for [[https://rse.shef.ac.uk][RSE Sheffield]] feed.

This is a really neat feature, it works for anything with RSS feeds, e.g. YouTube channels, SoundCloud accounts (if
configured to include RSS feeds, not all are). Services such as [[https://fetchrss.com/][FetchRSS]] can generate RSS feeds for any website or
service.

* Server Setup

I have a VPS (I use [[https://ovh.co.uk][OVH]]) and figured I could just
host my own. My VPS runs [[https://archlinux.org][Arch Linux]] and there
is a package for [[https://aur.archlinux.org/packages/mastodon][Mastodon
on AUR]]appear

#+begin_src sh
$ cd ~
$ git clone https://aur.archlinux.org/mastodon.git
$ cd mastodon
$ makepkg -sri
<<< enter password >>>
#+end_src

Ok installed but unfortunately the
[[https://wiki.archlinux.org/title/Mastodon][promised post-install
message]] didn't appear. So lets read the
[[https://docs.joinmastodon.org/admin/prerequisites/][official
documentation]] which recommends three things...

1. Only allowing SSH key-based login (I already have this configured).
2. Installing
   [[https://www.fail2ban.org/wiki/index.php/Main_Page][fail2ban]] to
   block repeated logins.
3. Install a firewall and only allow SSH, HTTP and HTTPS ports

** SSH key-based login

I took some steps to
[[https://kimura.no-ip.info/doku.php?id=linux:security:ssh#ssh_hardening][harden
my SSH login]] some time ago. They are minor but make a small
difference. In ~/etc/ssh/sshd.config~ change the following...

#+begin_src sh
PermitRootLogin no
Port <insert-port-number>
PasswordAuthentication no
#+end_src

Note however that before changing ~PasswordAuthentication~ to ~no~ you
*MUST* upload your public SSH key to your account on your VPS otherwise
you will lock yourself out.

#+begin_src sh
rsync -av ~/.ssh/<keyname>.pub <username>@<vps-server-name|ip-address>:~/.ssh/.
#+end_src

You should now be able to login using your SSH key and its even easier
if you use [[linux:security:ssh#public_key_generation|keychain]].

** fail2ban

Under Arch Linux install with the following (as ~root~)...

#+begin_src sh
# pacman -Syu fail2ban
#+end_src

As per instructions you could add the following to
~/etc/fail2ban/jail.local~.

#+begin_src sh
  [DEFAULT] destemail = your@email.here sendername = Fail2Ban

  [sshd] enabled = true port = 22

  [sshd-ddos] enabled = true port = 22
#+end_src

However, I don't...

1. Want lots of emails telling me about failed login attempts (like anyone is ever going to read what I write here!).
2. Don't run ~sshd~ on port ~22~ and instead use some other random port to reduce exposure to attacks (not perfect but
   its one simple step to take).

For obvious reasons I'm not posting what I have entered here and you should interpolate your own values for the relevant
fields. Once you have configured ~fail2ban~ appropriately you can enable/restart the service.

#+begin_src sh
  systemctl enable --now fail2ban.service
#+end_src

** Firewall, SSH and HTTPS (not HTTP)

I've already configured [[https://nginx.org/en/][nginx]] which I use for serving the sites I host on my VPS to redirect ~http~ requests on port 80
to ~https~ on port 443 and use [[https://certbot.eff.org/][certbot]] to provide valid certificates. I'm not going to allow any firewall to allow
~http~ connections then. As mentioned above I configure ~sshd~ to run on a port other than ~22~. To which end my
installation of ~iptables~ is somewhat different from the recommended.

*TODO* Finish off.

* On keeping things open

An interesting piece on why Farcebooks entry into the Fediverse is dangerous is here. Its possible to block all of
"threads" as tooted by Mastodon developer, see [[https://mastodon.social/@Gargron/111587088958531028][@Gargon@mastodon.social]] ...

#+begin_quote
If for whatever reason you never wish to interact with #Threads, you can personally block it for your account. This
hides all posts and profiles from Threads, prevents anyone from Threads from following you, and stops your posts from
being delivered to or fetched by Threads. Simply click the "Block domain threads.net" option on any Threads profile or
post you see in Mastodon.
#+end_quote

It is galling that Meta/Threads think that the simple act of interacting with users on their instances means that they
can [[https://fosstodon.org/@mastodonmigration@mastodon.online/111585528277307543][harvest all your data]], although a counter point is that they can [[https://rknight.me/meta-doesnt-need-activitypub-to-slurp-up-your-data/][already get to what they want]].

A list of servers and their status with regards to [[https://fedipact.veganism.social][blocking threads]].


* Discourse

A great piece of forum software is Discourse, they have as of 2023-11-09 integrated support for Fediverse (see [[https://meta.discourse.org/t/activitypub-plugin/266794/116][post]] and
[[https://socialhub.activitypub.rocks/t/are-you-running-your-own-discourse-community-for-your-software-lets-federate/3757][more info]]).

* Links

** About

+ [[https://fedi.tips/][Fedi.Tips -- An Unofficial Guide to Mastodon and the Fediverse]]
+ [[https://simonwillison.net/2022/Nov/5/mastodon/][It looks like I'm moving to Mastodon]]
+ [[https://blog.djnavarro.net/posts/2022-11-03_what-i-know-about-mastodon/][Notes from a data witch - Everything I know about Mastodon]]

** Switching

+ [[https://fedifinder.glitch.me/][Fedifinder]] Find Fediverse accounts of your Twitter followings
+ [[https://twitodon.com/][Twitodon - Find your Twitter friends on Mastodon]]
+ [[https://www.movetodon.org/][movetodon.org]]
+ [[https://pruvisto.org/debirdify/][Debirdify]]
+ [[https://axbom.com/mastodon-tips/][10 quick Mastodon tips]]

** Emacs

+ [[https://emacs.ch][emacs.ch]]
+ [[https://codeberg.org/martianh/mastodon.el][martianh/mastodon.el: Emacs client for Mastodon]]
+ [[https://sachachua.com/dotemacs/index.html#mastodon][Sacha Chua - Mastodon Config]]
+ [[https://gist.github.com/rougier/e92d446600dfe350b9ec9d7cabaca211][A different timeline layout for the Emacs mastond client]]

** Verification

+ [[https://keyoxide.org/][KeyOxide]]

** Servers

+ [[https://joinmastodon.org/servers][Servers - Mastodon]]
+ [[https://mastodon.social][mastodon.social]]
+ [[https://fosstodon.org][fosstodon.org]]
+ [[https://pixelfed.social/][pixelfed.social]]

+ [[https://phanpy.social/][phanpy.social]] a nice layer over the top of standard Mastodon.

*** Hosting

+ [[https://masto.host/][masto.host]]
+ [[https://growyourown.services/grow-your-own-social-network/][GrowYourOwnServices]]


** HowTo

+ [[https://blog.maartenballiauw.be/post/2022/11/05/mastodon-own-donain-without-hosting-server.html][Mastodon on your own domain without hosting a server - Maarten Balliauw {blog}]]
+ [[https://rossabaker.com/projects/webfinger/][Ross A. Baker: WebFinger]]
+ [[https://www.stevencanplan.com/2022/12/automatically-post-your-flickr-photos-to-your-mastodon-account/][Automatically post your Flickr photos to your Mastodon account – Steven Can Plan]]
+ [[https://cosimameyer.com/post/2023-04-25-building-mastodon-bots-and-promoting-the-community/][Building Mastodon Bots and Promoting the Community - Part 1]]
+ [[https://cosimameyer.com/post/2023-09-17-building-mastodon-bots-and-promoting-the-community-part-2/][Building Mastodon Bots and Promoting the Community - Part 2]]

** Technical

+ [[https://dramsch.net/today-i-learned/social-media/mastodon-user-post-timeline/][Mastodon User Timelines are RSS Feeds | Real-world Machine Learning]]
+ [[https://www.bentasker.co.uk/posts/blog/software-development/writing-a-simple-mastodon-bot-to-submit-rss-items.html][Writing A Simple RSS To Mastodon Bot | www.bentasker.co.uk]]
+ [[https://dev.to/contentful/create-a-bot-with-rss-and-webhooks-for-mastodon-a-twitter-alternative-l4o][Create a bot with RSS and webhooks for Mastodon, a Twitter alternative - DEV Community]]
+ [[https://thibaultmilan.com/blog/2022/12/20/how-to-create-a-rss-feed-bot-for-mastodon/][How to create a RSS feed bot for Mastodon – Thibault Milan]] - This was the most simple solution I've come across and
  the one I've used!
+ [[https://www.softwolves.com/wolfblog/2023/12/18/adding-a-mastodon-feed-to-a-static-html-site/][Adding a Mastodon feed to a static HTML site]]

** Academic

+ [[https://truesciphi.org/][TrueSciPhi]]
+ [[https://nathanlesage.github.io/academics-on-mastodon/][Academics on Mastodon]]
+ [[https://docs.google.com/document/d/1TTtXbf0yDXHKXwR9jpZ4kU79mmiZT5KIM7U4tBr83hY/edit#][Mastodon Media List]]

** Misc

+ [[https://denise.dreamwidth.org/91757.html][A guide to potential liability pitfalls for people running a Mastodon instance]]
+ [[https://mastometrics.com/][MastoMetrics - Analytics for Mastodon]]
+ [[https://whomtofollow.com/][Whom to Follow | Find New Fediverse Accounts]]
+ [[https://followgraph.vercel.app/][Followgraph on Mastodon]]

** RSS Feeds

+ [[https://mstdn.social/@feditips/108357998963885456][Most accounts are accessible via RSS with .rss at the end of the URL]]
+ [[https://mastodon.social/@ifixcoinops/109288684615075785][Add .rss to the end of most pages you see on a Mastodon server to get an RSS feed for your RSS reader.]]
+ [[https://thibaultmilan.com/blog/2022/12/20/how-to-create-a-rss-feed-bot-for-mastodon/][How to create a RSS feed bot for Mastodon – Thibault Milan]]
+ [[https://blog.khinsen.net/posts/2023/10/09/deconstructing-the-mastodon-client/][Deconstructing the Mastodon client]] - covers the broad principles (with links) for creating RSS feeds to read from
  Mastodon.
+ [[https://codeberg.org/aliceice/fedi-marss/][Fedi-MaRRS]] Emacs Lisp implementation of the above.
+ [[https://rss-parrot.net/web/about][@birb@rss-parrot.net]]
