:PROPERTIES:
:ID:       bc06ad82-f80e-4436-8ef4-7f58f73d29eb
:mtime:    20250916084632
:ctime:    20250916084632
:END:
#+TITLE: Mastodon RSS
#+FILETAGS: :mastodon:rss:

* Mastodon accounts are RSS feeds!

Its pretty simple to get and RSS feed of an account, just add ~.rss~ to the end of the URL.

* Embedding Mastodon RSS feeds

An example of embedding Mastodon feeds on your site you can use [[https://github.com/sampsyo/emfed][emfed]].

* Posting RSS feeds to your account

The easiest way to include RSS feeds in your account is to leverage [[https://mastofeed.org/][mastofeed.org]]. Simply sign in using your Mastodon
account, add a link to the RSS feed you want to be automatically tooted. By default it is inactive so Activate it and
save the changes, you can then configure how posts appear, save those changes and your good to go.

If you wish to post content from WordPress sites you can find [[https://www.wpbeginner.com/wp-tutorials/how-to-make-separate-rss-feed-for-each-category-in-wordpress/][content specific feeds]] to narrow down what is posting.

Another option is the very early beta [[https://feedsin.space/][feedsin.space]].

* Following RSS feeds

An excellent service is available via [[https://rss-parrot.net/][RSS Parrot]] which allows you to toot ~@birb@rss-parrot.net~ with a URL for a site
with RSS feeds. It will then look up the RSS or Atom feed of the site automatically and set up an account that
automatically toots new RSS posts. It replies to you with the account details and you can follow them to stay abreast of
the RSS feed directly in Mastodon.

Since this is a Mastodon instance you can also view the account itself, e.g. I have setup...

+ [[https://rss-parrot.net/web/feeds/www.flickr.com.photos.slackline][@www.flickr.com.photos.slackline@rss-parrot.net]] for my Flickr feed.
+ [[https://rss-parrot.net/web/feeds/rse.shef.ac.uk][@rse.shef.ac.uk@rss-parrot.net]] for [[https://rse.shef.ac.uk][RSE Sheffield]] feed.

This is a really neat feature, it works for anything with RSS feeds, e.g. YouTube channels, SoundCloud accounts (if
configured to include RSS feeds, not all are). Services such as [[https://fetchrss.com/][FetchRSS]] can generate RSS feeds for any website or
service.

* Linking Across Services

You can use [[https://fed.brid.gy/docs][Bridgy Fed]], a decentralised social network bridge to connect the fediverse, web and things like Bluesky.

Found a [[https://gist.github.com/vwillcox/956bc5056f46d152b2650ba78053ef5e][gist]] that purportedly makes cross-posting across BlueSky and Mastodon easy.

* Links


+ [[https://mstdn.social/@feditips/108357998963885456][Most accounts are accessible via RSS with .rss at the end of the URL]]
+ [[https://mastodon.social/@ifixcoinops/109288684615075785][Add .rss to the end of most pages you see on a Mastodon server to get an RSS feed for your RSS reader.]]
+ [[https://thibaultmilan.com/blog/2022/12/20/how-to-create-a-rss-feed-bot-for-mastodon/][How to create a RSS feed bot for Mastodon – Thibault Milan]]
+ [[https://blog.khinsen.net/posts/2023/10/09/deconstructing-the-mastodon-client/][Deconstructing the Mastodon client]] - covers the broad principles (with links) for creating RSS feeds to read from
  Mastodon.
+ [[https://codeberg.org/aliceice/fedi-marss/][Fedi-MaRRS]] Emacs Lisp implementation of the above.
+ [[https://rss-parrot.net/web/about][@birb@rss-parrot.net]]
+ [[https://mastofeed.org/][MastoFeed - Send your RSS Feeds to Mastodon]]
