:PROPERTIES:
:ID:       9f1ba60e-a255-46ef-ba40-6410b4a89d1d
:END:
#+TITLE: Nginx AI Sabotage
#+FILETAGS: :linux:nginx:ai:

I wanted to block AI bots on my self-hosted sites. Originally I came across [[https://rknight.me/blog/blocking-bots-with-nginx/][Blocking Bots with Nginx by Robb Knight]] this was pretty
straight-forward. Over time more options have become available, some are listed below but a more permanent record is
available at [[https://algorithmic-sabotage.gitlab.io/asrg/sabot-in-the-age-of-ai/][Sabot in the Age of AI - ASRG]].


* Blocking Bots with Nginx

I didn't have the same strict requirements as the author of the article so I created
~/etc/nginx/redirect.conf~  and added to it the following entry which is case-insensitive list of AI Bot names from
[[https://github.com/ai-robots-txt/ai.robots.txt/blob/main/robots.txt][here]].

#+begin_src
# List from https://github.com/ai-robots-txt/ai.robots.txt/blob/main/robots.txt
if ($http_user_agent ~* "(AI2Bot|Ai2Bot-Dolma|Amazonbot|anthropic-ai|Applebot|Applebot-Extended|Bytespider|CCBot|ChatGPT-User|Claude-Web|ClaudeBot|cohere-ai|Diffbot|DuckAssistBot|FacebookBot|facebookexternalhit|FriendlyCrawler|Google-Extended|GoogleOther|GoogleOther-Image|GoogleOther-Video|GPTBot|iaskspider/2.0|ICC-Crawler|ImagesiftBot|img2dataset|ISSCyberRiskCrawler|Kangaroo Bot|Meta-ExternalAgent|Meta-ExternalFetcher|OAI-SearchBot|omgili|omgilibot|PerplexityBot|PetalBot|Scrapy|Sidetrade indexer bot|Timpibot|VelenPublicWebCrawler|Webzio-Extended|YouBot)"){
    return 307 https://ash-speed.hetzner.com/10GB.bin;
}
#+end_src


Any bot that matches the above "user agent" will get redirected to ~https://ash-speed.hetzner.com/10GB.bin~.

For each ~server{...}~ entry under ~/etc/nginx/nginx.conf~ I then added the following line to include the above file.

#+begin_src
    include /etc/nginx/redirect.conf
#+end_src


Restart the server and test by changing the "user agent" in any browser to one that matches the above and I was asked if
I wanted to download a ~10GB.bin~ file.

* Serve AI Bots Junk

Came across [[https://zadzmo.org/code/nepenthes/][Nepenthes]] which infinitely generates junk pages when web-crawlers hit it. Not yet deployed this.

This isn't the only approach its possible [[https://tzovar.as/algorithmic-sabotage-ii/][Algorithmic sabotage for static sites II: Images]] too.

* Codeberg/GitHub static stites

You can also serve up junk on static sites that are hosted on Codeberg/GitHub pages using the approach described in
[[\[\[https://tzovar.as/algorithmic-sabotage-ssg/\]\[Bastian Greshake Tzovaras · Algorithmic sabotage for static
sites\]\]][Algorithmic sabotage for static sites]]. It uses the [[https://marcusb.org/hacks/quixotic.html][Quix[]otic]] tool to achieve this.

* Iocaine

A great [[https://vulpinecitrus.info/blog/guarding-git-forge-ai-scrapers/][article]] ([[https://web.archive.org/web/20251212132351/https://vulpinecitrus.info/blog/guarding-git-forge-ai-scrapers/][archive copy]]) showing how to use [[https://iocaine.madhouse-project.org/documentation/3/][Iocaine3]] to serve garbage to crawlers using Nginx for reverse proxying.

* Science is Poetry

A [[https://julianoliver.com/projects/science-is-poetry/][project by Julian Over]] to provide random nonsense to AI web-crawlers. I need to work out how to add a link to this in
the header of all self-hosted services.

* Poison Fountain

[[https://rnsaffn.com/poison3/][Poison Fountain]] is another attempt to feed AI web-crawlers a bunch of junk (see also [[https://www.theregister.com/2026/01/11/industry_insiders_seek_to_poison/][Register article]]).

* AI Scraping

The article [[https://blog.includesecurity.com/2026/06/the-smart-tv-in-your-livingroom-is-a-node-in-the-aiscraping-economy/][The Smart TV in Your LivingRoom Is a Node in the AIScraping Economy]] describes how an SDK is used in mobile
apps and "smart" TVs to act as scrapers for companies.

Adding the following to block lists prevents them

#+BEGIN_EXAMPLE
proxyjs.brdtnet.com
proxyjs.luminatinet.com
proxyjs.bright-sdk.com
clientsdk.bright-sdk.com
clientsdk.brdtnet.com

#+END_EXAMPLE


* ~human.json~

[[https://codeberg.org/robida/human.json][human.json]] is a meta-data specification for declaring your site is made by humans. Drop a simple ~human.json~ into your
website, link to it from a page and you're done. You can "vouch" for other websites which you know are also made by
humans. Simple, neat idea.

* Links

+ [[https://algorithmic-sabotage.gitlab.io/asrg/sabot-in-the-age-of-ai/][Sabot in the Age of AI]]
+ [[https://julianoliver.com/projects/science-is-poetry/][julian oliver/projects/science-is-poetry/]] ([[https://mastodon.social/@JulianOliver/116391284280771352][thread]] )
+ [[https://www.nature.com/articles/d41586-026-01689-0][Bots are scraping open data — how should researchers respond?]]

** Research

+ [[https://arxiv.org/abs/2510.07192][[2510.07192] Poisoning Attacks on LLMs Require a Near-constant Number of Poison Samples]]
