:PROPERTIES:
:ID:       3774439d-af75-453e-b3e9-9d578b6bec46
:mtime:    20251212133522 20250626215633 20250622203534 20250622162759 20250603081658 20250403122443 20250328170850 20250223131954 20250208103833 20250206173224 20250206100320 20241128103141 20241117170240 20241114174544 20230911222107 20230528222513 20230215120711
:ctime:    20230215120711
:END:
#+TITLE: Nginx
#+FILETAGS: :gnu:linux:nginx:web:

* Installation

Available across packages install as appropriate to your OS.

#+begin_src bash
  emerge -av nginx        # Gentoo
  pacman -Syu nginx       # Arch
  apt-get install nginx   # Ubuntu
#+end_src


* Configuration

** General


*** Block "AI" Bots

Now expanded to its own [[id:9f1ba60e-a255-46ef-ba40-6410b4a89d1d][sabotage]] page.

** LetsEncrypt

I use LetsEncrypt to provide certificates for my sites so they are secure. Using Nginx when renewing remember to include
the ~--nginx~ flag.

#+begin_src
certbot --nginx renew
#+end_src

A useful tool for debugging why certificate issue may fail is [[https://letsdebug.net/][Let's Debug]]

In 2025 LetsEncrypt started [[https://community.letsencrypt.org/t/getting-ready-to-issue-ip-address-certificates/][issuing certificates for IP addresses]] which is really useful for those seeking to encourage
adoption of the [[https://ar.al/2025/06/25/web-numbers/][SmallWeb]].

* Servers

** [[https://wiki.nshephard.dev][Dokuwiki]]

I use [[id:bc096b27-5f0e-426c-9722-7798e12ca2dc][Dokuwiki]] to host a couple of wiki's as its simple and doesn't require a database.

** [[https://freshrss.nshephard.dev][FreshRSS]]

** [[https://opengist.nshephard.dev][OpenGist]]

This runs locally and uses a reverse proxy to connect to it from the outside world. It plays nicely with ForgeJo and
allows used of its login options.

** [[https://forgejo.nshephard.dev][Forgejo]]

** [[id:d9c960c2-71b6-45e6-b388-dcd07b9da3e1][FitTrackee]]

** [[https://owntracks.nshephard.dev][OwnTracks]]

I setup my own [[id:5315e7ee-0ed9-4514-b1a9-0a03114d8191][owntracks]] instance.

** Wordpress

I also (used to) host a Wordpress site with the intention of monetising my photography. Never got a single sale one day
I might update the installation and get it working again.



* Links

+ [[https://nginx.org/en/docs/][nginx docs]]

** Website Analysis

+ [[https://web-check.xyz/][webcheck.xyz]]
+ [[https://plausible.io/][Plausible]]
+ [[https://www.hitsteps.com/][Hitsteps]]
+ [[https://heapanalytics.com][Heap]]

** Blocking Bots

+ [[https://rknight.me/blog/blocking-bots-with-nginx/][Blocking Bots with Nginx • Robb Knight]]

** Search

+ [[https://pagefind.app/][Pagefind | Pagefind — Static low-bandwidth search at scale]]
