:PROPERTIES:
:ID:       5249c437-1ff7-4925-937d-9e9c42256ef1
:mtime:    20241215075449
:ctime:    20241215075449
:END:
#+TITLE: NixOS - Installation
#+FILETAGS: :nixos:linux:installation:


The [[https://nixos.org/manual/nixos/stable/#sec-booting-from-usb][installation]] requires creating a bootable USB, there are two [[https://nixos.org/download/#nixos-iso][options]] a a Graphical ISO image (with GNOME or
Plasma Desktop to choose between) or a Minimal ISO image that uses the console. I opted for the later.

Once downloaded you need to copy the ISO to a USB drive. Tweak the following to reflect the location you have saved the
~.iso~ to and the device your USB drive is detected as (use ~dmesg | tail~ after inserting the USB or ~lsblk~ to list
the available devices and compare to your ~/etc/fstab~ you don't want to get the target device wrong as it could wipe
your installation!)

#+begin_src sh
dd bs=4M conv=fsync oflag=direct status=progress if=/path/to/nixos-minimal-24.11.710650.e2605d0744c2-x86_64-linux.iso of=/dev/sd<#>
#+end_src

* Boot NixOS

Depends on your computers BIOS settings but insert the USB drive and enable booting from the USB drive.

* Partitioning

I'm familiar with ~cfdisk~ having used it over the years when installing various [[id:88fc1e91-d928-485e-83b4-1991663fa267][GNU/Linux]] operating systems such as
[[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] and more recently [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] so opted to use that to partition my hard drive. I have a 1TB drive and opted to
create four physical partitions with a separate ~/home/~ partition and despite having 32GB of RAM opted for an 8GB swap
partition.

| Partition   | Label   | Size |
|-------------+---------+------|
| ~/dev/sda1~ | ~boot~  | 512M |
| ~/dev/sda2~ | ~nixos~ | 100G |
| ~/dev/sda3~ | ~swap~  | 8G   |
| ~/dev/sda4~ | ~home~  | 832G |

* Formatting Filesystems

I opted to go with the reliable ~ext4~ file system.

#+begin_src sh
mkfs.ext4 -L nixos /dev/sda2
mkfs.ext4 -L home /dev/sda4
mkfs.fat -F 32 -n boot /dev/sda1
mkswap -L swap /dev/sda3
#+end_src

* Install

Once partitions had been formatted the next step, as with any other boot-strap installation, is you need to mount the
partitions to perform the installation, although unlike [[id:44b32b4e-1bef-49eb-b53c-86d9129cb29a][Gentoo]] and [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] you don't have to ~chroot~ into the
environment.

#+begin_src sh
mount /dev/disk/by-label/nixos /mnt/
mkdir /mnt/{boot,home}
mount -o umask=077 /dev/disk/by-label/boot /mnt/boot
mount /dev/disk/by-label/home /mnt/home
swapon /dev/disk/by-label/swap
#+end_src

Of course you could use the partitions you created rather than the labels...

#+begin_src sh
mount /dev/sda2 /mnt/
mkdir /mnt/{boot,home}
mount -o umask=077 /dev/sda1 /mnt/boot
mount /dev/sda4 /mnt/home
swapon /dev/sda3
#+end_src

* Generate ~configuration.nix~

Being a declarative operating system a file is required that declares all of your desired options and preferences.

This is created using ~nixos-generate-config~ and requires an option saying where the ~--root~ of the system should be
(in this case where the disk labelled ~nixos~ has been mounted).

#+begin_src sh
nixos-generate-config --root /mnt
#+end_src

* Configure the System

You can now edit the generated ~/mnt/etc/nixos/configuration.nix~ using ~nano~.

#+begin_src sh
nano /mnt/etc/nixos/configuration.nix
#+end_src

It is very well commented and many fields are already uncommented. I changed and the values of some to leave myself with
the following...

#+begin_src
{ config, lib, pkgs, ...}:

{
  imports =
    [ # Include the results of the hardware scan
      ./hardware-configuration.nix
    ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  networking.hostname = "crow";
  networking.networkmanager.enable = true;
  time.timeZone = "Europe/London";
  i18n.defaultLocale = "en_GB.UTF-8";
  services.xserver.enable = true;
  services.xserver.xkb.layout = "gb";
  service.pipewire = {
    enable = true;
    pulse.enable = true;
  };
  services.libinpu = true;
  users.users.username = {
    isNormalUser = true;
    packages = with pkgs; [
      tree
    ];
  };
  programs.firefox.enable = true;
  environment.systemPackages = with pkgs; [
    emacs
    wget
  ];
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };
  services.openssh.enable = true;
  system.stateVersion = "24.11";
}
#+end_src

Save the file and exit (in ~nano~ this is ~C-o Enter~ then ~C-x~).

* Install the System

To install the system its

#+begin_src sh
nixos-install
#+end_src

At the end of the process you are prompted to set a ~root~ password. And if you have configured a user account you can
set the password for that account with...

#+begin_src sh
nixos-enter --root /mnt -c 'passwd username'
#+end_src

* Reboot

Its then a simple case of rebooting.

#+begin_src sh
reboot
#+end_src


* Trouble Shooting

The system rebooted into a graphical user interface, but I was unable to login with either the account I created or the
~root~ account.  However switching to TTY1 with ~Ctrl-Alt-F1~ and I could login with my user account and ~sudo su~ to
root so I have a working system, although its not currently connected to the WiFi. To connect I repeated the steps from
the installation manual. Before doing anything else though I decided to reboot into the installation disk, reconnect to
Wifi so I could update my configuration to enable Flakes. Went round a few times in circles and ended up disabling
~NetworkManager~ from the configuration and enabling ~wpa_supplicant~ from the installation disk then rebooting and
ensuring that ~NetworkManager~ was disabled and configured and enabled [[https://nixos.wiki/wiki/Wpa_supplicant][~wpa_supplicant~]] from the new installation.

I took the time to enable Flakes at the same time (see next section) so I didn't had on less configuration in my history.

#+begin_src
networking.wireless = {
    enable = true;
    networks."my-network".psk = "somerandompassword";
    extraConfig = "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel";
}
networking.networkmanager.enable = false;
#+end_src

Restarting the service and I could connect \o/, I might have had to explicitly start the service, I can't remember, but
because the service was configured declaratively under ~/etc/nixos/configuration.nix~ I didn't have to use ~wpa_cli~ to
establish the connection as I did from the Live boot disk.

#+begin_src
sudo nixos-rebuild
sudo systemctl start wpa_supplicant
#+end_src

Because I enabled Flakes at the same time as switching to ~wpa_supplicant~ I could now check out templates with ~nix
flake show templates~, which brings us up-to-date with the need to introduce and understand Flakes
