:PROPERTIES:
:ID:       69291a6b-c253-44bc-ad9d-8d899bb90529
:mtime:    20241211115355 20241211103642 20241210065459 20240324205532 20240305091938 20240304160447
:ctime:    20240304160447
:END:
#+TITLE: NixOS
#+FILETAGS: :linux:unix:nixos:

* Installation

The [[https://nixos.org/manual/nixos/stable/#sec-booting-from-usb][installation]] requires creating a bootable USB, there are two [[https://nixos.org/download/#nixos-iso][options]] a a Graphical ISO image (with GNOME or
Plasma Desktop to choose between) or a Minimal ISO image that uses the console. I opted for the later.

Once downloaded you need to copy the ISO to a USB drive. Tweak the following to reflect the location you have saved the
~.iso~ to and the device your USB drive is detected as (use ~dmesg | tail~ after inserting the USB or ~lsblk~ to list
the available devices and compare to your ~/etc/fstab~ you don't want to get the target device wrong as it could wipe
your installation!)

#+begin_src sh
dd bs=4M conv=fsync oflag=direct status=progress if=/path/to/nixos-minimal-24.11.710650.e2605d0744c2-x86_64-linux.iso of=/dev/sd<#>
#+end_src

** Boot NixOS

Depends on your computers BIOS settings but insert the USB drive and enable booting from the USB drive.

* Links

** Documentation

+ [[https://nixos.org/manual/nix/stable/][Nix Reference Manual]]
+ [[https://wiki.nixos.org/wiki/NixOS_Wiki][NixOS Wiki]]

** Articles
+ [[https://economicsfromthetopdown.com/2024/02/17/nixing-technological-lock-in/][Nixing Technological Lock In – Economics from the Top Down]]
+ [[https://www.software.ac.uk/blog/reproducible-environments-nix][Reproducible Environments With Nix | Software Sustainability Institute]]
+ [[https://www.youtube.com/watch?v=cJJa0ztEVD8][NixOS: Pros and cons of truly reproducible builds - Ben Orchard - YouTube]]
+ [[https://nixos-and-flakes.thiscute.world/][NixOS & Flakes Book | Home Page]]

** Video

+ [[https://www.youtube.com/watch?v=CwfKlX3rA6E][NixOS: Everything Everywhere All At Once - YouTube]]
