:PROPERTIES:
:ID:       04cf68bf-0db2-403e-b0a6-9c94aa662577
:ROAM_ALIASES: "Open Research : Peer Review"
:END:
#+title: Open Research : Peer Review
#+filetags: :open-research:peer review:

An extension to reproducibility is peer review of code ensuring that code runs as described in other environments. This
can be facilitated by using containers such as Docker to provide reproducible environments.

* Peer Review

Just as traditional journals undertake peer review, the literate programming and code that underpins the analyses of a
piece of body of research can be peer reviewed. A pre-requisite is having access to the original data and code used to
prepare and analyse is and a first step would be to ensure that the results published can be faithfully reproduced from
the data and the code.

* CodeCheck / ReproHacks

Two useful initiatives that have been gaining traction in recent years are that of [[https://codecheck.org.uk/][CODECHECK]] and [[https://www.reprohack.org/][ReproHack]] which seek to
take published papers, or pre-prints, that have been written in an open-source framework where code and data is
available and check that the results can be reproduced.

* Links

+ [[https://i4replication.org/][Institute for Replication]]
+ [[https://pubpeer.com/][PubPeer - Search publications and join the conversation.]]
+ [[https://codecheck.org.uk/][CODECHECK]]
+ [[https://www.reprohack.org/paper/][ReproHack Hub]]
+ [[https://replicationnetwork.com/][The Replication Network | Furthering the Practice of Replication in Economics]]
+ [[https://www.itcrtraining.org/courses#h.ugabyqq1bigx][ITCR Courses]] includes two on reproducibility in Cancer Informatics
