:PROPERTIES:
:ID:       136364e7-1a6d-4b28-b284-0e415b860699
:ROAM-ALIASES: "Org Roam : Overview"
:mtime:    20250616211626 20250513083029 20250508122559 20240701060633 20231026121908 20231016222532 20230727234008 20230331110207 20230116172234 20230103103313 20221224191223 20230103103308
:ctime:    20221224191223
:END:
#+TITLE: Org-roam
#+FILETAGS: :orgroam:zettelkasten:org:

* Linking Nodes
:PROPERTIES:
  :ID:       e02fac30-1d8a-47ea-a91f-3c0b993ca2a3
:mtime:    20221224191223 20230103103311
:ctime:    20221224191223 20230103103311
  :END:

The power of the Zettelkasten approach comes from linking nodes. To achieve this in Org-roam the common keybinding
for doing so is ~C-c n i~ which is defined by

#BEGIN_SRC lisp :eval no
#END_SRC

Once defined you can insert a link to an existing node using the key sequence and then typing the name of the node (as
defined in the ~:ROAM ALIASES:~). If you want to manually insert a link then you can do so using ~C-c l~ (default for
inserting a link in Org-mode) and entering a node's ID prefixed with ~id:~ (e.g.
~id:136364e7-1a6d-4b28-b284-0e415b860699~) followed by the text you want to appear.

You can insert a node at any point (e.g. under a section heading) using ~C-c n o~.

* Templates
:PROPERTIES:
:ID:       904d2d18-37d6-47a1-b1c6-3bdb1cdd817d
:END:

Customising templates for capture Org-roam notes streamlines the process. The default is...

#+BEGIN_SRC elisp :eval no
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new (file+head "${slug}.org" "#+TITLE: ${title}\n")
      :unnarrowed t)))
#+END_SRC

...but we can prompt for additional information such as ~#+filetags:~ and ~:ROAM-ALIASES:~ if we want. The main
reference is the [[https://www.orgroam.com/manual.html#The-Templating-System][Templating System]]. The following will add a date/time stamp and prompt for tags to add the header
of the file...

#+BEGIN_SRC elisp :eval no
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new (file+head "${slug}.org" "#+TITLE: ${title}\n#+DATE: %U\n")
      :unnarrowed t)))
#+END_SRC

** Daily Captures
:PROPERTIES:
:mtime:    20230103103313 20221224191223
:ctime:    20221224191223
:END:

You may want to capture notes daily and process them, this can be done by customising the
~org-roam-dailies-capture-templates~. The example below saves to the directory defined by
~org-roam-dailies-directory~ which I have simply set to be ~org-roam/daily~.

#+BEGIN_SRC elisp
  (org-roam-dailies-capture-templates
   '(("d" "default" entry
   "* %?"
   :target (file+head "%<%Y-%m-%d%H%M%S>.org"
            "#+TITLE: %{title}\n#+DATE: %U\n"))))
#+END_SRC

This adds entries into the Org-roam db which may not be desirable, an alternative is to use a simple Org-capture template
to capture notes each day. The following template does this, but regardless one needs to be religious about writing up
notes or deleting them if not needed.

#+BEGIN_SRC elisp
  (setq org-capture-templates
   ("s" "Org-Roam Notes" entry (file "~/work/org-roam/20220206201656-notes.org")
   "
#+END_SRC


* Keeping up to Date
:PROPERTIES:
:ID:       68374984-d0f4-46de-8d3d-004fa9a82886
:mtime:    20221224191223
:ctime:    20221224191223
:END:

If you decide to delete files you can do so, but the references and links to them will persist in the database. To
rectify this you can use ~org-roam-db-sync~ to update the database by scanning all files (bound to ~C-n s~).

* Citations
:PROPERTIES:
:ID:       e3cd65be-e817-4820-94a7-502a7d668ae2
:END:

Org works with [[http://www.bibtex.org/][BibTeX]] citation files and Org-roam is no different, although it has several different ways in which it
can interact with your citations. Perhaps the most straight-forward is to use [[https://github.com/org-roam/org-roam-bibtex][org-roam-bibtex]] which integrates Org-roam
with [[https://github.com/jkitchin/org-ref][org-ref]] and the ~cite:~ that is built-in to Org-mode >9.5.

* Exporting Org-roam to Hugo

If you want to export your Org-roam to a static HTML site using [[https://gohugo.io/][Hugo]] (a static site generator) then you can and
thankfully someone took the time to write-up how to do so. See the post from [[https://sidhartharya.github.io/exporting-org-roam-notes-to-hugo/][Sidharth Arya - Exporting Org Roam notes to
hugo]].

* Org-roam UI

[[https://github.com/org-roam/org-roam-ui][Org-roam-ui]] is an excellent tool for visualising notes.

Currently running/exporting the site is not possible, although there is an example mentioned in RSE Slack of this being
[[https://ukrse.slack.com/archives/CDBHZCDQE/p1680256552958189][possible/in the pipeline]].

You can even add the [[id:e19b6eb6-46b2-440a-ba35-be29feb33407][GitHub Actions]] from [[https://github.com/ikoamu/publish-org-roam-ui][ikoamu/publish-org-roam-ui]] that will build and host your UI on GitHub Pages for
you.


* Links

** Reference

+ [[https://www.orgroam.com/manual.html#A-Brief-Introduction-to-the-Zettelkasten-Method][Org-roam User Manual]]

** Articles

+ [[https://lucidmanager.org/productivity/taking-notes-with-emacs-org-mode-and-org-roam/][Taking Notes with Emacs Org Mode and Org-Roam]]
+ [[https://blog.jethro.dev/posts/how_to_take_smart_notes_org/][How To Take Smart Notes With Org-mode · Jethro Kuan]]
+ [[https://jethrokuan.github.io/org-roam-guide/][How I Take Notes with Org-roam · Jethro Kuan]]
+ [[https://systemcrafters.net/build-a-second-brain-in-emacs/][Build a Second Brain in Emacs - System Crafters]]
+ [[https://www.eigenbahn.com/2021/09/15/org-roam][Graphing my External Brain with Org-Roam | Eigenbahn blog]] (includes deleting articles from the database)
+ [[https://honnef.co/articles/my-org-roam-workflows-for-taking-notes-and-writing-articles/][My org-roam workflows for taking notes and writing articles — Dominik Honnef]]

** Templates

+ [[https://systemcrafters.net/build-a-second-brain-in-emacs/capturing-notes-efficiently/][Capturing Notes Efficiently with Org Roam - System Crafters]]

** Zettelkasten

+ [[https://zenkit.com/en/blog/a-beginners-guide-to-the-zettelkasten-method/][A Beginner’s Guide to the Zettelkasten Method - Zenkit]]
+ [[https://nesslabs.com/thinking-in-maps][Thinking in maps: from the Lascaux caves to knowledge graphs]]
+ [[https://joonhyeokahn.substack.com/p/demystify-zettelkasten?r=18rf0p][Demystify Zettelkasten - Joonhyeok Ahn]]
+ [[https://feeei.substack.com/p/the-essence-of-the-zettelkasten-method][The essence of the Zettelkasten method, demystified.]]

** Alternatives

+ [[https://logseq.com/][logseq]]
+ [[https://obsidian.md/][Obsidian]]
+ [[https://xwmx.github.io/nb][nb]] / [[https://github.com/xwmx/nb][nb (GitHub)]]

*** Boards for drawing notes

+ [[https://excalidraw.com/][Excalidraw]] ([[https://github.com/excalidraw/excalidraw][excalidraw/excalidraw]]) : Virtual whiteboard for sketching hand-drawn like diagrams

** PARA Method

+ [[https://fortelabs.com/blog/para/][The PARA Method: The Simple System for Organizing Your Digital Life in Seconds]]
+ [[https://whhone.com/posts/para-org-mode/][Implementing the PARA Method in Org-mode - Wai Hon's Blog]]
