:PROPERTIES:
:ID:       5315e7ee-0ed9-4514-b1a9-0a03114d8191
:mtime:    20250524134848 20250504065636 20250330091626 20250329110559 20250329095813 20250328170851
:ctime:    20250328170851
:END:
#+TITLE: OwnTracks
#+FILETAGS: :linux:gps:tracking:

* Installation

** Arch Linux
I found ~owntracks-recorder~ required me to manually install ~pkg-config~ first as the ~PKGBUILD~ doesn't currently list
it as a dependency.

#+begin_src
cd ~/aur
git clone https://aur.archlinux.org/owntracks-{recorder,frontend}.git
cd owntracks-recorder
makepkg -sri
cd ../owntracks-frontend
makepkg -sri
#+end_src

You also need to explicitly install the

** Gentoo

Only the recorder appears to be available in Portage for now.

#+begin_src
emerge -av owntracks-recorder
#+end_src

* Configuration

The following applies to the installation under [[id:a53fa3c5-f091-4715-a1a4-a94071407abf][Arch Linux]] as I deployed this on my VPS.

| Files                           | Description                                     |
|---------------------------------+-------------------------------------------------|
| ~/etc/mosquitto/mosquitto.conf~ | Configuration for the [[https://mosquitto.org/][Mosquitto]] message broker. |
| ~/etc/owntacks-recorder.conf~   | Recorder configuration.                         |
|                                 |                                                 |



** Enable Services

You need to start the Mosquitto Database service as well as the OwnTracks Recorder to be able to get things up and
running. ~owntracks-recorder.service~ is dependent on ~mosquitto.service~ (even though the systemctl doesn't make this
explicit).

#+begin_src
systemctl enable --now mosquitto.service
systemctl enable --now owntracks-recorder.service
#+end_src

** User Configuration


** LetsEncrypt Certificate

#+begin_src
certbot certonly -d owntracks.nshephard.dev
#+end_src

** Nginx Reverse Proxy

Helpfully there is a [[https://github.com/owntracks/recorder#nginx][clear]] example of a reverse proxy. It recommend password protecting the site.

Its important that you change the ~location~ to point to the install which for Arch install should be...

#+begin_src
        location / {
            root   /usr/share/webapps/owntracks-frontend/;
            index  index.html index.htm;
        }
#+end_src

*** Password Protection

You will probably want to setup password protection to the OwnTracks front end. This is [[https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/][documented]] and you will need to
install [[https://aur.archlinux.org/apache-tools.git][apache-tools]] from the AUR repository.

Create passwords for two users

#+begin_src
htpasswd -c /etc/nginx/.htpasswd user1
htpasswd /etc/nginx/.htpasswd user2
#+end_src

Add authentication to the ~location~ section of the reverse proxy

#+begin_src
        location / {
            root   /usr/share/webapps/owntracks-frontend/;
            index  index.html index.htm;
            auth_basic "OwnTracks Site";
            auth_basic_user_file /etc/nginx/.htpasswd;
        }
#+end_src


** Start Services

#+begin_src
systemctl enable --now mosquitto.service
systemctl enable --now owntracks-recorder.service
systemctl restart nginx.service
#+end_src
* Links

+ [[https://github.com/owntracks/recorder#building-from-source][Building from Source]]
