:PROPERTIES:
:ID:       5253f936-28e2-416c-8541-6081c1ac4f0c
:mtime:    20251219073009 20251214110433 20250317072302 20240715081115 20240701052946 20240630202230 20240617091334 20240511204735 20240511084447
:ctime:    20240511084447
:END:
#+TITLE: Photography
#+FILETAGS: :photography:pictures:

* Cameras

+ [[id:89d15c28-6227-4671-b6a5-ab1b242423ef][Nikon D50]]
+ Nikon D90
+ Canon S95
+ [[id:1333529b-ea55-4ee8-aa4d-26aba712f0b5][Fuji X-T2]]
+ [[id:4e139c27-3f5d-4456-9a43-1c6cff35eb03][Sony RX100 IV]]


* Software

** Darktable

** Hugin

* Hosting

** Flickr

I've been a long time [[https://www.flickr.com/photos/slackline][Flickr]] user and have stuck with it despite the change of hands and increasing costs.

*** API

Details of Flickr API are at [[https://www.flickr.com/services/feeds/][Flickr Services]].

*** Flickr.org

There is also [[https://www.flickr.org/about-us/][Flickr Foundation]] which aims to preserve and make available the corpus of photos to future generations
which seems like a great idea as in the future when I'm dead I won't care if people use my photos.

** [[https://unsplash.com/][Unsplash]]

Not so much a hosting service /per se/ but a place where you can give away your pictures for others to use. Not really
investigated much but presumably you can access your own photos after uploading them!

** Ente

A privacy respecting photo back-up service. [[https://ente.io][Ente]] provides 10GB of end-to-end encrypted hosting for free. Beyond that you
have to take out one of their paid plans. Theses are quite expensive compared to Flickr.

** [[https://chronoframe.bh8.ga/][ChronoFrame]]

Another self-hosted option, includes AWS S3 storage options.
