:PROPERTIES:
:ID:       899eb7a6-22d6-493a-a67f-b05bd89917d0
<<<<<<< Updated upstream
:mtime:    20251212222746 20251205094419 20251109091653 20251031210041 20250624075947 20240716154936
||||||| Stash base
:mtime:    20251205094419 20251109091653 20251031210041 20250624075947 20240716154936
=======
:mtime:    20251215104153 20251205094419 20251109091653 20251031210041 20250624075947 20240716154936
>>>>>>> Stashed changes
:ctime:    20240716154936
:END:
#+TITLE: Browsing Privacy
#+FILETAGS: :privacy:browser:firefox:


* Librewolf
Using the modified [[https://librewolf.net/][Librewolf]] (based on Firefox) is a good option to minimise tracking by default. It is worth reading
their [[https://librewolf.net/docs/settings/][settings]] documentation on how to enable/disable certain features.

The developers likely disable "AI" features that Mozilla seem hell-bent on adding but in case they don't
[[https://equk.co.uk/2025/10/28/firefox-forcing-llm-features/][here]] are the ones that need explicitly disabling either
in ~about.:config~ or to the ~pref.js~ file (not yet sure where this lives!)

#+begin_src javascript :tangle no
user_pref("browser.ml.enable", false);
user_pref("browser.ml.chat.enabled", false);
user_pref("browser.ml.chat.hideFromLabs", true);
user_pref("browser.ml.chat.hideLabsShortcuts", true);
user_pref("browser.ml.chat.page", false);
user_pref("browser.ml.chat.page.footerBadge", false);
user_pref("browser.ml.chat.page.menuBadge", false);
user_pref("browser.ml.chat.menu", false);
user_pref("browser.ml.linkPreview.enabled", false);
user_pref("browser.ml.pageAssist.enabled", false);
user_pref("browser.tabs.groups.smart.enabled", false);
user_pref("browser.tabs.groups.smart.userEnable", false);
user_pref("extensions.ml.enabled", false);
#+end_src

* Extensions

There are a wealth of browser extensions available for Firefox (and many on mobile too).

+ AdNauseum
+ ClearURLs
+ Decentraleyes
+ Facebook Container
+ Firefox Multi-Account Containers
+ Forget Me Not
+ I Don't Care About Cookies
+ Piped Redirects
+ Temporary Containers
+ UTM Remover
+ UntrackMe
+ uBlock Origin


** Mobile

You can disable Firefox's Facebook data collection by following the instructions [[https://fosstodon.org/@thomholwerda@exquisite.social/112795429462507951][here]].

* Translations

You can use Firefox/LibreWolf to translate text/URLs by heading to ~about:translations~. Its slow the first time as
presumably its downloading something in the background to do the translation, but after that initial translation for
each language it's pretty fast and efficient.

* Online Safety Act

This poorly thought out legislation is full of problems

** Including VPNs

A recent proposal amendment to include VPN service providers is also poorly thought out.

+ [[https://decoded.legal/blog/2025/12/a-proposed-legislative-amendment-to-attempt-to-compel-vpn-services-providers-to-prevent-anyone-under-18-in-the-uk-from-using-their-vpns/][A proposed legislative amendment to attempt to compel VPN services providers to prevent anyone under 18 in the UK from
  using their VPNs]]

* Links

+ [[https://dl.acm.org/doi/10.1145/3696410.3714548][The First Early Evidence of the Use of Browser Fingerprinting for Online Tracking | Proceedings of the ACM on Web Conference 2025]]
+ [[https://blog.rebeltechalliance.org/know-your-enemy-pt-1-google/][Know Your Enemy Part 1 - Google]]
+ [[https://blog.rebeltechalliance.org/know-your-enemy-pt-2-meta/][Know Your Enemy Part 2 - Meta]]
+ [[https://www.peekmyip.com/p/anonymizing-networks.html][Self-Contained Anonymizing Network: Private, Secure Communication System | PeekMyIP]]
