:PROPERTIES:
:ID:       3b8242c4-772a-408e-84bc-6b0e1777aa36
:mtime:    20230922202237 20230920223047 20230920170217 20230920155200
:ctime:    20230920155200
:END:
#+TITLE: Python Napari
#+FILETAGS: :python:visualisation:

+ [[id:04ef0490-a655-4609-94fe-0aa2f2b1bf49][Napari Training]]


* Setup

A [[https://github.com/napari/napari-plugin-template/][template]] system is provided by Napari developers to make it easy to setup and get started with developing a plugin.

Using it is straight-forward providing you have [[id:99d3e5a1-bf9b-44f3-afc9-fed5ffead7bd][Python uv]] installed, all you need to do is decide on the ~name~ of your
repository. Following the Python convention distribution packages should use /dashes/ (~-~) between words and these
will be translated to /underscores/ (~_~) for files and modules.

#+begin_example
uv tool run --with jinja2-time --with npe2 --python=3.11 copier copy --trust https://github.com/napari/napari-plugin-template <name>
#+end_example

You will then be prompted for answers to a number of questions about the repository and what features to install,
including whether to add templates for some basic plugins and whether to include [[id:c76767c4-2a49-42f8-a323-a6d6105e0bce][Pre-commit]].

Once this has been created you will likely want to create a repository on a [[id:52b4db29-ba21-4a8a-9b83-6e9a8dc02f41][GitHub]] or other forge (e.g. [[id:240b85db-27c9-4848-9d3f-c3be841a193b][Codeberg]] or
[[id:736537b3-75e0-4c24-9156-364937e0e8a2][Forgejo]]) to back your data up to. It should be an empty repository and once cloned

** Additions to ~.gitignore~

I added the following to ~.gitignore~

#+begin_example
# Spyder project settings
.spyderproject
.spyproject
# Environments
.env
.venv
env
venv/

# ruff
.ruff_cache/
# OS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
# pytest-testmon
.testmondata*
# Emacs
\#*
*~
# Other directories
tmp/
#+end_example

** Create a Virtual Environment

Create a [[id:4bf1c297-d00a-4857-9339-8017c27138c6][Python Virtual Environments]] to develop your code under. I used [[id:99d3e5a1-bf9b-44f3-afc9-fed5ffead7bd][Python uv]] again to do this in conjunction with
[[id:a4af96d2-f895-4a68-9419-d482d2850f4d][Direnv]] to create the virtual environment within the ~.venv~ of the current directory and ensure it is loaded when
~cd~ing into the directory (or opening files under [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]]).

#+begin_example
uv venv -p 3.11 .venv
echo "source .venv/bin/activate"
direnv allow
#+end_example

* Structure

** ~napari.yaml~

Within the ~src/<package_name>/~ directory the key file ~napari.yaml~ will have been created. This is the key file for
writing Napari plugins and serves as the entry point (defined in ~pyproject.toml~).

| Field           | Description                                                                              |
|-----------------+------------------------------------------------------------------------------------------|
| ~name~          | Package name                                                                             |
| ~display_name~  | Name used to display the plugin in the Napari Plugin menu                                |
| ~visibility~    | Whether the package should be ~public~ or ~private~                                      |
| ~contributions~ | [[https://napari.org/stable/plugins/technical_references/contributions.html][Contributions]] extend the functionality of Napari, there are several types detailed below |

*** ~contributions~

[[https://napari.org/stable/plugins/technical_references/contributions.html][Contributions]] can be one of the following.

| Contribution  | Description                                                                                                                                          | Fields                                                                                                                                                                                                                         |
|---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ~commands~    | Adds a Python callable (i.e. command) with descriptors. All subsequent contributions must have a ~command~ field that maps to the ~id~ of one entry. | ~id~, ~title~ (optional) and ~python_name~ ()                                                                                                                                                                                  |
| ~readers~     | Add functions to read files.                                                                                                                         | ~command~ which has a corresponding ~command.id~ field, ~filename_patterns~ for restricting to particular file extensions and ~accepts_directories~ an optional Boolean.                                                       |
| ~writers~     | Add functions to write files.                                                                                                                        | ~command~ which has a corresponding ~command.id~ field, ~layer_types~ for the list image layers to write, ~filename_extensions~ for compatible file extensions and ~display_name~ which if present is used in the Save dialog. |
| ~widgets~     | Adds widgets to the viewer.                                                                                                                          | ~command~ which has a corresponding ~command.id~ field, ~display_name~ for the widget, ~autogenerate~ a boolean, if ~True~ then [[https://pyapp-kit.github.io/magicgui/][magicgui]] will be used.                                                                         |
| ~sample_data~ | For generating sample data                                                                                                                           | ~command~ which has a corresponding ~command.id~ field, ~display_name~ for the item, ~uri~ valid path or URL to data resource, ~reader_plugin~ optional name of plugin to open the URI.                                        |
| ~themes~      | Adds a colour theme to Napari                                                                                                                        | Various see documentation                                                                                                                                                                                                      |
| ~menus~       | For adding menus to Napari to access functions.                                                                                                      | ~command~ which has a corresponding ~command.id~ field, ~when~ optional condition to show the item if ~True~, ~group~ for sorting and grouping menu items.                                                                     |
| ~submenus~    | For adding submenus to Napari to access functions                                                                                                    | ~command~ which has a corresponding ~command.id~ field,                                                                                                                                                                        |

"Widgets" are graphical interfaces where configuration options can be adjusted viz. buttons, labels, text fields and
sliders.

** Code

The template uses a [[https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/][src layout]] and so files reside under ~src/<package_name>~ adjacent to ~napari.yaml~. It seems the
convention is to make modules "private" by preceding them with ~_~ (underscore) as it is unlikely they will (or should)
be imported by other modules.

*** MagicUI

Napari leverages [[https://pyapp-kit.github.io/magicgui/][magicgui]] to make it easier to construct "widgets" and there are a number of [[https://pyapp-kit.github.io/magicgui/generated_examples/napari/napari_parameter_sweep/][examples]] in the
documentation. Here is a simplified version that I actually understand.

We leverage the `@magic_factory()` decorator and for each argument of the function that is being decorated (bar the
`image` argument which Napari seems to sort out on its own) we define a dictionary with a bare minimum of a ~label~
key. The value of this ~label~ key should be a string and is the text that is displayed against the option. If there are
not other key/value pairs then this includes a simple text box which is appropriate for a boolean parameter. If a
numerical value is required to be input then you can include key the keys `min`, `max` and `step` which define the range
and the increments the slider adjusts in. An illustrative example is shown below...

#+begin_example python
"""View images in three dimensions."""

from typing import TYPE_CHECKING

import napari.types
from magicgui import magic_factory
from napari import current_viewer  # pylint: disable=no-name-in-module
from napari.layers import Image
from napari_topostats.utils import afm2stack

if TYPE_CHECKING:
    import napari


@magic_factory(
    by_slices={"label": "Whether to stack by slices."},
    numslices={"label": "Number of slices.", "min": 20, "max": 2000, "step": 1},
    resolution={"label": "Resolution.", "min": 1.0, "max": 100.0, "step": 0.1},
)
def view_3d(
    image: Image,
    by_slices: bool = True,
    numslices: int = 255,
    resolution: float = 1.0,
) -> napari.types.LayerDataTuple:
    """
    View image in three dimensions.

    Parameters
    ----------
    image : Image
        Image to be viewed in three dimensions.
    by_slices : bool
        Whether to stack by slices (default ``True``). If ``False`` then ``resolution`` is used.
    numslices : int
        Number of slices to create.
    resolution : float
        The resolution/distance between each slice, by default 1.0.

    Returns
    -------
    napari.types.LayerDataTuple:
        Modified image in three-dimensions.
    """
    three_dimensions = afm2stack(image=image.data, by_slices=by_slices, numslices=numslices, resolution=resolution)
    viewer = current_viewer()
    viewer.dims.ndisplay = 3
    return (
        three_dimensions,
        {"name": f"{image.name}_3D"},
        "image",
    )
#+end_example

Here the plugin component has three "widgets", a tick box for whether to stack slices which is stored in ~by_slices~,
the number of slices (~numslices~) which can be between ~20~ and ~2000~ in steps of ~1~ and the resolution which can be
between ~1.0~ and ~100.0~ in steps of ~0.1~. These map directly to the arguments of the ~view_3d()~ function which is a
thin wrapper to ~afm2stack()~. In this instance the current viewer is obtained and the number of display dimensions is
increased to ~3~ (as this renders a 2D image in 3D). Finally a ~LayerDataTuple~ is returned.

To get this working you add the following to ~napari.yaml~.

#+begin_example yaml
contributions:
  commands:
    - id: napari-afmslicer.view_3d_widget
      python_name: napari_afmslicer.view_3d_widget:view_3d
      title: AFMSlicer 3D Viewer
  widgets:
    - command: napari-afmslicer.view_3d_widget
      display_name: AFMSlicer 3D Viewer
  menus:
    napari/layers/filters:
      - submenu: filtering_submenu
    filtering_submenu:
      - command: napari-afmslicer.view_3d_widget

  submenus:
    - id: filtering_submenu
      label: Filtering

#+end_example
* Links

+ [[https://chanzuckerberg.github.io/napari-plugin-accel-workshops/workshops/softwaredev][napari Plugin Accelerator Grant workship series]]
** Development

+ [[https://napari.org/stable/plugins/best_practices.html][Napari Best Practices]]
+ [[https://github.com/napari/napari-plugin-template/][napari/napari-plugin-template]]
+ [[https://github.com/napari/cookiecutter-napari-plugin][GitHub - napari/cookiecutter-napari-plugin: Cookiecutter for napari plugins]]

*** Tutorials

+ Napari leverages [[https://pyapp-kit.github.io/magicgui/][magicgui]] to make it easier to construct "widgets" and there are a number of [[https://pyapp-kit.github.io/magicgui/generated_examples/napari/napari_parameter_sweep/][examples]] in the
documentation. Here is a simplified version that I actually understand.

We leverage the `@magic_factory()` decorator and for each argument of the function that is being decorated (bar the
`image` argument which Napari seems to sort out on its own) we define a dictionary with a bare minimum of a ~label~
key. The value of this ~label~ key should be a string and is the text that is displayed against the option. If there are
not other key/value pairs then this includes a simple text box which is appropriate for a boolean parameter. If a
numerical value is required to be input then you can include key the keys `min`, `max` and `step` which define the range
and the increments the slider adjusts in. An illustrative example is shown below...

#+begin_example python
"""View images in three dimensions."""

from typing import TYPE_CHECKING

import napari.types
from magicgui import magic_factory
from napari import current_viewer  # pylint: disable=no-name-in-module
from napari.layers import Image
from napari_topostats.utils import afm2stack

if TYPE_CHECKING:
    import napari


@magic_factory(
    by_slices={"label": "Whether to stack by slices."},
    numslices={"label": "Number of slices.", "min": 20, "max": 2000, "step": 1},
    resolution={"label": "Resolution.", "min": 1.0, "max": 100.0, "step": 0.1},
)
def view_3d(
    image: Image,
    by_slices: bool = True,
    numslices: int = 255,
    resolution: float = 1.0,
) -> napari.types.LayerDataTuple:
    """
    View image in three dimensions.

    Parameters
    ----------
    image : Image
        Image to be viewed in three dimensions.
    by_slices : bool
        Whether to stack by slices (default ``True``). If ``False`` then ``resolution`` is used.
    numslices : int
        Number of slices to create.
    resolution : float
        The resolution/distance between each slice, by default 1.0.

    Returns
    -------
    napari.types.LayerDataTuple:
        Modified image in three-dimensions.
    """
    three_dimensions = afm2stack(image=image.data, by_slices=by_slices, numslices=numslices, resolution=resolution)
    viewer = current_viewer()
    viewer.dims.ndisplay = 3
    return (
        three_dimensions,
        {"name": f"{image.name}_3D"},
        "image",
    )
#+end_example

Here the plugin component has three "widgets", a tick box for whether to stack slices which is stored in ~by_slices~,
the number of slices (~numslices~) which can be between ~20~ and ~2000~ in steps of ~1~ and the resolution which can be
between ~1.0~ and ~100.0~ in steps of ~0.1~. These map directly to the arguments of the ~view_3d()~ function which is a
thin wrapper to ~afm2stack()~. In this instance the current viewer is obtained and the number of display dimensions is
increased to ~3~ (as this renders a 2D image in 3D). Finally a ~LayerDataTuple~ is returned.

To get this working you add the following to ~napari.yaml~.

#+begin_example yaml
contributions:
  commands:
    - id: napari-afmslicer.view_3d_widget
      python_name: napari_afmslicer.view_3d_widget:view_3d
      title: AFMSlicer 3D Viewer
  widgets:
    - command: napari-afmslicer.view_3d_widget
      display_name: AFMSlicer 3D Viewer
  menus:
    napari/layers/filters:
      - submenu: filtering_submenu
    filtering_submenu:
      - command: napari-afmslicer.view_3d_widget

  submenus:
    - id: filtering_submenu
      label: Filtering

#+end_example
* Links

+ [[https://chanzuckerberg.github.io/napari-plugin-accel-workshops/workshops/softwaredev][napari Plugin Accelerator Grant workship series]]
** Development

+ [[https://napari.org/stable/plugins/best_practices.html][Napari Best Practices]]
+ [[https://github.com/napari/napari-plugin-template/][napari/napari-plugin-template]]
+ [[https://github.com/napari/cookiecutter-napari-plugin][GitHub - napari/cookiecutter-napari-plugin: Cookiecutter for napari plugins]]

** Plugins

+ [[https://biapol.github.io/Quantitative_Bio_Image_Analysis_with_Python_2022/day4c_crafting_napari_plugins/01_creating_widgets_from_functions.html][Creating Widgets from Functions — Quantitative Bio-image Analysis with Python]]

** Plugins

+ [[https://pypi.org/project/cellfinder-napari/][cellfinder-napari]]
