:PROPERTIES:
:ID:       251b3ae4-4a5c-4c44-909a-dcbc0aef4b45
:mtime:    20230103103309 20221228151331 20230103103309 20230103103308
:ctime:    20221228151331 20230103103308
:END:
#+TITLE: Quarto
#+DATE: <2022-05-24 Tue 22:07>
#+FILETAGS: :reproducibility:literate programming:

[[https://quarto.org/][Quarto]] is a [[id:ab2f5dfb-e355-4dbb-8ca0-12845b82e38a][literate programming]] engine based on [[https://pandoc.org/][Pandoc]] that supports multiple scientific languages ([[id:de9a18a7-b4ef-4a9f-ac99-68f3c76488e5][R]], [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]], [[id:67f03851-d5bf-46ea-a7f5-14dfbaa7c61c][Julia]]
and [[https://observablehq.com/@observablehq/observables-not-javascript][Observable]]). Its syntax has a lot in common with other literate programming languages such as [[id:ca27ae38-f187-4a3c-803f-b36ee2cfa374][RMarkdown]] and [[id:6e75f9df-df3d-4402-b5ad-ed98d0834e08][Org
Babel]] in so much as code chunks have parameters which handle how they are processed and then displayed in the resulting
document.

* Blogging
:PROPERTIES:
:ID:       25c4a623-fc4c-4902-8f28-f54949e26299
:mtime:    20230103103313 20221228151331 20230103103308
:ctime:    20221228151331 20230103103308
:END:

Blogging is simple with Quarto.

* Presentations
:PROPERTIES:
:ID:       29a2113e-484c-42f3-b200-76a569066c3b
:mtime:    20221228151331 20230103103311
:ctime:    20221228151331
:END:

** RevealJS
:PROPERTIES:
:ID:       0cfcd756-03fa-4150-a685-4a31d8197c54
:END:

* Websites
:PROPERTIES:
:ID:       2a6ded3a-68ba-4f05-ac0c-f1fa29fdcec4
:END:

* Books
:PROPERTIES:
:ID:       0ce8dca8-d0c7-40e9-a629-01e03a8d7a44
:mtime:    20230103103308 20221228151331
:ctime:    20221228151331
:END:

* Code
:PROPERTIES:
:ID:       db0e802e-d990-40c0-9c29-6bd067f4f546
:mtime:    20221228151331
:ctime:    20221228151331
:END:

There are a number of options you can apply to code blocks. The ~code_fold: true~ options will hide code blocks in the
rendered HTML but with a little arrow to expand them. ~code_tools: true~ will put links to the documentation of
functions used in a code block. ~code_link: true~

#+begin_example yaml
  execute:
    code_fold: true
    code_link: true
    code_tools: true
#+end_example

I found these global options didn't work under blogs, although
* Previewing
:PROPERTIES:
:ID:       8e0f1277-6058-4135-8483-20b1ace75161
:END:

You can preview documents easily, from within [[id:754f25a5-3429-4504-8a17-4efea1568eba][Emacs]] bind the following.

#+begin_example emacs-lisp
  (use-package quarto-mode
	     :mode (("\\.Rmd" . poly-quarto-mode))
	     :bind (("C-c q" . quarto-preview)))
#+end_example

 You can set [[https://quarto.org/docs/reference/projects/options.html#preview][options for ~preview~ ]] in the YAML header, most usefully is fixing the ~host~ and/or ~port~ so you don't
  get a new browser tab each time you preview.

#+begin_example yaml
  ---
  project:
    ...
    preview:
      port: 9999
      host: 127.0.0.1
      browser: true
      watch-inputs: true
      navigate: true
#+end_example

* Links
+ [[https://t.co/FDlvjq4qrc][quarto.org]]
+ [[https://hbiostat.org/rflow/][R Workflow]] : Reproducible Biomedical Research using Quarto
+ [[https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/][A Quarto tip a day]]

** GitHub

+ [[https://github.com/quarto-dev/quarto-actions/][quarto-dev/quarto-actions]]
