:PROPERTIES:
:ID:       de9a18a7-b4ef-4a9f-ac99-68f3c76488e5
:END:
#+TITLE: R
#+DATE: [2022-02-13 Sun 19:51]
#+FILETAGS: :r:programming:statistics:

[[https://www.r-project.org][R]] is a statistical programming language, written and developed initially by statisticians for statisticians. It is based
on the statistical programming S.

* Tidyverse

The Tidyverse refers to a group of packages that work in unison to simplify the process of writing readable code. Read
more on the [[id:b4510762-8409-4e5e-8ee8-c27574977772][Tidyverse]].

* ~data.table~
  :PROPERTIES:
  :ID:       af60974e-e132-48d0-a1ad-8137ee50f4b9
  :END:
* RStudio

[[https://www.rstudio.com/][RStudio]] is an Integrated Development Environment (IDE) for working with R and more recently other languages. Read more
on [[id:fbe4e0bc-038d-4aeb-aa48-e312f469678e][RStudio]].

* RMarkdown
[[https://rmarkdown.rstudio.com/][R Markdown]] is a markup language that weaves [[id:0c371287-128d-4e46-8128-b2d4f5fc604c][markdown]] with code to facilitate producing reproducible workflows. It can
render to HTML, PDF (via [[id:e1c2cfef-1b43-47a8-a425-94e6ae58d917][latex]]) or produce interactive Shiny applications. Read more on [[id:1db6158d-cb5d-4b73-b926-95e9c09f878b][RMarkdown]].

* Shiny

Shiny provides a framework for creating interactive web-pages from within R. Read more on [[id:fe1f6380-9217-482c-bb5e-91817ae3e8f8][Shiny]].

There are a few ways in which dashboards can be created. The package [[https://rinterface.github.io/bs4Dash/index.html][bs4Dash]] is /A Bootstrap 4 Version of
shinydashboard/ and as v2.0.0 its as simple as switching from ~library(shinydashboard)~ to ~library(bs4Dash)~

* Community
:PROPERTIES:
:TITLE: R community
:ID:       e7011db4-16fc-4cde-bb81-4d172cb0db14
:END:

There is a wonderful community around R online. Gone are the days of trepidation about posting on [[https://stat.ethz.ch/mailman/listinfo/r-help][R-help]] only to get
chided for not being clear enough about the problem. These days there is [[https://stackoverflow.com/questions/tagged/r][StackOverflow]] and [[https://stats.stackexchange.com/][CrossValidated]], [[https://www.tidytuesday.com/][Tidy Tuesday]]

** Seeking Help
:PROPERTIES:
:ID:       bbe26fc4-9c87-477b-ab93-eeec4449bc4b
:END:

It can be daunting asking questions about something you don't feel you understand particularly well. Often a seed of
doubt about whether it is even a valid question will be there, the fear of "looking stupid". Anyone who fails to
acknowledge that there are beginners ("newbies") in any area of life is probably not worth worrying too much about, even
if they are held in high-regard within a community. Listen to the people who are willing to help you as you will learn
more from them than an aloof answer.

That said there are things that you can do to help those who's assistance you seek answer your question. This is not a
new topic and there are examples out there such as Eric S. Raymond [[http://www.catb.org/esr/faqs/smart-questions.html][How To Ask Questions The Smart Way]] (on which some of
this advice is based, although that article is heavily orientated towards Computer Science)

+ Start by searching, chances are someone has had the same question before and an answer is out there somewhere. Include
  links to some of the threads you might have found but explain why they didn't answer your question/problem. This
  avoids people responding with "/Use the search/" as it demonstrates you have tried doing so already.
+ Be explicit and give a working example that demonstrates the problem you have.
+ Show your code and the result it gives (in text, not screen shots so that others can copy and paste it and modify it)
  and explain what you were expecting.
+ Take the time to develop a reproducible example (the package [[https://reprex.tidyverse.org/][reprex]] can help here). Often you will find when creating
  a small self-contained example that you actually understand the problem better and solve it yourself before getting
  round to posting it on a forum. This is a form of [[https://rubberduckdebugging.com/][Rubber Duck Debugging – Debugging software with a rubber ducky]] and
  is quite satisfying.
+ Remember what is urgent for you won't be for those you are asking to spend their free time helping you for no benefit
  to them whatsoever (i.e. its often their free time).
+ In the same vein if you're asked for more information or to provide an example clarifying your problem take the time
  to do so.
+ Keep conversations open. People are helping for free and the information should remain visible to anyone else who is
  searching for assistance in the future. Don't message people privately asking for help.

** R User Groups
:PROPERTIES:
:ID:       d76ffaee-8e40-4d36-a901-80401a4cc836
:END:

There are a lot of R user groups and there is no single definitive list, below are links to some.

+ [[https://benubah.github.io/r-community-explorer/rugs.html][R Community Explorer]] a Shiny Dashboard which is regularly updated, probably your best first port of call when looking
  for an R user group.
+ [[https://www.meetup.com/pro/r-user-groups/][R User Groups - Meetup]]
+ [[https://jumpingrivers.github.io/meetingsR/r-user-groups.html][R User Groups]] curated by
* Development
:PROPERTIES:
:ID:       61a19339-e706-4f93-b98c-f5b336d0f280
:END:
At some point you may want to delve further into writing more structured code in R and write your own package. This can
be a good way of organising your work and making it reproducible and available to others, but for this to be effective
there are some principles which should be followed and thanks to the work of others there are many tools available to
help with that. An excellent resource is the [[https://r-pkgs.org/][R Packages book by Hadley Wickham and Jenny Bryan]]

** testthat
:PROPERTIES:
:ID:       206d377a-f739-4cb9-afa7-8f3956ca2e38
:END:
** roxygen2
:PROPERTIES:
:ID:       02920384-18c3-4e27-8a63-29a693ab16d0
:END:

* Links
** Books
+ [[https://r-pkgs.org/][R Packages]]
+ [[https://r4ds.had.co.nz/][R for Data Science]]
+ [[https://rstudio-education.github.io/hopr/][Hands-On Programming with R]]
+ [[https://ggplot2-book.org/index.html][ggplot2]]
+ [[https://adv-r.hadley.nz/][Advanced R]]
+ [[https://r-graphics.org/][R Graphics Cookbook, 2nd edition]]
+ [[https://geocompr.robinlovelace.net/][Geocomputation with R]]
+ [[https://www.bayesrulesbook.com/][Bayes Rules! An Introduction to Applied Bayesian Modeling]]
+ [[https://epirhandbook.com/en/][The Epidemiologist R Handbook : R for applied epidemiology and public health]]
+ [[http://hbiostat.org/rflow/][R Workflow for Reproducible Biomedical Research Using Quarto]]
+ [[https://argoshare.is.ed.ac.uk/healthyr_book/][R for Health Data Science]]

** HowTos

+ [[https://www.tidyverse.org/blog/2019/09/callr-task-q/][Multi Process Task Queue in 100 Lines of R Code]]

*** Videos

+ [[https://www.youtube.com/@brodriguesco/videos][brodriguesco on YouTube]] - lots of useful tips and tricks.

** Packages and Documentation

+ [[https://r-universe.dev/search/][ROpenSci : R-universe]]
+ [[https://www.rdocumentation.org/][RDocumentation]]
+ [[https://rdrr.io/][R Package Documentation]]

*** Genetics

+ [[https://www.slendr.net/][A Simulation Framework for Spatiotemporal Population Genetics • slendr]]

** ROpenSci
+ [[https://docs.ropensci.org/occCite/][Querying and Managing Large Biodiversity Occurrence Datasets • occCite]]
+ [[https://docs.ropensci.org/osmextract/][Download and Import Open Street Map Data Extracts • osmextract]]
+ [[https://docs.ropensci.org/jqr/][Client for jq, a JSON Processor • jqr]]
