:PROPERTIES:
:ID:       4c9eab3d-4ae2-4f48-a32c-925929fe60bf
:END:
#+title: Open Research Data
#+date: [2022-02-15 Tue 14:02]
#+filetags: :open-research::data:
* Open Data

The FAIR principles are that data is Findable, Accessible Interoperable and Reusable. They are not rigorous in their
formulation but are rather meant to encourage researchers to think about how their data could be curated in such a
manner that it is usable by others.

A major feature therefore lies around what metadata is used to describe the data contained within. This should be rich
in detail so that the content is well described and to make it findable it should include a globally unique and
persistent identifier, that makes it possible to retrieve the data

* Data Version Control

Version controlling data is just as important as version controlling your software if you are to make your analysis
reproducible. To that end tools like [[https://dvc.org/][DVC]] and [[https://dagshub.com/][dagshub]] make life simpler, although with hosting of data on forges care and
consideration should be given to principles of GDPR.

* Links
+ [[https://theodi.org][The Open Data Institute]]
+ [[http://opendsi.cc][Open Data Science Initiative]]
+ [[https://www.pachyderm.com/][Pachyderm | The Data Foundation for Machine Learning]]
+ [[https://dataverse.scholarsportal.info/][Scholars Portal Dataverse]]
+ [[https://www.jisc.ac.uk/guides/rdm-toolkit][Research data management toolkit | Jisc]]

** Articles
+ [[https://www.nature.com/articles/sdata201618][The FAIR Guiding Principles for scientific data management and stewardship | Scientific Data]]
+ [[https://rd-alliance.org/group/fair-research-software-fair4rs-wg/outcomes/fair-principles-research-software-fair4rs-0][FAIR Principles for Research Software (FAIR4RS Principles) | RDA]]

** Tools
+ [[https://opentelemetry.io/][OpenTelemetry]]

** Journals
+ [[https://www.nature.com/sdata/][Scientific Data]]
