:PROPERTIES:
:ID:       60bd7406-c4c2-4316-8517-cb9d1cac8f35
<<<<<<< HEAD
:mtime:    20250721065203 20230914192913 20230528221730
||||||| parent of 879139f (sheffield: adding weather details)
:mtime:    20230914192913 20230528221730
=======
:mtime:    20250721083639 20250721065203 20230914192913 20230528221730
>>>>>>> 879139f (sheffield: adding weather details)
:ctime:    20230528221730
:END:
#+TITLE: Sheffield
#+FILETAGS: :sheffield:

Sheffield is the city I call home and have done since I started living here in 1995 when I moved to study Zoology and
Genetics for three years. I graduated and returned to my parents only to come back to Sheffield a year later to study
Genetic Epidemiology. Despite a brief sojourn to Perth, Western Australia, which wasn't all it was sold to me as, I
returned to Sheffield and like it. Its friendly, green and close to lots of rock climbing in the Peak District. Its not
too far to get to North Wales, the Lake District or Northumberland. Scotland can just about be done in a day too and my
parents don't live too far away.

* Links

** Council

+ [[https://sheffieldactivetravelmap.commonplace.is][Sheffield Commonplace Active Travel Map]]

** Weather

+ [[https://www.sheffieldweather.co.uk/index.htm][South West Sheffield weather]]
+ [[https://check-for-flooding.service.gov.uk/station/9441][Meers Brook level at Sheffield Meersbrook]] (wider [[https://check-for-flooding.service.gov.uk/river-and-sea-levels?v=map-live&lyr=mv,ri,ti,gr,rf&ext=-1.556249,53.325115,-1.37907,53.386163&fid=stations.9441][map]])
