:PROPERTIES:
:ID:       3899f7f8-bc4a-4228-b922-5b9bb361106c
:END:
#+TITLE: Statistical Genetics
#+DATE: [2022-02-19 Sat 13:19]
#+FILETAGS: :genetics:statistics:

* Linkage Analysis
:PROPERTIES:
:ID:       543f41e3-63ba-45c7-963c-6a01ec45cd5d
:END:

 Linkage analysis focuses on pedigrees (families) where a disease segregates and occurs more frequently than the
 population at large. Often who within the pedigree is affected will indicate the inheritance pattern, X-linked,
 autosomal, dominant or recessive but variable penetrance, where not everyone who has a particular genotype expresses
 the phenotype, can make it hard to determine the inheritance pattern.

 Because recombination between chromosomes during meiosis that produces gametes is relatively rare closely related
 individuals share large sections of chromosomes with each other and by genotyping markers at known locations the
 relative position of genes segregating with disease can be identified. With larger, extended pedigrees there is greater
 scope for recombination events and so the region of DNA that can be identified as harbouring linked genes becomes
 smaller. You don't need to have DNA samples from older members of a pedigree where a disease is segregating as their
 genotypes can be inferred from their ancestors.

* Association Analysis
:PROPERTIES:
:ID:       5346ee87-dee7-45a0-81ff-51d0fe03d047
:END:

Extending the unobserved pedigree to the population level allows for population level association analyses to be
conducted, and underpins the now commonly used approach of Whole Genome Association Scans (WGAS).

* Statistical Genetic Software
:PROPERTIES:
:ID:       b48ba435-be96-443c-98f4-2baf3fc9596e
:END:

A lot of specialist software has been written over the years to conduct genetic association analyses. Old programmes
such as Genehunter were superseeded by re-implementations such as [[http://csg.sph.umich.edu/abecasis/Merlin/][MERLIN by Goncalo Abecasis]]. An excellent tool which
integrates with [[id:de9a18a7-b4ef-4a9f-ac99-68f3c76488e5][R]] for Genome Wide Association Scans is [[https://www.cog-genomics.org/plink2/][PLINK (v1.9)]]

* Links

** Software

+ [[https://gaow.github.io/genetic-analysis-software/0/][The Rockefeller List :: Genetic Analysis Software | The Rockefeller List]]
