:PROPERTIES:
:ID:       a1b78518-31e8-4fd3-a36f-d8f152832138
:mtime:    20251116133853 20240419193336 20230911222408 20230103103312 20221211195020
:ctime:    20221211195020
:END:
#+TITLE: ZSH
#+DATE: [2022-12-11 Sun 19:36]
#+FILETAG: :shell:zsh:

[[https://www.zsh.org/][ZSH]] is a shell, as with [[id:9c6257dc-cbef-4291-8369-b3dc6c173cf2][Bash]] it leverages the [[id:2b537cf2-b3aa-486b-a8e7-0d86a4fb1938][Readline]] library to facilitate navigating the text on the prompt and
searching history.

* Oh-my-zsh

* Tips & Tricks

** Pip install optional extras

I found the hard way that ZSH uses square brackets (~[ ]~) for globbing when I was trying to install optional additional
packages using [[id:5b5d1562-ecb4-4199-b530-e7993723e112][Python]] package manager [[id:47543a76-a873-4c07-b30d-926f50b31fca][pip]] which takes the format.

#+begin_src sh :eval no
  pip install .[optional_extra]
#+end_src

To get round this you can either quote the target

#+begin_src sh :eval no
  pip install ".[optional_extra]"
#+end_src

Or put an alias in ~/.zshrc~

#+begin_src sh :eval no
  pip='pip noglob'
#+end_src

** zmv

This is a neat extension to ~mv~ that facilitates [[https://blog.smittytone.net/2021/04/03/how-to-use-zmv-z-shell-super-smart-file-renamer/][batch file renaming]].

To enable it add the following to ~.zshrc~

#+begin_src sh :eval no
  autoload zmv
#+end_src

* History

There are a few options, tools and plugins for working with history. Ensuring there are no duplicates is really useful
as is setting the maximum size of your history to a very high level so that you retain a lot of your history.

I have the following options set.

#+begin_src sh
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
export HISTTIMEFORMAT="[%F %T]"
export HIST_STAMPS="yyyy-mm-dd"
export SAVEHIST=100000
export HISTSIZE=5000
#+end_src

** Tips and Tricks

+ Start a command with a space it /won't/ be saved in your history. Useful for sensitive commands that include passwords
  or keys.


** Atuin

[[id:f74f50d3-9d99-4082-8733-84f139fddea1][Atuin]] is a tool for syncing, searching and backing up shell history.

* Links

+ [[https://www.zsh.org/][ZSH]]
+ [[https://grml.org/zsh/zsh-lovers.html][ZSH Lovers]]
+ [[https://github.com/robbyrussell/oh-my-zsh][oh-my-zsh]]
+ [[id:f74f50d3-9d99-4082-8733-84f139fddea1][Atuin]]

** Extensions

+ [[https://github.com/zsh-users/zsh-completions][zsh-completions]]
